### ISSUE TITLE
Build.cmd can occasionally leave auto-started SelfHostedWcfService.exe running

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1098]
When you use this script to start an OuterLoop run against the self-hosted service:
```
  build.cmd /p:WithCategories=OuterLoop
```
it will periodically not call the cleanup code when it is done, leaving SelfHostedWcfService.exe running.  In a CI environment this will be bad for 2 reasons: (1) inability to 'git clean' and (2) the default logic will autodetect SelfHostedWcfService.exe is already running and will use it -- even though it is stale and probably uses services for a different PR.

I've seen this twice, but it is timing related and may need to be repro'ed with some manual intervention.  In my case, I witnessed these happening on a clean enlistment:
 - Build.cmd detected OuterLoop was needed and auto-started the SelfHostedWcfService
 - Because build.cmd was doing a major package restore, it took near 100% of the cpu
 - SelfHostedWcfService.exe was stalled by the package restore overhead and took longer than expected to initialize ports, etc before it could start the services.
 - The ping script eventually timed out and reported it could not ping the services, returning an error code to the main script

The main script therefore believed the services were not running and therefore did not need to be cleaned up.

Recommendation: if the script even *attempts* to auto-start the services, it *must* call the cleanup code, regardless what errors happen.

**Comment by zhenlan** [comment]
Two things we potentially can do to tackle this
- Do "ping" in a loop with a maximal timeout
- Call cleanup more aggressively in build.override.targets, for example, do cleanup if "start service script said it started the service" OR "ServiceUri is empty".

**Comment by roncain** [comment]
I think the simplest solution is to do an aggressive cleanup on only 1 condition -- that we *attempted* to do any setup at all.  For example, we might have installed certs, configured firewall rules and only then failed to start the service.  The ping only detects the final step.  Any exit code other than "it was already running" should trigger the cleanup code.

**Comment by zhenlan** [comment]
Wouldn't devs have the same problem? We should be very careful of diverging the design or special casing for some particular scenarios as it will add long term maintenance cost and we may just end up having to solve the problem repeatedly in different scenarios.

> do an aggressive cleanup on only 1 condition -- that we attempted to do any setup at all

Just to point out what you said is not much different than the second bullet point I put out there. Basically it's the condition "ServiceUri is empty".

**Comment by roncain** [comment]
I'm not proposing a divergent design -- only fixing an issue that exists in both CI and Dev scenarios.  Fix once, appreciate twice :grinning:

Triggering on the "ServiceUri is empty" case would break the "manually started self-host on my machine" developer scenario. I don't think we want to gate on *why* we chose to setup the machine, only on the fact we *tried*.

**Comment by zhenlan** [comment]
Then it's not 1 condition. It's 2: "ServiceUri is empty" AND "there was not a service running already". This will solve the "aggressive cleanup" problem. It does not solve the problem that ping failed in the first place. If you observed ping always (or most of the time) would fail, why do we even bother to do it? If we want to keep it, we should make it more reliable.

> Triggering on the "ServiceUri is empty" case would break the "manually started self-host on my machine" developer scenario.

For the scenario "manually started self-host on my machine", a dev should really pass a non-empty ServiceUri too. The dev needs to do this for cross machine. The dev should do this for the same machine too even though ServiceUri is localhost in this case. We are doing magic here by auto detecting and optimistically reusing an existing localhost service. This is fragile and causing problems like making cleanup conditions more complex like in this case. I know this is a scenario supported by Bridge, but I have to ask, what is the real benefit of it other than saving some typing of `p:ServiceUri=localhost`?

**Comment by hongdai** [comment]
In the latest version of build.override.targets, I always run clean up except:
* there is a service already running.
* Setup has not been run.

This should have taken care of Ron's original concern.

**Comment by iamjasonp** [comment]
I'd like to see what happens when we run in CI. If true, we will be in a very, very bad state because it'll happen on machines. 

There's two classes of approaches that I've seen here: 
1. Attempt to do detection (check for ServiceUri is empty and check service state) 
2. Cleanup always when we've tried to setup anything. 

The ping problem is orthogonal to this problem about cleanup, IMO. A service that is pingable signifies that the service is ready for use and we can test; conversely though, a service that is _not_ pingable does not imply that the machine is clean. 

"ServiceUri is empty" does not preclude there being a service already running, but it implies we should attempt to start the service. If a service is already running and we run build.cmd /p:WithCategories=Outerloop, what happens to the already-running service? Do we kill it and start fresh? Who owns the start/stop of the already-running service?

For the moment, I care that we don't hang the CI machines or leave them in an unclean state (as good citizens using the CI system). I think @hongdai's solution takes care of that, given that the set of initial conditions on the machine is well-known.

**Comment by zhenlan** [comment]
Agreed with what you said @iamjasonp.

> "ServiceUri is empty" does not preclude there being a service already running, but it implies we should attempt to start the service.

Yes, this is the design.

> If a service is already running and we run build.cmd /p:WithCategories=Outerloop, what happens to the already-running service? Do we kill it and start fresh?

IMHO, we should fail in this case and give an error message something like "We cannot start a new service as we detected there was already a servicing running on local machine. If you want to use the existing service, please pass /p:ServiceUri=localhost to the build.cmd. Alternatively, please shut down the existing service and we will create a new one for you.".

> Who owns the start/stop of the already-running service?

The original owner who started the service owns the already-running service, so we should not kill it when we attempt to start a new one.

**Comment by iamjasonp** [comment]
> "We cannot start a new service as we detected there was already a servicing running on local machine. If you want to use the existing service, please pass /p:ServiceUri=localhost to the build.cmd."

Got it. I personally like the explicitness of this case whereby we force passing in the ServiceUri. 

So in practice, the cleanup conditions: 

> : "ServiceUri is empty" AND "there was not a service running already".
> and 
> I always run clean up except:
> * there is a service already running.
> * Setup has not been run.

Can be reduced to "I always run clean script except when setup has not been run", or, flipping the negative: "I always run clean when setup has been run". 

If a service is already running, by definition setup will not happen due to the explicit bounding conditions  mentioned here: https://github.com/dotnet/wcf/issues/1098#issuecomment-215615545.

More specifically, I think we should be clear that "I always run the cleanup script if the setup script has executed any command that might change the state of the machine"

I think this fixes the Dev scenario (though there's a bit more typing involved), and the CI scenario (we always end up with a clean box).

@hongdai, just to confirm that this is effectively what happens in #1083 as merged?

**Comment by roncain** [comment]
@hongdai solved this issue with #1083.  I would like to close this current issue and carry on discussions regarding ServiceUri on a different thread.

**Comment by zhenlan** [comment]
> I personally like the explicitness of this case whereby we force passing in the ServiceUri.

Exactly! WCF for .NET Core is a x-plat library/framework. I hope we can minimize anything that is special for Windows. We should have a x-plat design in both product and testing.  Getting rid of some Windows specific magic helps to raise the awareness and achieve the x-plat goal.
