### ISSUE TITLE
Server side code should not log to the console.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#1205]
Some server side code here...
...\wcf\src\System.Private.ServiceModel\tools\IISHostedWcfService\App_code\WcfChannelExtensibilityService.cs
Is logging to the Console, this should be removed.

**Comment by roncain** [comment]
@StephenBonikowsky -- we need to merge PR #1325 before tackling this issue, because it alters the MessageInspector tests to not use a flawed workaround.  At that point, I would like to broaden this current issue to include cleaning up the MessageInspector test, probably like this:
- Remove the console logging on the server side
- Rather than write to console, make the server side return the information it would have logged (not the silly messages -- just the wind speeds that made it through the intercepting channel)
- Make the MessageInterceptor test verify the data returned from the server matched what it expected.

Optional: I might also consider making the custom MessageInterceptor used in this test set some flags or something like that to indicates its methods were called, and the test can verify that those methods were called when the message was sent.

Feel free to reassign to me.

**Comment by StephenBonikowsky** [comment]
Fixed by https://github.com/dotnet/wcf/pull/1394
