### ISSUE TITLE
ERROR: Could not restore build tools correctly

### ISSUE THREAD

**Issue by gacostab** [dotnet/wcf#1255]
I have this issue running the instructions to install the wcf in Ubuntu 12.04.

juan@ubuntu:~/monobuild$ git clone https://github.com/dotnet/wcf.git
Cloning into 'wcf'...
remote: Counting objects: 16613, done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 16613 (delta 16), reused 0 (delta 0), pack-reused 16579
Receiving objects: 100% (16613/16613), 5.94 MiB | 980 KiB/s, done.
Resolving deltas: 100% (11010/11010), done.
juan@ubuntu:~/monobuild$ cd wcf
juan@ubuntu:~/monobuild/wcf$ sudo ./build.sh 
Setting up directories for build
Installing dotnet cli...
Restoring BuildTools version 1.0.25-prerelease-00424-03...
/home/juan/monobuild/wcf/init-tools.sh: line 78: /home/juan/monobuild/wcf/Tools/dotnetcli/dotnet: cannot execute binary file
ERROR: Could not restore build tools correctly. See '/home/juan/monobuild/wcf/init-tools.log' for more details.
Initializing BuildTools...
/home/juan/monobuild/wcf/init-tools.sh: line 84: /home/juan/monobuild/wcf/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00424-03/lib/init-tools.sh: No such file or directory
Done initializing tools.
./build.sh: line 106: /home/juan/monobuild/wcf/Tools/corerun: No such file or directory

tail: cannot open `/home/juan/monobuild/wcf/msbuild.log' for reading: No such file or directory
Build Exit Code = 127

Could you please give me some hints, what is the problem?

**Comment by zhenlan** [comment]
Hi @gacostab - can you please share the content of `/home/juan/monobuild/wcf/init-tools.log`? You may also like to check out [this doc](https://github.com/dotnet/core/blob/265fa210b2326eea227a62d03c78d966133565e2/Documentation/prereqs.md#ubuntu) (not merged yet) to make sure you have all prereq.

**Comment by gacostab** [comment]
Running: /home/juan/monobuild/wcf/init-tools.sh

Installing 'https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2-002733/dotnet-dev-ubuntu-x64.1.0.0-preview2-002733.tar.gz' to '/home/juan/monobuild/wcf/Tools/dotnetcli/dotnet.tar'

Running: /home/juan/monobuild/wcf/Tools/dotnetcli/dotnet restore "/home/juan/monobuild/wcf/Tools/1.0.25-prerelease-00424-03/project.json" --packages /home/juan/monobuild/wcf/packages --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json

Running: /home/juan/monobuild/wcf/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00424-03/lib/init-tools.sh /home/juan/monobuild/wcf /home/juan/monobuild/wcf/Tools/dotnetcli/dotnet /home/juan/monobuild/wcf/Tools

**Comment by gacostab** [comment]
I added the missing packages as required for Ubuntu and try again. 
However, the same issue. 

juan@ubuntu:~/monobuild/wcf$ sudo ./build.sh
Setting up directories for build
Installing dotnet cli...
Restoring BuildTools version 1.0.25-prerelease-00424-03...
/home/juan/monobuild/wcf/init-tools.sh: line 78: /home/juan/monobuild/wcf/Tools/dotnetcli/dotnet: cannot execute binary file
ERROR: Could not restore build tools correctly. See '/home/juan/monobuild/wcf/init-tools.log' for more details.
Initializing BuildTools...
/home/juan/monobuild/wcf/init-tools.sh: line 84: /home/juan/monobuild/wcf/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00424-03/lib/init-tools.sh: No such file or directory
Done initializing tools.
./build.sh: line 106: /home/juan/monobuild/wcf/Tools/corerun: No such file or directory

tail: cannot open `/home/juan/monobuild/wcf/msbuild.log' for reading: No such file or directory
Build Exit Code = 127

I will add the content of the log here too. 

Running: /home/juan/monobuild/wcf/init-tools.sh

Installing 'https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2-002733/dotnet-dev-ubuntu-x64.1.0.0-preview2-002733.tar.gz' to '/home/juan/monobuild/wcf/Tools/dotnetcli/dotnet.tar'

Running: /home/juan/monobuild/wcf/Tools/dotnetcli/dotnet restore "/home/juan/monobuild/wcf/Tools/1.0.25-prerelease-00424-03/project.json" --packages /home/juan/monobuild/wcf/packages --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json

Running: /home/juan/monobuild/wcf/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00424-03/lib/init-tools.sh /home/juan/monobuild/wcf /home/juan/monobuild/wcf/Tools/dotnetcli/dotnet /home/juan/monobuild/wcf/Tools

**Comment by roncain** [comment]
Hi @gacostab -- sorry you're encountering difficulties.  I see you are using Ubuntu 12.04, which is below the min version 14.04 .NET Core describes in its [roadmap](https://github.com/dotnet/core/blob/master/roadmap.md).  Do you have access to an Ubuntu 14.04 machine to try this?  I don't know if it is related to your issue, but we don't currently test on 12.04.

We also don't typically use sudo to run our build.sh or init-tools.sh because this causes some folders like package caches to be owned by root.  This can sometimes lead to issues attempting to update packages if you later build as non-sudo. If you are able to try this using 14.04, I'd recommend avoiding building as sudo (just do './build.sh').

Another way to help isolate whether this is related to WCF's GitHub repo might be to create a fork of https://github.com/dotnet/corefx and see if you are able to at least invoke ./init-tools.sh there. Their build instructions are [here](https://github.com/dotnet/corefx/blob/master/Documentation/building/unix-instructions.md).  Building CoreFx is not a pre-req for building WCF, but it is an alternate way to verify whether this is a machine version issue.

**Comment by roncain** [comment]
Hi @gacostab -- what would you like us to do with this issue?  Have you moved forward to Ubuntu 14.04 or 16.04?  There have also been numerous updates to the build.sh and init-tools.sh scripts in the last several months.
