### ISSUE TITLE
Ignoring Server Cert Errors

### ISSUE THREAD

**Issue by BadriL** [dotnet/wcf#1256]
We use WCF client to talk to a SOAP server that uses a self-signed cert (name does not match the URL).

```
var client = new SoapClient(binding, endpoint);
client.ClientCredentials.ServiceCertificate.Authentication.CertificateValidationMode = 
                  X509CertificateValidationMode.None;
client.ClientCredentials.ServiceCertificate.Authentication.RevocationMode = 
                 X509RevocationMode.NoCheck;
```

Despite this, I'm getting a security exception. I guess I need to disable the validation at the `HttpClient` level. I could do that using `ServiceManager` but can you please let me know how I can do the same with WCF in .NET core?

**Comment by StephenBonikowsky** [comment]
Do you mean ServiceManager under System.Activities.Presentation? If so that isn't supported in .NET core yet.
However I recently also ran into the first part of what you described, and found out that when using tcp you use ServiceCertificate.Authentication and with http you use ServiceCertificate.SslCertificateAuthentication to set the CertificateValidationMode.

The unfortunate part of this is that you don't get a build error when using the wrong property for the transport you are using.

To use SslCertificateAuthentication you also have to first instantiate it with a new X509ServiceCertificateAuthentication.

For examples see our test cases...
   for tcp: https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.cs
   for http: https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.cs

Please let us know if this fixes the issue.
Adding @mconnew who can provide additional insight into the bizzare implementation that results in this scenario.

**Comment by BadriL** [comment]
My bad. I meant `System.Net.ServicePointManager`. I'll try `ServiceCertificate.SslCertificateAuthentication` but currently the server that sends the bad certificate has been fixed now. I'm not able to test the exact scenario now. I'm closing the issue for now. Thanks for your help.

**Comment by BadriL** [comment]
I'm using the following code.

```
var client = new SoapClient(binding, endpoint);
client.ClientCredentials.ServiceCertificate.SslCertificateAuthentication = new 
                 X509ServiceCertificateAuthentication();             
client.ClientCredentials.ServiceCertificate.SslCertificateAuthentication.CertificateValidationMode = 
                 X509CertificateValidationMode.None;
client.ClientCredentials.ServiceCertificate.SslCertificateAuthentication.RevocationMode = 
                 X509RevocationMode.NoCheck;
```

My project.json is 
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002702"
    },
    "System.Diagnostics.Tools": "4.0.1-rc2-24027",
    "System.Xml.XmlSerializer": "4.0.11-rc2-24027",
    "System.Net.Security": "4.0.0-rc2-24027",
    "System.ServiceModel.Http": "4.1.0-rc2-24027",
    "System.ServiceModel.Primitives": "4.1.0-rc2-24027",
    "System.ServiceModel.Security": "4.0.1-rc2-24027",
    "System.Private.ServiceModel": "4.1.0-rc2-24027"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}
```
`X509ServiceCertificateAuthentication` does not have a public ctructor. So, does this mean I need RTM bits for the above code to work?

**Comment by MattyBoy4444** [comment]
Does this really work? I am using a Self Signed Cert and have it installed.   I get the following Exception

`System.ExecutionEngineException was unhandled
Message: An unhandled exception of type 'System.ExecutionEngineException' occurred in System.Private.CoreLib.ni.dll`

Sample Code

`var endpointAddress = new EndpointAddress(new Uri("https://localhost:59006/xyc.svc"), new DnsEndpointIdentity("service.xyz.com"), null);
XyzClient client = new XyzClient(XyzClient.EndpointConfiguration.BasicHttpBinding_IXyz, endpointAddress);
client.ClientCredentials.ServiceCertificate.SslCertificateAuthentication = new X509ServiceCertificateAuthentication();
client.ClientCredentials.ServiceCertificate.SslCertificateAuthentication.CertificateValidationMode = System.ServiceModel.Security.X509CertificateValidationMode.None;
client.ClientCredentials.ServiceCertificate.SslCertificateAuthentication.RevocationMode = System.Security.Cryptography.X509Certificates.X509RevocationMode.NoCheck;
  `

**Comment by MattyBoy4444** [comment]
Forget it.  Turns out it is a known bug in .Net Core 1.1.  
[#8148](https://github.com/dotnet/coreclr/issues/8148)

To work around I put the environment variable in

COMPlus_ReadyToRunExcludeList=System.Security.Cryptography.X509Certificates
