### ISSUE TITLE
proxy.ClientCredentials.ClientCertificate.SetCertificate() search certificate store only.

### ISSUE THREAD

**Issue by emailtowalter** [dotnet/wcf#1317]
We want to run .NET core on cloud foundry, and use 2 way SSL to call backend soap service. But SetCertificate() method seems only search the cert from certificate store which I think it is windows specific.

Is there a way to pass the certificate as a string (best option to us since we can store in certralized config server or at least file to this function? 

Thanks,

**Comment by mconnew** [comment]
I presume you found the `SetCertificate()` method from looking at our scenario tests? We use this method because it's the only way which works when writing an app for UWP. This is because you can't convert an X509Certificate2 instance into a Windows Runtime Windows.Security.Cryptography.Certificates.Certificate. As our tests get executed on all platforms, our tests use this form.  
Certificate stores are supported cross platform, but there's some caveats on some non-windows platforms. The X509Store class uses OpenSSL for the certificate store, but that doesn't always mean the transport uses the same store. For example, HttpClient is implemented on top of libcurl which often uses OpenSSL but doesn't necessarily do so. On OSX the version of libcurl which comes preinstalled uses the OSX security libraries so depending on how your certificate chain is rooted, you might have problems. This isn't a problem on most platforms, but it's something to be aware of.  
You can also set an X509Certificate2 certificate directly using the Certificate property on the X509CertificateInitiatorClientCredential object.
```csharp
    byte[] certBytes = LoadCertificateBytes();
    var factory = new ChannelFactory<IMyService>(binding, endpointAddress);
    factory.Credentials.ClientCertificate.Certificate = new X509Certificate2(certBytes);
```

**Comment by mconnew** [comment]
Closing as I believe my response addresses the issue. Feel free to re-open with more information if this doesn't address your issue.

**Comment by kotobelo** [comment]
I see this is closed, but I have a related issue with the setCertificate() method when used in an UPW app.

Somehow the following code (that uses setCertificate()) does not find my certificate:

`ClientCertificate.SetCertificate(StoreLocation.LocalMachine, StoreName.My, X509FindType.FindBySerialNumber, CertificateSerialNumber );
`

But the following code does find it:

`string CertificateSerialNumber = "EED8EE38FAB3BB5B744C360747E99ECDAB"; X509Store storeX = new X509Store(StoreLocation.LocalMachine, StoreName.My); storeX.Open(OpenFlags.ReadOnly); X509Certificate2Collection collection = storeX.Certificates; X509Certificate2Collection scollection = (X509Certificate2Collection)collection.Find(X509FindType.FindBySerialNumber, CertificateSerialNumber, false);`

**Comment by ankitsinghal0880** [comment]
@mconnew , I have a similar problem and your post definitely helped me the right direction. I have .Net core app running on Cloud Foundry in Linux cell. I do understand your code for setCertificate, Can you please share your strategy of loading the certificate on Local Machine. Technically anything local on CF is short lived unless some pre-deployment process is running to load the the cert before every deploy. Please advise your  inputs are much appreciated.

**Comment by mconnew** [comment]
@ankitsinghal0880, [here's the code](https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Common/Infrastructure/CertificateManager.cs#L79) where we save the certificate on the local machine during test setup. We check if it's already in the certificate store and if it isn't, we add it. You will need to create an instance of an X509Certificate2 from the bytes of the certificate which you obtain via some other mechanism. How we obtain the certificate in our tests wouldn't be appropriate for deploying in a real service as we fetch them over HTTP and just trust that the request isn't intercepted. This is okay for tests, but in "real life" you couldn't trust that mechanism.  
You can also directly set the X509Certificate2 in WCF. We use the SetCertificate api in our tests because of a difference when running on UWP and it works everywhere. On Linux you can just just directly set the certificate.

**Comment by mconnew** [comment]
@kotobelo, I didn't see your comment as the issue was closed. If you are still having problems, please open a new issue.

**Comment by ankitsinghal0880** [comment]
@mconnew , thanks for your response. I know how to get the certificate from the store. My struggle was mainly on how can I install and read certificate on from a container withing a cloud Foundry. I think my solution lies here: 
https://docs.cloudfoundry.org/devguide/deploy-apps/trusted-system-certificates.html

CF admin can install the certificate which could be available to instance containers. I am going to give it a try.

**Comment by mconnew** [comment]
@ankitsinghal0880, the code I linked to was how we install the certificate on the machine from .Net Core. But you need some mechanism to get the raw certificate first which isn't something I can help with as every environment will be different.
