### ISSUE TITLE
Support for Channel extensions

### ISSUE THREAD

**Issue by atanasa** [dotnet/wcf#1324]
As far as I could see, in RC2 ChannelInitializers on the ClientRuntime is not available. Are there plans to support this on .Net Core?

What I really need is a way to reuse a channel factory to create multiple channels to different endpoints but have different behaviors for each channel. I was looking at channel extensions as a way to pass input/configure the behaviors for a channel.

**Comment by mconnew** [comment]
ChannelInitializers are primarily useful to enable scenarios on the service side that you can't otherwise do. In a service, a Channel is created when a new incoming session is created and the ChannelInitializers allow you to modify the Channel object before it's used. On a client this mechanism isn't needed, although it can certainly make your code cleaner if it is available and enables doing things automatically with a custom bindingelement. Your code explicitly creates a channel by calling `ChannelFactory.CreateChannel()`. You can then modify any relevant properties on that channel before you call Open(). The difference is that instead of applying a behavior to your factory which wires up your code to make the changes, you need to arrange for your code to run to make any changes each time you call CreateChannel. There shouldn't be anything you can't do with the returned channel that you could otherwise do if the ChannelInitializers extensibility point was available.

**Comment by atanasa** [comment]
Thanks, I didn't see that the extension collection supported adding extension outside the initializer. That seems to work for my case.
