### ISSUE TITLE
Understand why ChainTrustValidator ctor was asserting for useMachineContext

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1326]
ChainTrustValidator was asserting useMachineContext was false, and this assert fired when PR #1325 allowed this code to run.

The assert has been commented out temporarily.

Investigate why the assert was there, and remove it if not needed.

**Comment by iamjasonp** [comment]
Analysis done - this assert can go away. Looking at the code and having consulted with @bartonjs, 
"useMachineContext == true" means that we will use _only_ the machine context; if "useMachineContext == false", then the chain build will use both the user context and the machine context. 

In other words, "useMachineContext" set to false is more permissive and will check more places than "useMachineContext == true". In CoreFx, a conscious decision was made to remove this API. 

Hence, any usages of the X509Chain(useMachineContext) constructor can be safely simplified to using the X509Chain default ctor in corefx. 

This work item should now be to remove the Asserts and scrub our uses of X509Chain - since we now know that it's safe to do so

**Comment by iamjasonp** [comment]
Part of this will be fixed by #1325, but I will still need to do a scrub to make sure all other usages of X509Chain are okay

**Comment by iamjasonp** [comment]
Investigation done - no further asserts were found and no bad usages were found. Closing the issue
