### ISSUE TITLE
Port SignedXml

### ISSUE THREAD

**Issue by atanasa** [dotnet/wcf#1393]
Are there any plans to port SignedXml?

**Comment by zhenlan** [comment]
Hi @atanasa, I assume what you mean is `System.Security.Cryptography.Xml.SignedXml` (instead of `System.IdentityModel.SignedXml` that is internal). If so, `System.Security.Cryptography.Xml.SignedXml` is not part WCF. Do you mind to open an issue in https://github.com/dotnet/corefx for this question?

**Comment by atanasa** [comment]
Sorry, my bad. I saw the dummy implementation in wcf and I assumed its part of it.
