### ISSUE TITLE
Add API T:System.ServiceModel.Dispatcher.IInteractiveChannelInitializer

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#1424]

**Comment by roncain** [comment]
Tasks are:
- [ ] Add implementation
- [ ] Add to contract
- [ ] Add unit tests
- [ ] Add scenario tests (may require adding add'l use of implementation throughout product)

**Comment by roncain** [comment]
PR #1602 adds to contract and adds tests.

I recommend this API be added because it is specifically client-side functionality to allow a UI to be invoked prior to opening channels.  Without this API, clients cannot do this.  All implementation code was already in place from the full framework, but prior to this PR was not being executed.

**Comment by roncain** [comment]
[Scenario enabled by this API]
The addition of these APIs permits a developer to register an IInteractiveChannelInitializer to be called whenever a channel is opened.  It is intended to be used in scenarios where it is necessary to present some UI to the user before allowing the channel to open. It is similar to IChannelInitializer but has additional support to accommodate the UI blocking the current thread..

[This blog](https://code.msdn.microsoft.com/windowsdesktop/WCF-Interactive-Channel-ec0caaa8) provides a code sample showing how one might use this to collect user credentials before allowing a channel to be opened.
