### ISSUE TITLE
Add API T:System.ServiceModel.Channels.PrivacyNoticeBindingElementImporter

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#1427]

**Comment by roncain** [comment]
Tasks are:
- [ ] Add implementation
- [ ] Add to contract
- [ ] Add unit tests
- [ ] Add scenario tests (may require adding add'l use of implementation throughout product)

**Comment by roncain** [comment]
I recommend deferring this work for now because the scope has grown quite large.
The primary scenario for it is "converts policies regarding the privacy policies in the WS-Federation specification" [blog](https://blogs.msdn.microsoft.com/carlosfigueira/2011/10/25/wcf-extensibility-policy-import-export-extensions/).  Because we have not yet implemented WS-TRUST, this scenario is not applicable yet.

Early investigation shows this brings in MetadataImporter/Exporter functionality and depends on Xml API's not yet available.

**Comment by zhenlan** [comment]
Design discussion agrees not to add this API at this point. Please go ahead and close.

**Comment by roncain** [comment]
Closing as agreed
