### ISSUE TITLE
Simply technical question XML -> .CS CODE

### ISSUE THREAD

**Issue by patsadow2** [dotnet/wcf#1520]
Hey,
Is there any good repository with knowledge about rewriting code from XML -> .CS CODE configuration endpoints/server host etc.

It would be very useful for ppl who wants to write their code in .cs
Thank u.

**Comment by roncain** [comment]
Thanks for engaging with us @patsadow2 .  To help me understand, is your question "How do I take existing WCF apps configured via app.config or web.config and instead do the same configuration in code?"

Because this .NET Core version WCF currently supports only the client-side, you won't be dealing with ServiceHosts, but you will certainly use code-based config for the client apps.  I'm not aware of the best place to go for general recommendations, but you will find our own functional tests use code-based config.  You can see examples of how we configure the server-side for our functional tests (that runs on the full framework, not .NET Core) under [IISHostedWcfService](https://github.com/dotnet/wcf/tree/master/src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts).  Also, you will see code-based config in all our [Scenario tests](https://github.com/dotnet/wcf/tree/master/src/System.Private.ServiceModel/tests/Scenarios).

Incidentally, you can also ask questions like this on our WCF [gitter](https://gitter.im/dotnet/wcf?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) and get input from other WCF developers as well as the immediate team.

**Comment by roncain** [comment]
Hi @patsadow2 -- just checking back to see if you found what you needed and whether we can resolve this issue.  Thanks.
