### ISSUE TITLE
Is wcf duplex channel support UWP background Tast?

### ISSUE THREAD

**Issue by huangjinshe** [dotnet/wcf#1577]
I mean using WCF after connected to the remote service, when the remote service pull callback still receive it in the background service in UWP. Is that possible?

**Comment by zhenlan** [comment]
Hi @huangjinshe, this is not a supported scenario. Do you mind sharing with us more details of your scenario, which will help us to consider it as a future feature?

**Comment by huangjinshe** [comment]
Sure. I'm using Duplex Channel.  If I'm changing my data, or send some info, the remote server will get the data and send to other client.

You know now all phone use notification mechanism, but currently problem is, If user not keep opening the App, WCF remote server try to send callback andl disconnect with the client. I think if wcf support receive the data(Duplex Channel callback) in background, that would be a good way, which mean user will keep all new data and message.

We could also add a background Task, that will keep connect with server if the server and client disconnect.  then that will make sure reconnect, and the callback will successfully received again.(I think this part could finish by current task, but If can't receive callback now, every time server send data to the client, the connect still will broke).

**Comment by huangjinshe** [comment]
@zhenlan, How do you think about it?  I think it's very good for interprice customer. Every time when we come back to the app, we don't need to reconnect with it.  Like New York cups using Windows phone now.  I think this will more helpful for them. :-)

**Comment by huangjinshe** [comment]
@zhenlan, Currently WCF design not too friendly for Mobile platform.

I'm using WCF duplex channel,  when mobile not open the app(mabe back to home , or maybe screen closed), if server send message to client, because mobile can't received, then it will time out, and the server connection state will turn fault.  If mobile open the mobile the communication all gone, client wont receive any callback data from server part,  the only way is mobile client need to send a new connection request(Close() too take time,  only way is Abort()) and create a new connection again. that will take time, also that will be need to execute every time if the app not run.(maybe back to phone home,  or close screen).

I think the good way is let WCF support background Task, let us keep receive the new callback from server, Or maybe you guys just redesign it, let it not fault when server send callback but client not running.

Or maybe just give me a good idea. I'm using Xamarin.Forms with WCF now.

**Comment by huangjinshe** [comment]
@zhenlan , Could you please bring more team members to discuss it together?

**Comment by zhenlan** [comment]
@mconnew can you please share your thoughts?

**Comment by mconnew** [comment]
Unfortunately UWP background tasks are too primitive to achieve this. If we were to add support for background tasks, that background task would be passed the socket instance when data arrives. We would have no way to rebuild the ChannelFactory and channel instance and all the internal state required for WCF to function from that socket. For example, the default message encoder for NetHttpBinding (used for WebSockets) is the binary message encoder. This maintains a dictionary which is dynamically built based on messages sent and received. Without that state, we wouldn't even be able to deserialize a message that was received.  
To achieve the functionality you are looking for, you could combine [Windows Push Notification Services](https://docs.microsoft.com/en-us/windows/uwp/controls-and-patterns/tiles-and-notifications-windows-push-notification-services--wns--overview) with raw notifications with WCF. When your app is being suspended, notify your service and close the channel. If the service needs to notify your app about something, you can either have it directly send the data if small enough or send a notification to indicate waiting data. Then in your notification background task create the channel factory and channel and reconnect to the server which then can call your callback with the data, or you could poll for it.

**Comment by huangjinshe** [comment]
@mconnew Hi, Thank you for you reply. Looks like you recommend me abort the Channal factory when App going to suspended, and use background task create a new channel factory, also when user open the App, abort the background channel factory, and create a new channel factory again.  Is that right?

The problem is that will cause some performance problem, I even worry that will not a best choice for battary,  Also maybe you know when first time create a Channel factory, it will take more time than next communication, then user will always need to wait for some time when Abort and create new channel factory every time.

I think the idea is good, but looks like that will take more time to write some code and debug. Is there any better idea?  like craete Channel factory in background only once, then no matter use open the App or not, the background Channel factory will always receive the data, also user could send data when open the App. I just more hope I could comunication with the same Channel factory no matter it's in background or forground.  Thank you again.

**Comment by mconnew** [comment]
Don't Abort your channel factory, call Close with the timeout that you want. If the factory can't be cleanly closed in that time, it automatically Aborts().  
Unfortunately WCF was designed over a decade before UWP was a twinkle in someone's eye so it wasn't written with the idea of being able to suspend the app and reinitialize it. The initialization is expensive, that's why a ChannelFactory exists, to share that expensive initialization state between multiple channels. It also means WCF was designed to maintain a lot of state to optimize for persistence.  
If this wasn't the case, it would have been designed such that you directly create a channel and each one initializes the entire state each time. There are some things you can do to make initialization cheaper. A client contract interface doesn't need to declare every operation the server exposes. The time to initialize a ChannelFactory is directly related to the number of methods and arguments in your contract. If your service contract has a lot of operations and large datatypes and your background task only has a subset of things it needs to do, you could make a second contract with identical namespaces etc with just the bare minimum needed to do the background task.  
The biggest cost though isn't CPU performance, it's memory usage. A channel factory is really quick to create, it just creates a lot of objects. If you are creating and disposing a lot of factories in a single process, you will stress the GC a bit (I'm talking 100's of them per second to notice it having an effect on the GC). Basically what I'm saying is don't presume you have a performance problem, measure it and see. If you do have a performance problem, then we can profile it, find the bottlenecks/hotspots and might be able to make a targeted fix. The biggest performance issue you will see shouldn't affect the local device, and that's how long it takes to establish a connection. If you use WCF asynchronously, your CPU should go to sleep waiting for the response from the server. We put a lot of effort into making sure WCF only uses async code paths whenever possible.

**Comment by mconnew** [comment]
If you find any specific performance issues with creating a ChannelFactory in a background Task, feel free to open an issue.
