### ISSUE TITLE
how to set max connections per endpoint with nettcpbinding

### ISSUE THREAD

**Issue by vincentshow** [dotnet/wcf#1603]

**Comment by hongdai** [comment]
Hi Vincent,
We do not currently support set max connections. The default is 10.

Do you think it's important for your scenario to set a different value?

**Comment by vincentshow** [comment]
Yes, in my scenario, there're more than 10+ tasks need to use wcf clients to send msg at once. And I got CommunicationException: The server did not provide a meaningful reply; this might be caused by a contract mismatch, a premature session shutdown or an internal server error. But when I send msg one by one, it worked ok.  

By the way, my nettcp binding service is duplex, and even though I got above exception in clients, the server side can also accept msg sended by those clients. 
Similarly, exception occured when the service host invoke the client's callback: The client was unable to process the callback request due to an internal error. 
And when the callback was invoked secondly in the fault tolerance module, another exception was thrown:The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state. 
However, the client whose callback is invoked by service host can also receive the data that send by the callback method.This is curious. Thanks

**Comment by mconnew** [comment]
The MaxConnections property isn't used to limit the number of outbound connections on the client side, it's used to control the number of idle connections in a standby connection pool. When you first use a WCF client proxy over NetTcp, it will establish a TCP connection with the server. Then there is a handshake that happens to negotiate which endpoint to connect to, apply any transport security and establish the session channel on the server side. When you call close on the client, a close handshake occurs on the connection. This causes the server to dispose of the session channel, clean up any instance context created, but it leaves the TCP connection open. The client then places the connection into an idle pool. If you then create a new client proxy, it checks the idle pool and reuses the TCP connection and does a fresh handshake. On the client side, the MaxConnections property simply limits how many idle connections are allowed to be in the pool. For example, if you created 15 clients then closed them all, the first 10 to close would have their TCP sockets left open and placed into the pool. The next 5 would fully close the socket. This in no way limits the number of connections a client is able to make to the server.  
It's difficult to say what the cause of your problem is, but it's not caused by the client side MaxConnections property and I suspect the issue is on the server side and not the client. You might find some hints to the underlying cause in the event logs. In Event Viewer, go to Applications and Services Logs -> Microsoft -> Windows -> Application Server-Applications and you might have an event telling you what the problem is.

**Comment by vincentshow** [comment]
Thank you for your time. But...sorry, nothing found in EventLogs. I've tried to log server side error using wcf trace log, and same errors that thrown when server side invoking clients' callback were traced indeed while no error about the clients. 
Before using asp.net core, the clients reference the same server side wcf work smoothly in .net framework 4.5. What I said above was in asp.net core whose wcf clients were generated by WCF connected service. Could this be the problem? Anyway, the net.tcp binding feature is not supported by the WCF connected service, I hacked it by using wsdualhttpbinding #728

**Comment by vincentshow** [comment]
@mconnew, one more question, could you give me some advice about how to manage the client proxy in duplex wcf service? 
Because of saving data operation in callback, I cannot close client at once after finishing  service method call. What I do is that my app create a client proxy queue, all clients used by app come from this queue, and the clients in queue never be closed unless the open time out. 
This is same with connection pool your explained above except that app cannot get client proxy when the queue is empty and max waiting time reached before existed client is disposed. Here, queue size, waiting timeout, cannot be found in client proxy configuration. Am I right?

**Comment by vincentshow** [comment]
anybody here?

**Comment by mconnew** [comment]
@vincentshow, sorry I didn't initially notice your response. The property you want to modify is TcpConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint. The connection pool settings aren't exposed on NetTcpBinding in .Net Core but are on TcpTransportBindingElement. Here's how you can modify it.
```csharp
NetTcpBinding netTcpBinding = new NetTcpBinding();
 // Set any other properties you need
BindingElements elements = netTcpBinding.CreateBindingElements();
TcpTransportBindingElement tcpTransport = elements.Find<TcpTransportBindingElement>();
tcpTransport.ConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint = 100;
CustomBinding customBinding = new CustomBinding(elements);
var factory = new DuplexChannelFactory<IMyService>(new InstanceContext(mycallback), customBinding);
```

**Comment by vincentshow** [comment]
Copy, I'll try this later.

**Comment by vincentshow** [comment]
Copy, I'll try this later.

**Comment by vincentshow** [comment]
Copy, I'll try this later.

**Comment by vincentshow** [comment]
Copy, I'll try this later.

**Comment by vincentshow** [comment]
Copy, I'll try this later.

**Comment by vincentshow** [comment]
Copy, I'll try this later.

**Comment by vincentshow** [comment]
Copy, I'll try this later.

**Comment by vincentshow** [comment]
Copy, I'll try this later.

**Comment by vincentshow** [comment]
Copy, I'll try this later.

**Comment by vincentshow** [comment]
@mconnew I can't use your code above. It seems the protocol of CustomBinding is not match to NetTcpBindings that my wcf server side specified. And...is this the connection queue question's answer? I mean  how to manage the client proxy in duplex wcf service is the problem I meet indeed. The connection queue is only my own opinion, I just want to hear your voice about it.

**Comment by mconnew** [comment]
That was example code. It sounds like you aren't using NetTcpBinding with all the default settings. Create the binding the same way you normally do then do the steps after the comment in my snippet.

**Comment by mconnew** [comment]
@vincentshow, I just realized you had another question, about the queue. There are multiple ways to solve this. One way would be when the callback happens to save some data, if you are finished with the channel after the call completes, at the end of your callback operation fire a background task to close the channel. E.g. `Task.Run(() => { ((IClientChannel)channel).Close(); });`. That Close call will block waiting for the callback to complete and then will close the channel after it has. You could also add code to remove the channel from a list or whatever other cleanup logic you need.
