### ISSUE TITLE
Test Case 'Message_With_MessageHeaders_RoundTrips' Failure

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#1745]
This test case began failing on UWP ILC runs after PR #1727 was merged.
Unfortunately UWP ILC teststack traces are not useful, the exception was...

`System.ArgumentNullException : ArgumentNull_Generic`

We would normally get more useful information from the same test case failing in the F5 runs but that same PR that caused this test case failure caused a much larger number of tests in the F5 runs to fail including this one for completely different reasons. (infrastructure related)

This needs to be investigated, in the mean-time I will add an active issue to the test case using this issue number.

**Comment by shmao** [comment]
This failure seems to me more likely caused by PR #1735. The PR added a new operation in the existing service where the this failing test sit. The new operation is marked with [XmlSerializerFormatAttribute] which would trigger UWP Toolchain doing something special for the ServiceContract. I suspected that caused the failure of this pre-existing test. If that's the case, to fix this we can put the new added test, Message_With_XmlElementMessageHeader_RoundTrip, into a new service.

**Comment by zhenlan** [comment]
We will revisit this when corefx is done with bringing up UWP to support NS2.0.
