### ISSUE TITLE
Wcf Proxy

### ISSUE THREAD

**Issue by moliveto** [dotnet/wcf#1799]
In net 4.5 we are working with proxy like this:

	<system.net>
		<defaultProxy enabled="true" useDefaultCredentials="false">
			<proxy usesystemdefault="True" proxyaddress="http://192.168.1.1:8888" bypassonlocal="True" autoDetect="False" />
			<module type="CommonLibrary.Proxy.MyProxy, CommonLibrary, Version=1.0.0.0, Culture=neutral" />
		</defaultProxy>
		<settings>
			<httpWebRequest useUnsafeHeaderParsing="true" />
			<servicePointManager expect100Continue="false" />
		</settings>
	</system.net>

but in asp.net core or test we can't found a solution like the above Could someone please help me?

I really appreciate your help

Thanks, Regards

**Comment by zhenlan** [comment]
Hi @moliveto, there are multiple things here.

> `<proxy usesystemdefault="True" proxyaddress="http://192.168.1.1:8888" bypassonlocal="True" autoDetect="False" />`

As you already noticed in #1592, we don't have something for this today, but we may be able to add APIs to wire this up in a future release.

> `<httpWebRequest useUnsafeHeaderParsing="true" />`

For WCF on .NET Core, we have changed to use HttpClient instead of HttpWebRequest and relaxed a little bit of how to add unsafe headers. Are there particular headers you are concerned with? Did you give it a try to see if it is still the problem?

> `<servicePointManager expect100Continue="false" />`

We have opened an issue about this a while back. Currently, 100-Continue is always false on Windows and true on Linux. There is no way to toggle it. Please up-vote dotnet/corefx#8673 if it is important to you.

**Comment by zhenlan** [comment]
@moliveto Please let us know (or open new issues) if you have other questions.
