### ISSUE TITLE
How do I use custom encoding (ISO-8859-1) when adding the service reference?

### ISSUE THREAD

**Issue by zenixgrace** [dotnet/wcf#1825]
Hello,

How can I use custom encoding when adding the service reference ?
I have to connect the wsdl service, but the vendor using ISO-8859-1 encoding type.

**Comment by zhenlan** [comment]
@hongdai can you see what options @zenixgrace may have here?

**Comment by hongdai** [comment]
@zenixgrace To understand better of the issue you are facing, Could you tell me you fail to create the client(reference.cs), or the client code was successfully generated, but failed to connect to the service? It will be the best if you have a repro that I can try and find out what you need to add to make it work.

Thanks,
Hong

**Comment by zenixgrace** [comment]
Hello,

I attach the log file, the  SS when adding service reference and the wsdl file.
The vendor API not open for the public access. so they have to open the spesific IP to allow access the API.

NB:
Please change the ext jpg to wsdl at index.jpg file

![1](https://cloud.githubusercontent.com/assets/17761222/24434104/a6b64c34-1457-11e7-9f3f-fd29551c64e8.jpg)
[SvcUtilParams.txt](https://github.com/dotnet/wcf/files/877482/SvcUtilParams.txt)
[WCFConnectedServiceLog.txt](https://github.com/dotnet/wcf/files/877483/WCFConnectedServiceLog.txt)

![index](https://cloud.githubusercontent.com/assets/17761222/24434305/eb963246-1458-11e7-9c57-f6b917a02ea3.jpg)

**Comment by hongdai** [comment]
@zenixgrace You can workaround the metadata download issue by using the wsdl file directly in the WCF Connected Service tool UI. However you will hit another issue that there isn't a workaround yet:

"Contract 'webservicePortType' is not compatible with .Net Core apps because it contains one or more operations with SOAP Encoding (use = 'encoded')...

Soap Encoding is not currently supported yet(see https://github.com/dotnet/wcf/issues/1549).  We will support it once we can consume  NS2.0.

**Comment by zenixgrace** [comment]
@hongdai yes, I got that error message too. I decided to make manually class for parse WS but not work. I still get the error encoding, So I decided to calling WS using HttpClient class T_T 

Hope it will implement soon. :)
