### ISSUE TITLE
Add Serializable attribute everywhere needed for 2.0

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#1829]
This attribute will be supported with 2.0, we will need to go back to many of our APIs and add this attribute back together with the dependent protected constructors that go with it.

Example: https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/src/System/ServiceModel/Security/SecurityNegotiationException.cs

**Comment by zhenlan** [comment]
We will not be able to do this until WCF is moved to build on NS2.0.

**Comment by zhenlan** [comment]
There is on-going discussion on this topic at dotnet/corefx#19119. We will hold on this item until that discussion is concluded. Current thinking is we will do this for Exception types in WCF.

**Comment by zhenlan** [comment]
Let's do this only for exception types in WCF and add tests to make sure they can be serialized/deserialzed between desktop and Core by DCS.

**Comment by zhenlan** [comment]
The PR #1900 is out but needs some touch to fix CI failures.

**Comment by karelz** [comment]
@zhenlan is it by design infrastructure issue in CI?

**Comment by karelz** [comment]
@StephenBonikowsky is the issue fixed by the PR #1900? (sorry it is not clear from the PR description)

In future, I would recommend to use [GitHub auto-closing via commit messages](https://help.github.com/articles/closing-issues-via-commit-messages/) - i.e. "Fixes #xyz" in the commit text / PR top post. It clarifies what fixed what and it is easier to spot. See examples in [CoreFX repo](https://github.com/dotnet/corefx/issues), e.g. issue 19732 (avoiding link on purpose).

**Comment by StephenBonikowsky** [comment]
Thanks @karelz I will try to remember to do that in the future. Yes this issue was fixed by PR #1900.
