### ISSUE TITLE
XML maximum depth when adding service

### ISSUE THREAD

**Issue by sergioadh** [dotnet/wcf#1834]
When trying to add a service there is an error in the form of:

Scaffolding Code ...
Error:Error: Cannot obtain Metadata from 
[Ommited] 
If this is a Windows (R) Communication Foundation service to which you have access, please check that you have enabled metadata publishing at the specified address.  For help enabling metadata publishing, please refer to the MSDN documentation at http://go.microsoft.com/fwlink/?LinkId=65455.
WS-Metadata Exchange Error
    URI: [Ommited]
Metadata contains a reference that cannot be resolved: '[Ommited]'.
There is an error in XML document (1, 1496).	
The maximum read depth (32) has been exceeded because XML data being read has more levels of nesting than is allowed by the quota. This quota may be increased by changing the MaxDepth property on the XmlDictionaryReaderQuotas object used when creating the XML reader. Line 1, position 1496.
An error occurred in the tool.

Failed to generate service reference.

Is there any way to actually configure this?

I'm using Visual Studio 2015.

**Comment by hongdai** [comment]
@sergioadh Since .Net Core not longer support traditional config file, there isn't a way to config it with the tool. 

Could you try below to see if you can workaround the issue?
1. Download the metadata(wsdl file, you can use ?singleWsdl) via a browser.
2. Browse and use the wsdl in the WCF connected service tool instead of the service URL.

Thanks,
Hong

**Comment by sergioadh** [comment]
That worked correctly. Thank you very much.
