### ISSUE TITLE
Subscribe to core-setup updates.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#1859]
Now that we are consuming Microsoft.NETCore.App we can automate ourselves to have a PR created automatically to point to us the latest packages.

**Comment by StephenBonikowsky** [comment]
This is done for the release/2.0.0 branch, it will also be completed on Master branch as a natural part of adopting buildtoolsv2.

**Comment by StephenBonikowsky** [comment]
@dagood We've made some changes that affect this. Currently we have a package reference to `Microsoft.Private.CoreFx.NETCoreApp` in [corefx.depproj](https://github.com/dotnet/wcf/blob/master/external/corefx/corefx.depproj#L26)

And in our [dependencies.props](https://github.com/dotnet/wcf/blob/master/dependencies.props#L95) we have an XmlUpdateStep for this package.

Normally I would add a `CoreSetupCurrentRef` with a corresponding...
`    <RemoteDependencyBuildInfo Include="CoreSetup">
      <BuildInfoPath>$(BaseDotNetBuildInfo)core-setup/$(CoreDependencyBranch)</BuildInfoPath>
      <CurrentRef>$(CoreSetupCurrentRef)</CurrentRef>
    </RemoteDependencyBuildInfo>`

Should I do this and remove the current...
`    <XmlUpdateStep Include="CoreFx">
      <Path>$(MSBuildThisFileFullPath)</Path>
      <ElementName>MicrosoftPrivateCoreFxNETCoreAppPackageVersion</ElementName>
      <PackageId>Microsoft.Private.CoreFx.NETCoreApp</PackageId>
    </XmlUpdateStep>`?

**Comment by dagood** [comment]
This issue should probably just be closed: WCF doesn't have a dependency on Core-Setup since we chose to assemble CoreFX and CoreCLR individually for the build. CoreCLR auto-updates should probably be set up, though.

**Comment by StephenBonikowsky** [comment]
Ok, what dependency do we have on CoreClr? I don't see that we have any.

**Comment by dagood** [comment]
Following [CoreClrPackageVersion](https://github.com/dotnet/wcf/blob/298273d7a64295613f932e2cec857d60ffcf59ae/dependencies.props#L43), you can see some [test runtime dependencies](https://github.com/dotnet/wcf/blob/6ea8adbf03455931ce37d79d8fac0690c0920de8/external/runtime/runtime.depproj#L34-L39).

...And then I also see some [Core-Setup dependencies](https://github.com/dotnet/wcf/blob/6ea8adbf03455931ce37d79d8fac0690c0920de8/external/runtime/runtime.depproj#L43-L48) for the test host, so I'm wrong about getting rid of that.

Nevermind, this issue is valid! CoreCLR should just be added too.

Your list of important bits for auto-update looks right, the `*CurrentRef` properties, `RemoteDependencyBuildInfo` items, and `XmlUpdateStep` items. We use CoreFX, so leave that one and add in Core-Setup and CoreCLR ones.

(Future reference: "fenced code blocks" (code in lines between ```) gives nice newlines in GitHub comments.)
