### ISSUE TITLE
Remove UAP 10.1 support from System.ServiceModel.* packages

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#1942]
In System.SeviceModel.Http/NetTcp/Duplex/Security (ie. except Primitives) packages, we have UAP 10.1 section for WCF 2.0.0 packages. We don't support UAP 10.1, we should remove it.

- UAP 10.1
  - System.Private.ServiceModel (>= 4.4.0-preview1-25303-02)
  - System.ServiceModel.Primitives (>= 4.4.0-preview1-25303-02)

**Comment by StephenBonikowsky** [comment]
@ericstj and @weshaggard 
I can't find where in our Repo UAP 10.1 could be getting added as a supported framework. I'm wondering if this is an unexpected buildtools issue?

**Comment by StephenBonikowsky** [comment]
This still exists with our latest release/2.0.0 packages...
System.ServiceModel.Duplex 4.4.0-preview2-25416-01

@MattGal do you have any idea how UAP 10.1 is getting pulled in as a package dependency?

**Comment by MattGal** [comment]
I don't know, this has gotten very complex in the last 5 months.  I suspect that this comes from Microsoft.Private.PackageBaseline but that's a much better question for @ericstj

**Comment by ericstj** [comment]
There isn't a new dependency here, you just have a dependency group with fewer dependencies that is autogenerated for UAP10.1.

We've always done this for frameworks that have "inbox" assemblies.  NetStandard2.0, NetCoreApp2.0, and UAP10.1 all represent themselves with 'inbox' assemblies now to reduce dependencies.

It doesn't hurt anything to have the dependency group there, but you can remove it if you want.  We don't have a hook to selectively disable inbox framework information.  As @mattgal points out this comes as part of the baseline.  

Here's what I did in CoreFx's release/2.0.0 branch to rip out all the UAP10.1 stuff, temporarily from the release branches: https://github.com/dotnet/corefx/pull/19568/files
The `Dependency` portion is the part that is relevant to this discussion since WCF doesn't have any libraries specifically targeting UAP10.1.  You'd be safe to pick that whole change though.

**Comment by StephenBonikowsky** [comment]
Thanks @ericstj  !
