### ISSUE TITLE
Deserialization error for first streamed web service request with a Global.asax file added

### ISSUE THREAD

**Issue by mol** [dotnet/wcf#2189]
Adding an (even empty) Global.asax file to a web service that is streaming and using the netHttpBinding (maybe others too), causes **the first request** after service start throw a deserialization related exception - every time. Subsequent requests work fine.

It's been reported to StackOverflow a few times without details and without actual solutions, but I've managed to narrow it down to the Global.asax file. If it exists, even empty, the first request fails. If it's deleted, the first request does not fail.

It fails both when hosted in IIS Express and IIS proper.

I've modified the WCF SelfHost sample to run a web service that reproduces the issue. Just clone, set both projects to start and run:
https://github.com/mol/FailingWCFFirstRequest

**Comment by mol** [comment]
Seems like it's related to this:
https://stackoverflow.com/questions/4412124/how-can-a-newly-added-global-asax-file-make-a-mess-of-my-wcf-service

Setting aspNetCompatibilityEnabled to false in the Web.config and the first request works.

**Comment by zhenlan** [comment]
@mol thanks for reporting the issue. This is an issue regarding WCF in .NET Framework. I will forward this for further investigation, but if your are interested to get an update or in case any further information is needed, I would recommend you to send this through https://connect.microsoft.com/VisualStudio/Feedback for anything related to full .NET Framework.

**Comment by jcondex** [comment]
Hi,

The reason why this happens is because when Global.asax is added, the Session_Start event handler gets hooked up.  If you remove the Session_Start handler, the issue will not reproduce anymore.  You can also get an instance of Session.SessionID which also mitigates the flushing issues:

void Session_Start(object sender, EventArgs e)
{
    // Code that runs when a new session is started
    string sessionId = Session.SessionID;
}

Having said that, the issue appears to be in ASP.NET and we have looped in the appropriate owners for investigation.  The flush happens because WCF sends the SOAP header first and flushes then serializes the body to the output stream flushing each item if it’s a collection for example, then closing the SOAP message and flush again. SessionStateModule knows the response has had flush called, so this means the application had already written a response to the client.
