### ISSUE TITLE
Missing ClientBase<TChannel>.Close()

### ISSUE THREAD

**Issue by EPinci** [dotnet/wcf#2282]
Hello,

Looks like the method ClientBase<TChannel>.Close() is no longer there.
How do I close a client?

Thank you.

**Comment by zhenlan** [comment]
Hi @EPinci, you can call `Dispose()` on it
https://github.com/dotnet/wcf/blob/0066c64bd8536b732309ee1a9fc4037c02266e4c/src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs#L142

**Comment by EPinci** [comment]
Understood, thank you.

Can I ask you to comment on [this article](http://geekswithblogs.net/DavidBarrett/archive/2007/11/22/117058.aspx): this is widely reported around and does it still apply?

Thank you.

**Comment by ericstj** [comment]
You might consider bringing this back in the references.  We brought back all `Close()` members in CoreFx and I see you kept the Close method in the implementation.  The Close/Dispose confusion didn't outweigh the sheer number of hits on the missing Close methods.

You might also consider looking at a diff for other types that were subsetted "on principle".  We've backed off most of those principles since 2.0.  /cc @terrajobst @danmosemsft

**Comment by StephenBonikowsky** [comment]
@ericstj I opened #3101 to do this work.

**Comment by ericstj** [comment]
Sorry I missed that this one was actually fixed.  Thanks for opening the new issue.
