### ISSUE TITLE
Support proxy servers for nuget download task

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#23]
From PR #22. Once a fix for https://github.com/dotnet/corefx/issues/963 is in, we should pull in a similar change. Today, nuget package restore would fail when behind a corporate firewall. 

Thanks @PatrickMcDonald for the heads up!

**Comment by shamusfuller** [comment]
The WebClient implementation in PR #22 will fail throwing "Message=The remote server returned an error: (407) Proxy Authentication Required." in some firewall environments where a 'network logon' is used instead of Active Directory to authenticate to the proxy server. If I remember correctly the Active Directory credentials show up as default credentials which does not work. The proxy credentials had to be set in code explicitly.

The problem seemed to go away by using HttpClient instead of WebClient. I no longer have access to such an environment so I can not verify the behavior, but thought you should be aware of it.

**Comment by iamjasonp** [comment]
@shamusfuller - whoa, hadn't even thought of trying that scenario. What happens when HttpClient is used and how does one specify creds in that case? 

Thanks for the heads up!

**Comment by roncain** [comment]
This issue was fixed by PR https://github.com/dotnet/wcf/pull/65. That PR copied the fix from the CoreFx repo after it was fixed by PR https://github.com/dotnet/corefx/pull/1798
