### ISSUE TITLE
Terrifying Developer Experience using WCF on UWP!

### ISSUE THREAD

**Issue by Joebeazelman** [dotnet/wcf#2381]
Developing on UWP has been a living nightmare.  Fortunately, my customers are more patient than I am.  As an addendum to my last post, I discovered a work around to to the code generation problem.  It is detailed in this obscure article:

https://medium.com/@narinkaew/using-wcf-soap-services-in-net-core-fb13180c4eda

I initially thought it couldn't be that simple, but I gave it a try and it worked!  The code customization is still limited and there's still the weird naming issues, but I can live with it.  Although, this isn't technically a bug, it is worse.  Bugs are obvious, but this slowly leads you down to hell in a virtual hand basket.  

First, there's the bad UI.  On the UWP project, you three confusing options for adding a reference, on dotnet core and .Net standard you get two:

- Add Service Reference  (UWP .NET Standard)
   Generates a useless client on UWP, but a useable one on .NET Standard. 
- Add Connected Service  (UWP, .NET Core)
   A meaningless option with nothing useful in UWP.  A web service is connect, isn't it? Well it appears to be on .NET Core, but only when you know the secret of installing a special add-in that generates something half usable. 
- Add Reference  (UWP, .NET Standard)
   The most sensible and familiar one that lets you add a reference to another project or assembly. 

Who designed this dreadful interface?  It reminds me of VISTA with 6 options for turning off your computer, three buttons for navigating your Windows phone, and three buttons on a Windows mouse.  I don't want a thousand choices, I just want the best one!  Ever wondered how Apple rose from the ashes and ate your lunch?

Second, the documentation for Microsoft products have always left a lot to be desired, but recently it is beyond atrocious!  There are thousands if not millions of documentation, videos and source code and you have to be a detective to find them.  Microsoft's search is completely useless, so you have to use their competitor's search site, Google.  Once you find the info, you then have to find out if it is relevant, current and accurate.  But you won't know until you've read pages of drawn out introductory texts explaining how they will explain what they will be explaining, along with the obligatory dead-end and broken links. 

When you do discover useful information it is usually on some whiz kid's blog, stackoverflow, github, or youtube, anywhere but Microsoft.com! I even had a Microsoft Engineer tell me to file a bug with the suggestion "hub" without providing me with a link.  Why was I sent to a suggestion hub when I have a bug to file?  Doesn't Microsoft have a proper defect tracking site?  What's going on here?  Maybe Microsoft could find more talent if they stopped giving out those stupid whiteboard interviews. 

You guys are a multi-billion dollar company with more than enough money to buy an entire country!  I would hold my tongue if Microsoft was a startup, but you've been around for decades now.  Before, Microsoft was a monopoly operating on mediocrity, today it's just plain mediocrity.

**Comment by mlacouture** [comment]
Hi @Joebeazelman 

I can understand your frustration.  Visual Studio is a very rich environment that supports developing code for different technologies (C#, C++, Web, .Net Framework, .Net Core Framework to name some) and also provides the tools to make it easier to work with the different project templates designed for these technologies.

As you could imagine, we are busy working on the new tools to support newer technologies and we use newer technologies to develop these tools as well.  The WCF Web Service Reference connected service provider is designed for .Net Core projects using the relatively new VS Connected Services framework.  

We could spend time updating the old tools to have a unified experience or we could use this time to develop the tools based on newer technologies to support new project types.  Of course, ideally we would do both (and we actually keep fixing any issues in the older tools) but we set our priorities so that we can enable customers to adopt these newer technologies faster.

It seems you have been active in using the [WCF Web Service Reference](https://github.com/dotnet/wcf/blob/master/Documentation/WCF-Web-Service-Reference-guide.md) tool and we are glad you do.  Please keep using it and let us know if you hit any issues, and thank you for helping us improve this tool.

Miguel Lacouture
[MSFT]

**Comment by Joebeazelman** [comment]
You guys need to focus on getting ,NET consolidated and working, not reinventing the wheel  The WCF Web Service Reference worked and is  part of visual studio for Windows, not the Framework.  At most, it needed some tweaks to its code generation, not an entire rewrite.  There's no reason why it has to use the same code base as its target.  This is a lot of unnecessary work and duplication of efforts.

**Comment by wsnell** [comment]
I don't understand why the new connect web service reference tool generates code that is completely different than the add web service reference tool. I don't want async calls I want to also support synchronous calls one after the other in my own thread.  How can I do that now in .NET Core?
I don't want an async interface...  How do I do this and get the code generation to look just like it did in full .NET framework?

Thanks
-Wes

**Comment by mlacouture** [comment]
@wsnell, thank you for your feedback.  Although the WCF Web Reference connected service (WC CS) provider works similarly to the Add Service Reference tool, these tools have some differences, the main being they are designed for different frameworks; the former is designed for .Net Core Framework, while the latter for the desktop .Net Framework.  

The WC CS tool, targeting a more modern framework, takes advantage of newer language features and favors .Net Core clients which usually present some sort of UI, so need to perform background operations (such as communicating with a web service) in background threads.

You can always write synchronous code for methods that are designed to run asynchronously, for instance, the async call `var a = await client.GeValueAsync(10);` can be changed to `var a = client.GetValueAsync(10).Result;` so it can run synchronously.

I hope this helps,
Miguel Lacouture
