### ISSUE TITLE
WCF with Websockets on .NET Core 2.0

### ISSUE THREAD

**Issue by wsnell** [dotnet/wcf#2386]
I'm trying to find out how/if WCF with Websockets on .NET Core 2.0 is supported.
1.  I see release notes from your team there is support, but I see zero documentation or details or examples.  
2. What is available and how does it work? 
3. Can I use the WebSocket as a duplex connection?  I would like to be able to use WCF and call into the websocket with commands as well for async results.
4. IN general in .NET Core 2.0 (on windows 7 and in Linux), I really want WebSocket support in general as well and fully functional without 3rd party support.  This is a huge protocol and needs to be fully contained in the .NET Core or .NET Standard 2.0 specs (note I can't live with the needs win8+ requirement).
5. Can you guys provide docs and example code too?
Need ASAP...
Thanks
-wes

**Comment by mconnew** [comment]
1. The documentation/usage is the same for .Net core as it is on the full framework. A good starting point is [this](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/wcf-and-websockets) documentation for the full framework. We also have some [scenario tests here](https://github.com/dotnet/wcf/blob/2c421e6e1af634938071cfc07204e4c9d68ca749/src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/WebSocketTests.4.1.0.cs) which are good samples on how to use WebSockets in .Net Core.
2. I'm not sure what you're asking here? We have some limitations with authenticating server certificates due to limitations in the ClientWebSocket api. Other than that, we don't have a lot of differences compared to the full framework.
3. Yes, WebSocket's does support duplex. In the scenario tests I linked to earlier, there's a test called WebSocket_Http_WSTransportUsageDefault_DuplexCallback_GuidRoundtrip which uses a duplex contract. 
4. WCF just uses the WebSockets implementation on .Net Core. When that gets support for Win7, WCF will too without needing to do anything. You can track the progress of that issue in dotnet/corefx#9503
5. I hope the links I've already supplied are sufficient. If there's something specific you need, please say.
