### ISSUE TITLE
.NET Core 2.0 WCF has horrible documentation

### ISSUE THREAD

**Issue by wsnell** [dotnet/wcf#2405]
.NET Core 2.0 WCF has horrible documentation, almost none.  So I don't know what exactly is supported, what is not and running sample code that I can refer too.  I like WCF, but this is sorely needed.
Thanks
-Wes

**Comment by zhenlan** [comment]
Hi @wsnell, WCF .NET Core shares the same API surface of WCF .NET Framework except it's a subset because WCF .NET Core supports client scenarios only. Since WCF on .NET Core needs to talk with WCF service on .NET Framework, WCF .NET Core maintained as much compatibility as possible with .NET Framework. Therefore, all existing client-related WCF documentation applies to WCF on .NET Core too.

You can find all the APIs that are supported by WCF on .NET Core from docs.microsoft.com. Here is an example. Note that, you can switch between different frameworks and versions through the dropdown list at the upper-right corner of the page.
https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.basichttpsbinding?view=netcore-2.0

You can also find the [release notes](https://github.com/dotnet/wcf/releases) we had for each WCF .NET Core release where you can find the document of supported features by each release, for example, this is a document for 2.0 release.
https://github.com/dotnet/wcf/blob/master/release-notes/SupportedFeatures-v2.0.0.md

Hope this helps!

**Comment by masoudtahmasebi93** [comment]
Hi , sorry is the documentation for WCF in .Net Core 2 available anywhere? Cause I just can't find anything anywhere
