### ISSUE TITLE
How to call a connected WCF service in Visual Studio 2017 community version in a Windows application?

### ISSUE THREAD

**Issue by Kirin2017** [dotnet/wcf#2412]
Hello Team,

Please note that I have consumed a wsdl as a service reference [ServiceReference1] in a Windows application Form in Visual Studido 2017 community edition. I wanted to make use of some methods provided by the web service.

Please can you inform me how I can do it as I cannot even call the soap client via ServiceReference1 namespace? 

Please advise.

**Comment by mlacouture** [comment]
Hi @Kirin2017 
Just to make sure we understand your problem, what do you mean by 'cannot call the soap client'? are you getting an network error or is it that your application does not compile? please provide specific details about your problem.

Also, did you create your windows application project from one of the .Net Core templates or from one of the classic .Net Framework template? did you use the WCF Web Service Reference connected service provider to add the web service reference or the Add Service Reference tool? I'm asking because this forum is about WCF on .Net Core.  If you are on .Net Framework we may still be able to help depending on the problem ...

thank you!
Miguel Lacouture

**Comment by mlacouture** [comment]
@Kirin2017, please let us know if you still need help with this. closing for now.
