### ISSUE TITLE
Consider making package versions and assembly versions be the same.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#2485]
Lets discuss, this could simplify our versioning story and make for less confusion and mistakes.

**Comment by Tragedian** [comment]
It seems obvious to have them match. Are there any reasons _not_ to keep them in sync?

**Comment by zhenlan** [comment]
Currently, v4.5.0 S.P.SM package has S.P.SM assembly version 4.1.4.0, we would like to change the assembly version to 4.5.0.0. This will make future debugging/investigation to find the right package much easier.

@weshaggard, do you see problems of doing this?

**Comment by weshaggard** [comment]
There are a couple reasons we stopped tying them together:
 
1. In a lot of our packages we have multiple assemblies for different target frameworks which have different assembly versions so which one would you pick in that case.
2. There are a number of scenarios were we want to keep the assembly version fixed but we have to still bump the package version to ship an update. Think .NET Framework where the assembly versions are fixed.
3. Another reason was for marketing reasons at .NET Core 1.1 time we aligned all the package versions across the product to be the same and didn't want to force all the assembly versions to jump around to match, in some cases we couldn't make them match because it would lower the version. 

So for S.P.SM you could make them match today if you wanted to but I suspect things will happen over time to make them not be in lock step so I'm not sure it is actually worth changing it now.

**Comment by Tragedian** [comment]
@weshaggard  What's the details on the scenario where you want to push an update but not bump the assembly version to match? Is there something looking for specific assembly versions?

**Comment by weshaggard** [comment]
A lot of our packages support multiple frameworks and some of those frameworks have versions of a library fixed inbox (ex .NET Framework) so we have a fixed assembly version we must provide for our reference assembly in the package so that references to that package will run correctly when running on .NET Framework. If we bumped the version then we would have to handle version unification in some way (i.e. binding redirects), which complicates things. In such cases we don't bump the version of the reference assembly until we change the API surface at which point we bump the minor version. However in that time we might ship the package many times to provide fixes in the .NET Core implementation library that lives in the package.

**Comment by zhenlan** [comment]
Thanks for the input @weshaggard. This is helpful.

I agree we should not change the assembly versions blindly across the board. For the cases, where the assembly version is not supposed to be changed we will leave it as is. This should be only about the case where we would need to update the assembly version anyway. Since for every release, we will have to bump up the package version, we will need to decide if an assembly version update is necessary for every release. It is possible, assembly version falls behind the package version for some releases in the future, but if we decide to update the assembly version too, we will update the assembly version to match the package version.

**Comment by zhenlan** [comment]
Resolved by https://github.com/dotnet/wcf/pull/2518
