### ISSUE TITLE
Adding web service reference in Visual Studio

### ISSUE THREAD

**Issue by deb0011** [dotnet/wcf#2594]
While trying to 'Add a Service Reference' to an asmx web service(Visual Studio Team Services endpoint for my project) in Visual Studio 2012, I'm getting the error:
"The content type text/html; charset=utf-8 of the response message does not match the content type of the binding (application/soap+xml; charset=utf-8)"

I tried a Get request with the 'RESTED' chrome extension which worked fine (returned the WSDL for the web service). Fiddler is also giving me a 200 status code. But I'm getting the above error while trying to connect from Visual Studio.

The service is hosted by Microsoft so no changes possible there. What are the list of things that could be going wrong at the client side?

Searching the internets did not fix my issue. Either the situations did not apply or the solutions mentioned did not work for me.

P.S. I'm a novice in WCF services so any obvious explanations would not be out of place.

**Comment by MSGaryWang** [comment]
Here is for .Net Core version WCF library, please use https://www.visualstudio.com/vs/support for assisted support at other version.  Since you can download that WSDL file and you might try using that WSDL file instead of original url or you might try append "?wsdl" to the end of the original uri if there was not.
