### ISSUE TITLE
Generated return types unnecessarily wrapped in *Response1 class

### ISSUE THREAD

**Issue by timmkrause** [dotnet/wcf#2670]
I am migrating from Service Reference to Connected Service Reference and I am facing a breaking change (beside forced `*Async()` methods).

What is the purpose of the `*Response1` wrapper around the actual `*Response`?
Is this behavior configurable?

**Comment by mlacouture** [comment]
Hi @timmkrause 

Thank you for using the WCF Web Service Reference connected service. 

In order to answer your question we are going to need more details about your service as the generated code is highly dependent on the service metadata.  Is the service you are using a public one that you can share the URL? if not, are you able to download the WSDL and share it with us? if none of these options are possible can you please share some details about the generated code like the generated methods/types you are asking about?

thank you!
Miguel Lacouture

**Comment by Lxiamail** [comment]
@mconnew has some additional context

**Comment by mconnew** [comment]
@timmkrause, I'm going to make some assumptions so please let me know if I'm wrong. You said about the issue of being forced to use `*Async()`, so I presume you were using a synchronous contract before. As you have gone from sync to async, there's some differences in how some parameters are handled. I presume your synchronous operation had either `out` or `ref` parameters, eg `void DoWork(out string)`, this won't work with Tasks.  
The reason is that they are passed by reference and when you await a `Task` which has gone asynchronous, the call stack unwinds and when the `Task` completes, the next statement is executed on a new call stack. This means any stack references passed in would now be invalid and you would loose the value being returned `out` by the parameter, or your variable passed in by `ref` wouldn't be updated. To work around this, in this situation a request and/or response wrapper are created. A `ref` parameter will exist in the request wrapper and the response wrapper. An `out` parameter will only exist in the response wrapper.

**Comment by timmkrause** [comment]
The `*Async()` stuff was just a side node. Because I have used the classic Service Reference before there were only synchronous methods. When switching to the Connected Service Reference there were only `async` methods and I saw in a different issue here that synchronous methods are not supported atm. So I refactored the corresponding code paths to `async`. All is fine with this.

What I am actually concerned about is the second thing in my post. The migration was easy and it is working again. I just find it ugly and want to understand the purpose around this `Response1` wrapper thing.

```
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class SomethingClient : System.ServiceModel.ClientBase<Some.Namespace.Something>, Some.Namespace.Something
    {
        
        public SomethingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Some.Namespace.SomeMethodResponse1> Some.Namespace.Something.SomeMethodAsync(Some.Namespace.SomeMethodRequest request)
        {
            return base.Channel.SomeMethodAsync(request);
        }
```

The input `SomeMethodRequest` is fine. But the output `SomeMethodResponse1` is the artifact I don't understand.
Is have to use `SomeMethodAsync()` like this:

```
SomeMethodResponse1 response = await client.SomeMethodAsync(request);
SomeMethodResponse realResponse = response.Response;
```

1. I find this `1` suffix pretty ugly.
2. What is the purpose of additionally wrapping the response? With the "old" Service Reference (not Connected Service Reference) it was just:

```
SomeMethodResponse response = await client.SomeMethodAsync(request);
// Go ahead with the actual response...
```

Unfortunately I cannot currently verify if this was a real change in the WSDL I used for the generation because it is currently in development and not working atm (and the Connected Service Reference does not create a copy of it for reference ;-)).
Or if this was introduced when switching to the Connected Service Reference... I would suspect it was caused by the Connected Service Reference.

**Comment by mconnew** [comment]
Do you have any `ref` or `out` parameters in your operation? Can you provide the corresponding method definition from the server side contract interface (presuming it's WCF?).

**Comment by timmkrause** [comment]
No `ref` or `out` parameters were generated.

The WSDL from the SAP service holds several types which follow the following convention:

`<xsd:element` name="Z_SAP_SOME_THINGResponse">`

Is this the actual "problem" why an additional `*Response1` is generated around this response type? Because of a naming clash?
As I said, this was not the case with the classic Service Reference. The type was generated with the name from the WSDL `Z_SAP_SOME_THINGResponse`.

**Comment by mlacouture** [comment]
@timmkrause, is it possible for you to provide us with the service WSDL docs? or the service URL if public?
thanks,

**Comment by mlacouture** [comment]
Hi @timmkrause!
any chance you can provide the info I requested? thanks,

**Comment by timmkrause** [comment]
I am very sorry to tell you that I won't find the time for that anymore as I am working on a different project already. I would have to thin out and anonymize the WSDL and I didnt' have the time for that. You can close the issue if you like...

All the best for your future releases.

**Comment by mlacouture** [comment]
Thank you @timmkrause and let us know if you need our support in the future.

**Comment by csmith-o2** [comment]
I realize this discussion is from 2 years ago, but I have the same question and I'm not having much luck finding an answer. At least the API I'm using is public: http://api.exigo.com/3.0/ or http://api.exigo.com/3.0/?wsdl

When I run dotnet-svcutil I get generated classes with the Response1 suffix. For example, `await client.AuthenticateUserAsync(...)` returns an instance of `AuthenticateUserResponse1` with only one property: `AuthenticateUserResponse Response`.

Can you tell me if this wrapping is unavoidable based on the way this WSDL is structured?

**Comment by Montago** [comment]
I'd like to know if this was ever fixed or resolved ?
