### ISSUE TITLE
System.ServiceModel.dll in System.ServiceModel.Primitives package has wrong referenced assembly versions

### ISSUE THREAD

**Issue by Lxiamail** [dotnet/wcf#2748]
In System.ServiceModel.Primitives package, under both ref and lib, open system.servicemodel.dll in ildasm, you can see that the following references in its manifest. The referenced assembly versions are all 0.0.0.0. We expect the referenced assembly versions should exactly match with corresponding façade assembly versions. Looks like this is a regression from v2.0 release. Also, we should evaluate if system.servicemodel.dll is needed under ref folder. If not needed, will moving it will cause breaking change?
.assembly extern System.Runtime
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 0:0:0:0
}
.assembly extern System.ServiceModel.Primitives
{
  .publickeytoken = (CC 7B 13 FF CD 2D DD 51 )                         // .{...-.Q
  .ver 0:0:0:0
}
.assembly extern System.ServiceModel.Http
{
  .publickeytoken = (CC 7B 13 FF CD 2D DD 51 )                         // .{...-.Q
  .ver 0:0:0:0
}
.assembly extern System.ServiceModel.Duplex
{
  .publickeytoken = (CC 7B 13 FF CD 2D DD 51 )                         // .{...-.Q
  .ver 0:0:0:0
}
.assembly extern System.ServiceModel.NetTcp
{
  .publickeytoken = (CC 7B 13 FF CD 2D DD 51 )                         // .{...-.Q
  .ver 0:0:0:0
}
.assembly extern System.ServiceModel.Security
{
  .publickeytoken = (CC 7B 13 FF CD 2D DD 51 )                         // .{...-.Q
  .ver 0:0:0:0
}
.assembly extern System.ServiceModel.Syndication
{
  .publickeytoken = (CC 7B 13 FF CD 2D DD 51 )                         // .{...-.Q
  .ver 0:0:0:0
}

**Comment by weshaggard** [comment]
We need this shim in the ref folder otherwise folks cannot consume a library with a reference to System.ServiceModel.

As for the reference versions of `0.0.0.0` that is also by design because we don't have a way to put exact versions of most of those dependencies because we want the shim to work on different versions of the platform. To avoid this version mismatch we set the reference to `0.0.0.0` and let msbuild/compiler unify the version to whatever is in the platform.

**Comment by StephenBonikowsky** [comment]
Thanks for the details @weshaggard
