### ISSUE TITLE
ChannelBase<> does not have Invoke() method

### ISSUE THREAD

**Issue by TillAlex** [dotnet/wcf#2935]
Currently ChannelBase<> only has BeginInvoke() and EndInvoke() methods. How to invoke sync Operations when using auto-generated proxies is not possible?

**Comment by Lxiamail** [comment]
@TillAlex adding the API will break .NET standard. Can you articulate which scenario you are trying to achieve?

**Comment by TillAlex** [comment]
@Lxiamail We are implementing a .NET standard WCF client, but can not use dynamic proxy generation (Xamarin.iOS does not support it). Therefore, we implement it manually using ChannelBase<>. If we target Xamarin.iOS this works as System.ServiceModel from Xamarin.iOS implements not only BeginInvoke and EndInvoke, but also Invoke. 

How to implement a non dynamic proxy with synchronous OperationContracts in .NET standard, when there is no Invoke() method?

**Comment by Lxiamail** [comment]
@TillAlex Looks like you already have current code working on Xamarin.iOS, but doesn't work on .NET standard. Can you provide a sample of your current working code so that we understand your concrete issue?

**Comment by TillAlex** [comment]
Attached you find an example of a service client working in Xamarin.iOS, but not in .NET standard. 

Problem is the ChannelBase<>.Invoke() method which exists in Xamarin.iOS, but does not in .NET standard. However, the async versions of Invoke(BeginInvoke() and EndInvoke()) do exist in Xamarin.iOS and .NET standard. 

Is there any reason why invoking OperationContracts asynchroniously is allowed, but synchroniously is not?

**Comment by Lxiamail** [comment]
@TillAlex Thank you for providing the repro. This is a feature request, we can't add ChannelBase<>.Invoke() since it doesn't exist in .NET Framework either. Can you try to use BeginInvoke() and EndInvoke() instead? You can do something similar to this:
```csharp
            public byte[] GetImageData(string id)
            {
                object[] args = {id};
                var iar = BeginInvoke("GetImageData", args, null, null);
                return (byte[])EndInvoke("GetImageData", Array.Empty<object>(), iar);
            }
```

**Comment by ignacioinnovo** [comment]
Hi there! I have the same situation here and I cannot run the app in iOS because in depends, entirely on the WCF service.

Thank you for your time!

**Comment by Lxiamail** [comment]
@mconnew Can you look into if there is any work around?

**Comment by StephenBonikowsky** [comment]
@mconnew Could you provide some of the context for this issue, clarify what needs to be done to resolve it?

**Comment by mconnew** [comment]
The Invoke method (which is only available on mono) exists to enable a different style of generated client. This is because the proxy implementation on mono uses transparent proxies which aren't available on iOS. Xamarin on iOS is going to have an IL interpreter which is [currently in preview release](https://devblogs.microsoft.com/xamarin/introducing-xamarin-ios-interpreter/). The .NET Core implementation of WCF client doesn't use transparent proxies, instead with use Ref Emit to create a class at runtime which implements the service interface (we use [DispatchProxy](https://github.com/dotnet/corefx/blob/e23119d577e644d2c2a25419c88c1181681358e0/src/System.Reflection.DispatchProxy/src/System/Reflection/DispatchProxy.cs) if you're interested. Rather than introduce a new api which doesn't exist on .NET Framework, and add into that the other problems on Xamarin such as not supporting Tasks, the better option long term is to use this implementation of WCF on Xamarin. Our generated proxy will run via the IL interpreter and there will be feature parity across all platforms.

**Comment by StephenBonikowsky** [comment]
The correct long-term solution is to use the WCF [DispatchProxy](https://github.com/dotnet/corefx/blob/e23119d577e644d2c2a25419c88c1181681358e0/src/System.Reflection.DispatchProxy/src/System/Reflection/DispatchProxy.cs) together with the Xamarin IL interpreter.

**Comment by FlavioGoncalves-Cayas** [comment]
What does the actual solution look like now? I got the same problem NRE as @TillAlex when calling EndInvoke.
I also cannot find any information on how to use DispatchProxy in this context.
