### ISSUE TITLE
error when add wcf to .net core project

### ISSUE THREAD

**Issue by MajidDehnamaki** [dotnet/wcf#3127]
when I add a wcf service to my project I see this error

> The project does not target a supported .Net Core or a .Net Framework version. The supported framework versions are as follows: netcoreapp[1.0-2.0], netstandard[1.3-2.0] and net4.5 and above.

**Comment by mlacouture** [comment]
Hi @MajidDehnamaki!
It seems you are using an old version of the Visual Studio while your project targets a newer version of the .NET Core/Standard platform.  What version of Visual Studio are you using? This issue was fixed in Visual Studio 2017 v15.7. 
Please let us know if you need any further help,

**Comment by MajidDehnamaki** [comment]
@mlacouture 
i have visual studio 2017 v15.5
should i update to 15.7?

**Comment by mlacouture** [comment]
Yes, even better if you can update to [Visual Studio 2017 15.8](https://blogs.msdn.microsoft.com/visualstudio/2018/08/14/visual-studio-2017-version-15-8/)
