### ISSUE TITLE
Generated endpoint configuration can contain syntax errors

### ISSUE THREAD

**Issue by JBastiaan** [dotnet/wcf#3166]
Depending on the name of the consumed endpoint the endpointconfig enum can contain syntax errors.

Generated reference file:
![image](https://user-images.githubusercontent.com/6311598/45341966-c2a63c00-b59c-11e8-87db-bf3e9c43191e.png)

Consumed endpoint:
![image](https://user-images.githubusercontent.com/6311598/45341994-d9e52980-b59c-11e8-9efb-07eeee8f9a75.png)

**Comment by mlacouture** [comment]
Hi @JBastiaan 

This is a known issue for which we have a fix but it will be available with Visual Studio 2017 v16.  In the meantime, you can use the [dotnet-svcutil tool](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide) which contains the fix for this issue.

hope this helps,
Miguel
