### ISSUE TITLE
Supporting of PipeBinding

### ISSUE THREAD

**Issue by Alexcei88** [dotnet/wcf#3180]
I did not find any information about supporting of PipeBinding. Is PipeBinding supported by the client libraries?

Thank you.

**Comment by Lxiamail** [comment]
@Alexcei88 It's not supported. What's the scenario that you need NamedPipeBinding. Since NamedPipeBinding needs to have both client and server on the same machine. It only can work on Windows today. WCF Core client targets cross-platform. With that  NamedPipeBinding doesn't fit in well until WCF Server is supported on WCF Core.

**Comment by Alexcei88** [comment]
@Lxiamail, thank you for answer!
I am porting the exist project from .Net Framework to .NetCore. I have a service published by the pipe. And I considered to connect to the service from my ported .NetCore code, but I could not do, my new code was not compiled.  So I decide to clarify about the support.

So, If the support of Pipe is not existed, I change a transport from pipe to tcp and it is good for me.

**Comment by Lxiamail** [comment]
@Alexcei88 Thanks for sharing your usage context. Yes, using tcp instead is good alternate.
