### ISSUE TITLE
Sending a stream of data from UWP to WCF

### ISSUE THREAD

**Issue by xiedongweo** [dotnet/wcf#3220]
I created a WCF service, which exposes the following [OperationContract]:
`Task<bool> SendStream(Stream stream);`

If I connect to this service from a WPF app, I can use the method as expected. However I want to send the data from a UWP app, and when trying to do so I find that the UWP client connection expects me to send a byte[] and not a Stream.

Why will UWP not recognise Stream, and how can I get around it? For reference I am intending to send files that could be many hundreds of MB in size, hence the reason I want to stream them.

**Comment by Lxiamail** [comment]
@xiedongweo Can you share a repro project and the WCF service WSDL file?

**Comment by xiedongweo** [comment]
> @xiedongweo Can you share a repro project and the WCF service WSDL file?

Please download my code sample from this link: [https://1drv.ms/u/s!AoI4pKdRYn8KnHdIoRuyX2xoajkQ]

**Comment by xiedongweo** [comment]
> @xiedongweo Can you share a repro project and the WCF service WSDL file?

Any update?

**Comment by Lxiamail** [comment]
@xiedongweo Thanks for the information. It's in our pipe to work on. However, due to other priority, we may not be able to get back to you very soon.

**Comment by StephenBonikowsky** [comment]
@xiedongweo Sorry for the delay. I took a look at this and it looks like Add Service Reference is deliberately converting the Stream to a byte array when generating the client code. We need to check a few things to decide if there is valid reason for this behavior, it doesn't do this when using a desktop console app so it is specific to the UWP app.

In the meantime it is simple to get around it by modifying the generated code to use `System.IO.Stream` instead of the `byte[]`. The generated code is in the Reference.cs file which is hidden but you can get to by F12ing the `Service1Client` type from your repro.

**Comment by xiedongweo** [comment]
@StephenBonikowsky  Thanks for your response. I will be going to wait for your good news.

**Comment by dasetser** [comment]
@xiedongweo The Add Service Reference feature is owned by a different team and issues for it are not tracked on GitHub. I have filed an internal bug and assigned it to the team that owns this feature so they can be made aware of the problem and investigate.

Since they don't track issues on Github and you have a work around for now, I'm closing this issue. If you want a follow up from that team please open a new feedback item at https://developercommunity.visualstudio.com, which can be used for all Visual Studio issues.

**Comment by xiedongweo** [comment]
@dasetser  Could you tell me the bug number? Then, I can attach the bug number on my thread when I post the question on https://developercommunity.visualstudio.com/.

**Comment by dasetser** [comment]
The internal bug number is 793124. If you include that in your feedback item they should be able to find it.
