### ISSUE TITLE
.NET Desktop assemblies are being loaded on OSX in wcf/master/ builds

### ISSUE THREAD

**Issue by MattGal** [dotnet/wcf#3232]
@dotnet-mc-bot commented on [Fri Oct 19 2018](https://github.com/dotnet/core-eng/issues/4430)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2135728
  - **Agent:** DDVSOMACAGE009
  - **Error log:** /Users/buildagent/agent/_work/0/s/wcf/src/packages.builds(0,0): error MSB4062: The "UpdatePackageIndex" task could not be loaded from the assembly /Users/buildagent/agent/_work/0/s/wcf/Tools/net46/Microsoft.DotNet.Build.Tasks.Pack...

@jcagme, @markwilkie

---

@MattGal commented on [Mon Oct 22 2018](https://github.com/dotnet/core-eng/issues/4430#issuecomment-431896465)

This failure is a source-code-authoring one:  Specifically something got tweaked such that the .NET Desktop version of build tasks are getting loaded on OSX ,which will never work:

```
error MSB4062: The "UpdatePackageIndex" task could not be loaded from the assembly /Users/buildagent/agent/_work/411/s/wcf/Tools/net46/Microsoft.DotNet.Build.Tasks.Packaging.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```
(note the "net46" in the path)

**Comment by StephenBonikowsky** [comment]
This was a special build intended to produce a stable package of 'dotnet-svcutil.xmlserializer' which it did. I think setting 'PB_IsStable' to "true" which I believe triggers the "UpdatePackageIndex" task is somehow causing the Desktop version of tools to get used.

Since we use our Windows build to provide us with the packages we build this is ok except that it tries to do it on the Linux and OSX builds as well.

I wonder, when CoreFx builds stable packages setting 'PB_IsStable' does it also run on Linux/OSX?

**Comment by StephenBonikowsky** [comment]
Thanks, @MattGal 
I was passing this variable to the child build defs via the pipelines json file, so I just modified it there only for Linux and OSX.
