### ISSUE TITLE
dotnet core wcf client httpclient socket can't reuse

### ISSUE THREAD

**Issue by caozhiyuan** [dotnet/wcf#3263]
in .net framework httpChannelFactory Closed, httpwebrequest socket client is ESTABLISHED, in dotnet core 2.1 wcf client httpClient just disposed

**Comment by Lxiamail** [comment]
@caozhiyuan in dotnet core, httpclient is bounded to httpChannelFactory. This behavior is expected. If you want to reuse httpClient, can you reuse the HttpChannelFactory?

**Comment by caozhiyuan** [comment]
now we use wcf client ioc instance scoped , so it will be closed on webapi request end @Lxiamail .  httpChannelFactory can extension some interface to reuse httpClient ?

**Comment by Lxiamail** [comment]
>>httpChannelFactory can extension some interface to reuse httpClient ?
@caozhiyuan What do you mean?

**Comment by caozhiyuan** [comment]
like this https://github.com/dotnet/wcf/blob/e3252b3f2a7a5b074d7143186dfe21dde4adc293/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs#L138 @Lxiamail

**Comment by mconnew** [comment]
@caozhiyuan, you have two options. The one I would recommend is to cache your WCF client (I presume it's one created using the connected services tool?) and reuse it for all your requests. It is thread safe to do this. The reason I recommend this is because a ChannelFactory is quite a heavy weight class and isn't cheap to create as it builds a contract description by reflecting over your service contract. The second option is to create a delegate which provides the HttpMessageHandler for the HttpChannelFactory. You found the line of code where we go and look for a delegate which does this. I wrote a reasonably complete description including links to an example about how to implement this option in [this comment](https://github.com/dotnet/wcf/issues/3230#issuecomment-431921166).
