### ISSUE TITLE
Potential deadlock when calling WCF service from ASPNET Core on dotnet core.

### ISSUE THREAD

**Issue by dcumbo** [dotnet/wcf#3309]
# Potential deadlock when calling WCF service from ASPNET Core on dotnet core.

We have an ASP.NET Core 2.1 WebApi running on .NET Core 2.1 which proxies calls through to a WCF Service. We have noticed strange behaviour during a load test which leads to requests timing out.

When concurrent requests are made to the WebAPI (in most cases) the responses stall until all of them are processed. As the number of requests increases, they keep getting queued with no responses being sent. This results in delayed responses or timed out requests, depending on the load.

In the case of a substantial number of requests, a `TimeoutException` is thrown by the service client when it exceeds the SendTimout limit. Wireshark shows that requests are not being made by the service client at all. This behaviour exhibits itself only on ASP.NET Core running on .NET Core. When running the exact code under .NET Framework the issue is not reproduced; responses are received while requests are being sent out.

The behavior we are noticing when doing a series of parallel requests is that all requests are sent to the service and responded to at the same time, therefore if we perform 50 requests it will take 10 seconds to answer all of them, whereas if we send 1000, it will take 150seconds.

We also ran some profiling and noticed that >99.9% of the request was held at `System.Runtime.TaskHelpers.WaitForCompletionNoSpin(Task)` in `System.Private.ServiceModel`. Hence why we're suspecting that this could be a deadlock.

![Profiler Image](https://user-images.githubusercontent.com/80220/49443079-b8769100-f7cb-11e8-92a5-d139fd954f74.png)

## Steps to reproduce
* [Download source code](https://github.com/zeppu/WcfIssue).
* Run multiple projects (`LoadTest`, `NetCoreApi`, `NetFrameworkApi` & `WcfService`).
* In the `LoadTest` program, select the second option by typing `2` and hitting the return key.
	* Wait for the application to finish and see the way it behaves.
* Hit return to go back to the main list of options
* In the `LoadTest` program, select the first option by typing `1` and hitting the return key.
	* Wait for the application to finish and see the way it behaves.
* Increase count by writing `c:count` e.g. `c:100` and repeat execution by writing `2` or `1` depending on which application you want to hit.

**Comment by mconnew** [comment]
There are two possible causes. I suspect you are calling WCF using a synchronous contract based on your screenshot. Use Task based Async methods instead and you shouldn't see this problem. Basically if you are in a Task based context we expect you to call WCF using Task based methods. The second possibility is you aren't opening the channel before making a call. If a channel hasn't been opened yet, the first call will implicitly open the channel. Because of a constraint to ensure call order is maintained, if another call arrives before Open has completed, it gets queued up, with each call made on the channel queueing up and executing sequentially in order until the queue is drained. The solution is to cast the channel to IChannel and call Open.

**Comment by Lxiamail** [comment]
@dcumbo Hope @mconnew's suggestion helped. Closing the issue due to being inactive for a while.
