### ISSUE TITLE
Running build.cmd doesn't generate the .nupkg files in the bin folder

### ISSUE THREAD

**Issue by mtycholaz** [dotnet/wcf#3373]
Building a dotnetcore 2.1 console application and attempting to add a reference to the generated NuGet packages. 

I've followed the documentation laid out in **using-prerelease-wcf-packages.md**, specifically

1. Build the packages using 'build.cmd" in a CMD window.
2. Edit NuGet.config to declare the location of the generated .nupkg files (again, use VS Package Manager Settings or just directly edit the NuGet.config file)
For example, I just created a new package source to point directly to the folder where build.cmd placed the WCF built packages: c:\git\wcf\bin\packages\Debug.

I'm finding though that running the build.cmd doesn't generate any .nupkg in the bin folder. I've also tried adding a reference manually to the System.ServiceModel.dll in the `bin\AnyOS.AnyCPU.Debug\netfx\netcoreapp` folder. The application builds fine, but at runtime I'm met with an exception

`Could not load file or assembly 'System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=MSIL'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context.`

**Comment by StephenBonikowsky** [comment]
Hi @mtycholaz we are going through significant updates to our build infrastructure, so I apologize for the out-of-date status of many of the .md docs.

If you were to check out the WCF repo (here is an [example ](https://github.com/dotnet/corefx/wiki/Checking-out-the-code-repository)for corefx repo that would also work for the WCF repo)
You could then run the following commands, the 'build.cmd' command would also build packages.

`clean.cmd -all`
`sync.cmd -p -- /p:ArchGroup=x64 /p:RuntimeOS=win10`
`build.cmd -buildArch=x64 -Release -- /p:RuntimeOS=win10`
`build-tests.cmd -buildArch=x64 -Release -Outerloop -- /p:RuntimeOS=win10 /p:Root_Certificate_Installed=true /p:Client_Certificate_Installed=true /p:SSL_Available=true /m:1`

Hopefully this solves your problem.

FYI, the System.ServiceModel.dll assembly you tried to use is a reference assembly that is used at runtime to type-forward for applications built on .netcore but running on target framework netfx (which is the full desktop framework), so that wouldn't work.

**Comment by Lxiamail** [comment]
@mtycholaz Hope your issue has been resolved.
