### ISSUE TITLE
svcutil on .NET Core Generate only Async Method ?

### ISSUE THREAD

**Issue by EliezerMarkovsky** [dotnet/wcf#3387]
Hi
Visual-Studio-2017 (15.9.6)
I have the same WCF-Service within the same solution
On this Solution I have Two Class Library Projects: 
1. .NET Framework 
2. .NET Core

I Connected WCF-service as a reference to Both Class Library Projects.

After generating Reference.cs file I see:

In .NET Framework Project (Reference.cs):  
`[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]` 
Is Generated with **Both sync and async** Method.

In .NET Core Project (Reference.cs):  
`[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]` 
Is Generated with **Only sync** Method.

Why is the behavior different for the same service between .NET Framework  and .NET Core ?

**Comment by dasetser** [comment]
Currently the tool only supports generating async operations for WCF on .NET Core. This has been previously answered in #654 (and a few other issues). Since we've heard multiple reports of customers wanting this I'm going to reopen that issue to investigate if it's possible to add an option to generate synchronous methods. I'll close this issue so we only have one open issue tracking the investigation, but feel free to add to the discussion on that issue.
