### ISSUE TITLE
Unable to generate deps.json, it may have been already generated.  You can specify the "-d" option before the tool name for diagnostic output (for example, "dotnet -d <toolname>": C:\Program  Files\dotnet\sdk\2.2.104\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj

### ISSUE THREAD

**Issue by atifalibhatti** [dotnet/wcf#3391]
I get following errors using 

dotnet svcutil http://localhost:8092/AuthenticationService.svc?wsdl --Verbosity debug > out.log

dotnet : Unable to generate deps.json, it may have been already generated.  You can specify the "-d" option before the tool name for diagnostic output (for example, "dotnet -d <toolname>": C:\Program 
Files\dotnet\sdk\2.2.104\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj
At line:1 char:1
+ dotnet svcutil http://localhost:8092/AuthenticationService.svc?wsdl - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unable to gener...nerateDeps.proj:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

and out.log is empty.

**Comment by atifalibhatti** [comment]
Microsoft WCF Web Service Reference Prodiver has following output.
![untitled123](https://user-images.githubusercontent.com/20585472/53015975-3282f180-346e-11e9-8892-b2c6d4dacbd5.png)

**Comment by atifalibhatti** [comment]
Event dotnet svcutil --help has the same error.

**Comment by dasetser** [comment]
@atifalibhatti Thanks for reporting this. Do you have any custom nuget.config on your machine? Can you provide the output of running the tool with the "-d" parameter (e.g. `dotnet svcutil -d --help`) so we can check if it's similar to the other report in #3225?

In that issue it looked like a problem with nuget restore failing, but I'm not sure why that would fail unless you had some kind of special configuration.

**Comment by atifalibhatti** [comment]
Thank you for your response.
1. There is no custom nuget.config
2. Following is the output of the dotnet -d svcutil --help:
![image](https://user-images.githubusercontent.com/20585472/53202943-9ad9fa80-3649-11e9-80e8-b9dc63cdbe15.png)

**Comment by atifalibhatti** [comment]
3.Output of dotnet svcutil -d --help
![image](https://user-images.githubusercontent.com/20585472/53203090-015f1880-364a-11e9-8a20-f5f9edba3114.png)

**Comment by dasetser** [comment]
You're right that I meant dotnet -d svcutil. Thanks for including that output as well.

Does your %temp% directory have a semicolon in the name? It looks like it's trying to set ProjectDepsFilePath to %localappdata%\Temp;\tmp35D9.tmp. The msbuild parameter parsing logic thinks the semicolon is a separator character, and so it tries to use "\tmp35D9.tmp" as a standalone parameter, and fails. 

I would guess the code is using whatever folder your %temp% environment variable is set to, but I have no idea why it would include a semicolon in the name.

**Comment by atifalibhatti** [comment]
You Rock!
That is it. I wish I could get more details or some option to have a detailed output using Microsoft WCF Connected Service provider tool. For some strange reason, my temp paths had semicolons which where causing the problem. Got rid of them and bingoo! Thanks a bunch again. That solves it.

**Comment by karthik33** [comment]
Hi Got similar issue andI am not able to proceed to add service reference using wsdl file.

**Below is the error Log**

05/10/2019 13:59:23],24,Importing web service metadata ...
[05/10/2019 13:59:23],17,Number of service endpoints found: 1
[05/10/2019 13:59:23],67,Scaffolding service reference code ...
[05/10/2019 13:59:23],17,Executing command [C:\Users\BD9086\AppData\Local\Temp\WCFConnectedService\2019_May_10_13_59_23\svcutil_starter]
"dotnet new console --no-restore --force --type project --language C# --output . --name svcutil_starter"
[05/10/2019 13:59:30],67,Executing command [C:\Users\BD9086\AppData\Local\Temp\WCFConnectedService\2019_May_10_13_59_23\svcutil_starter]
"dotnet restore --ignore-failed-sources"
[05/10/2019 13:59:36],60,Executing command [C:\Users\BD9086\AppData\Local\Temp\WCFConnectedService\2019_May_10_13_59_23\svcutil_starter]
"dotnet svcutil --additionalprobingpath "C:\Users\BD9086\.nuget\packages" "C:\Users\BD9086\AppData\Local\Temp\WCFConnectedService\2019_May_10_13_59_23\SvcUtilParams.txt""
[05/10/2019 13:59:39],67,Unable to generate deps.json, it may have been already generated.  You can specify the "-d" option before the tool name for diagnostic output (for example, "dotnet -d <toolname>": C:\Program Files\dotnet\sdk\2.1.503\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj
[05/10/2019 13:59:39],67,Done.

**Comment by dasetser** [comment]
@karthik33 Can you open the command prompt and go to this directory: C:\Users\BD9086\AppData\Local\Temp\WCFConnectedService\2019_May_10_13_59_23\svcutil_starter

And attach the output from the following command?
`dotnet -d svcutil --help`

**Comment by karthik33** [comment]
Hi, 
Thank you for your response. Please find attached below as you requested.


C:\Users\BD9086\AppData\Local\Temp\WCFConnectedService\2019_May_10_13_59_23\svcutil_starter>dotnet -d svcutil --help
Telemetry is: Enabled
projectfactory: MSBUILD_EXE_PATH = C:\Program Files\dotnet\sdk\2.1.503\MSBuild.dll
projectfactory: MSBuild project path = C:\Users\BD9086\AppData\Local\Temp\WCFConnectedService\2019_May_10_13_59_23\svcutil_starter\svcutil_starter.csproj
projecttoolscommandresolver: resolving commandspec from 1 Tool Libraries.
projecttoolscommandresolver: Attempting to resolve command spec from tool dotnet-svcutil
projecttoolscommandresolver: nuget packages root:
- C:\Users\BD9086\.nuget\packages\
- C:\Program Files\dotnet\sdk\NuGetFallbackFolder
projecttoolscommandresolver: found tool lockfile at : C:\Users\BD9086\.nuget\packages\.tools\dotnet-svcutil\1.0.1\netcoreapp2.1\project.assets.json
projecttoolscommandresolver: expect deps.json at: C:\Users\BD9086\.nuget\packages\.tools\dotnet-svcutil\1.0.1\netcoreapp2.1\dotnet-svcutil.deps.json
Generating deps.json at: C:\Users\BD9086\.nuget\packages\.tools\dotnet-svcutil\1.0.1\netcoreapp2.1\dotnet-svcutil.deps.json
MSBuild arguments: "C:\Program Files\dotnet\sdk\2.1.503\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj" -property:ProjectAssetsFile=\"C:\Users\BD9086\.nuget\packages\.tools\dotnet-svcutil\1.0.1\netcoreapp2.1\project.assets.json\" -property:ToolName=dotnet-svcutil -property:ProjectDepsFilePath=C:\Users\BD9086\AppData\Local\Temp\tmp78CE.tmp -property:TargetFramework=netcoreapp2.1 -property:AdditionalImport=C:\Users\BD9086\.nuget\packages\microsoft.netcore.app\2.0.0\build\netcoreapp2.0\Microsoft.NETCore.App.props
Unable to generate deps.json, it may have been already generated.  You can specify the "-d" option before the tool name for diagnostic output (for example, "dotnet -d <toolname>": Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
C:\Program Files\dotnet\sdk\2.1.503\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj : error NU1101: Unable to find package System.Net.WebSockets.Client. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org, SvcutilNuGetFeed
C:\Program Files\dotnet\sdk\2.1.503\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj : error NU1102: Unable to find package NuGet.Versioning with version (>= 4.5.0)
C:\Program Files\dotnet\sdk\2.1.503\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj : error NU1102:   - Found 1 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 3.5.0-beta2-1484 ]
C:\Program Files\dotnet\sdk\2.1.503\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj : error NU1102:   - Found 0 version(s) in SvcutilNuGetFeed
C:\Program Files\dotnet\sdk\2.1.503\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj : error NU1102:   - Found 0 version(s) in nuget.org


Microsoft.DotNet.Cli.Utils.GracefulException: Unable to generate deps.json, it may have been already generated.  You can specify the "-d" option before the tool name for diagnostic output (for example, "dotnet -d <toolname>": C:\Program Files\dotnet\sdk\2.1.503\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.GenerateDepsJsonFile(LockFile toolLockFile, NuGetFramework framework, String depsPath, SingleProjectInfo toolLibrary, String toolDepsJsonGeneratorProject)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.GetToolDepsFilePath(SingleProjectInfo toolLibrary, NuGetFramework framework, LockFile toolLockFile, String depsPathRoot, String toolDepsJsonGeneratorProject)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveCommandSpecFromToolLibrary(SingleProjectInfo toolLibraryRange, String commandName, IEnumerable`1 args, IProject project)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveCommandSpecFromAllToolLibraries(IEnumerable`1 toolsLibraries, String commandName, IEnumerable`1 args, IProject project)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveFromProjectTools(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CompositeCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CommandResolver.TryResolveCommandSpec(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

**Comment by dasetser** [comment]
@karthik33 Thanks for attaching that and reporting the issue. It looks like it's an error finding some dependencies of dotnet-svcutil. I believe this should be fixed in VS2019. If you can't upgrade to VS2019 yet I would suggest using the [dotnet-svcutil command line tool](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil2x). You shouldn't see this same issue if you use the latest version (2.0.0).

**Comment by glapsvin** [comment]
as posted in the Vs 2017 thread, still same problem with 2019 16.2.0 prev 3

**Comment by ChandrasekarRadhakrishnan** [comment]
Hi Im having the same issue in VS 2017."Unable to generate deps.json, it may have been already generated".
![image](https://user-images.githubusercontent.com/30401283/62063518-9e049280-b248-11e9-8e02-ad231ea6c4d7.png)

This is my screenshot for temp path do i need to remove those semicolon's can any one guide me how to resolve the issue.

**Comment by ChandrasekarRadhakrishnan** [comment]
Can anyone tell which semicolon i need to remove from the path

**Comment by dasetser** [comment]
@ChandrasekarRadhakrishnan That screenshot does not include the value of the TEMP variable, so I'm not sure if you're encountering the same issue as atifalibhatti. I would suggest following the instructions to install dotnet-svcutil 1.x from [here](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil1x) and running the `dotnet  -d svcutil` command and post the output here. Simply installing this can work around the issue in some cases, and in other cases the output of the command should let us see what the problem is.

**Comment by ChandrasekarRadhakrishnan** [comment]
Hi dasetser,

Thanks for replying to my comments.
If i try to install by the command dotnet tool install --global dotnet-svcutil --version 2.0.1 in pakage manager console i'm getting the below issue.

error NU1101: Unable to find package dotnet-svcutil. No packages exist with this id in source(s): C:\Program Files\dotnet\sdk\NuGetFallbackFolder, Microsoft Visual Studio Offline Packages
dotnet : The tool package could not be restored.
At line:1 char:1
+ dotnet tool install --global dotnet-svcutil --version 2.0.1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The tool package could not be restored.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Tool 'dotnet-svcutil' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this n
ame was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

This issue i'm getting both in VS 2017 and VS 2019.

**Comment by ChandrasekarRadhakrishnan** [comment]
![image](https://user-images.githubusercontent.com/30401283/62128005-1757c000-b2f1-11e9-8efa-6588c60f6dc1.png)

The wsdl file is generation in my temp path but in Visual Studio

**Comment by ChandrasekarRadhakrishnan** [comment]
This is the path 
![image](https://user-images.githubusercontent.com/30401283/62128094-48d08b80-b2f1-11e9-8576-8ff509dfe8f6.png).

My question is how come WSDL class can generate in temp but not in VS 2017

**Comment by dasetser** [comment]
@ChandrasekarRadhakrishnan The error you're getting when trying to install dotnet-svcutil looks like it's not checking nuget.org (only the offline packages and nuget fallback folder). Do you have nuget.org as a package source? Also, for the workaround I mentioned you want to use the install directions for dotnet-svcutil 1.x rather than 2.0. 

Are you saying that you are only getting the error with the WCF Connected Service when using VS2017 but it works in VS2019? Because there are a few known issues for VS2017 that we fixed for VS2019.

**Comment by AnReZa** [comment]
I'm having the exact same problem with the most recent version of Visual Studio. dotnet-svcutil runs fine, though. Any solution?

**Comment by dasetser** [comment]
@AnReZa This error means there is something about your environment that's causing the an error when the tool tries to install dotnet-svcutil. I'm guessing you're using the global version of dotnet-svcutil which does not have this problem, but the WCF Connected Service uses it differently to avoid having to mess with the global version on your machine. 

To figure out what's wrong I would suggest following the instructions to install dotnet-svcutil 1.x from [here](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil1x) and running the `dotnet -d svcutil` command. The output of that should give a hint about what's going on.

**Comment by AnReZa** [comment]
@dasetser Why exactly should I install version 1.x, if it's version 2.x that doesn't work?

**Comment by dasetser** [comment]
@AnReZa For debug purposes to get the more detailed error. It's a slightly different scenario than what's actually happening, but I think it will be close enough to give you the error and let you see what's happening.

If you want the details, this is an error you get from the dotnet sdk and is specific to installing a local CLI tool. I think you would likely get the same result trying to install and run any project-level CLI tool, not just dotnet-svcutil. I said to use the 1.x instructions because they are the only instructions we have for using dotnet-svcutil as a local CLI tool (because we released dotnet-svcutil 2.x as a global CLI tool). I figured it would be easier to just follow those instructions than try to look through the temp files from the WCF Connected Service or go track down the specific nuget package and add it to your own project, and I think you'll likely find the same results either way.

What's happening under the covers here is the WCF Connected Service has a nuget package with a specific version of dotnet-svcutil that it installs and runs as a local CLI tool. We released dotnet-svcutil 2.x, as a global CLI tool because it's a better customer use case than a local tool. However, the UI tool needs to be able to be installed side-by-side and use different versions without modifying the global version installed on your machine. So to do that it uses it as a local CLI tool instead (including the latest version of dotnet-svcutil).

If you really want to make sure it's the same scenario as in VS or if you don't get the error with the 1.x version for some reason you could look in your %temp% folder for a WCF Connected Service folder and see if you can find the placeholder project it installed dotnet-svcutil and run `dotnet -d svcutil-lib` from there. Alternatively, you could do the same thing yourself by creating a new  console project project, adding a nuget.config with a new package source that includes the folder with dotnet-svcutil-lib.nupkg (found in <VSInstallDir>\Common7\IDE\Extensions\Microsoft\WCF Connected Service\svcutil), and installing it as a DotNetCliToolReference, and then running it.

**Comment by hrafnkel** [comment]
VS2019 16.5.1

Importing web service metadata ...
Number of service endpoints found: 1
Scaffolding service reference code ...
Error:Unable to generate deps.json, it may have been already generated.  You can specify the "-d" option before the tool name for diagnostic output (for example, "dotnet -d <toolname>": C:\Program Files\dotnet\sdk\3.1.200\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj
Done.
