### ISSUE TITLE
[dotnet-svcutil] Error: Method 'Log' ... does not have an implementation

### ISSUE THREAD

**Issue by lefrac01** [dotnet/wcf#3432]
I run the tool from the project folder of an existing netstandard2.0 project against a running service url:
dotnet-svcutil http://localhost/xyz/xyz.svc

No files are generated.  This error message is reported:
**Error: Method 'Log' in type 'Microsoft.Tools.ServiceModel.Svcutil.DebugLogger' from assembly 'dotnet-svcutil-lib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' does not have an implementation.
Exit code: 9**

**Comment by lefrac01** [comment]
from a new project created using "dotnet new classlib", the same command succeeds

**Comment by dasetser** [comment]
@lefrac01 Thanks for reporting this. Does your project have a dependency (directly or indirectly) on the NuGet.Common package? This looks like a dependency conflict happening and it's ending up using a newer version of this package which exposes a bug in our tool.

If so, I think you should be able to avoid the bug by passing the ` --noTypeReuse` parameter. Your proxy won't reuse any types this way, but I think it will avoid the part of the code this bug is in.

**Comment by lefrac01** [comment]
Thanks for the reply.  Yes, NuGet.Common is a dependency.

I imported the files generated using the blank project and it worked fine.  The tool works now with or without --noTypeReuse in the problem project so I can't help confirm that as a workaround.

I'm not sure what change got rid of the issue.  The csproj has a new reference to ServiceModel.  Some nuget dependencies were converted from net462 to netstandard2.0.
