### ISSUE TITLE
WCF Web Service Reference Provider not updated

### ISSUE THREAD

**Issue by Tbd19** [dotnet/wcf#3483]
When using the WCF Provider from the Visual Studio I get an error about a duplicate item that is the same as https://github.com/dotnet/wcf/issues/3103. And also the generated file does not compile because the namespace used is Microsoft.CodeDom instead of System.CodeDom

If I run the dotnet-svcutil which is version 2.0.0 there is no error and the generated file contains the correct namespace.

The VS version that I use is 15.9.9 and I do not know where to look for the version of the WCF Provider tool version

**Comment by dasetser** [comment]
Visual Studio 2017 uses an older version of dotnet-svcutil that doesn't have the fix. This won't get fixed in the WCF Web Service Reference Provider until Visual Studio 2019 (which does use dotnet-svcutil 2.0 in the latest preview). Until you can upgrade to VS 2019 you'll need to use dotnet-svcutil.

**Comment by Lxiamail** [comment]
Please reactive the issue if you still have problem on VS 2019.
