### ISSUE TITLE
Async friendly inspectors

### ISSUE THREAD

**Issue by EricStG** [dotnet/wcf#3491]
The current `IClientMessageInspector` enforces us to implement both `BeforeSendRequest` and `AfterReceiveReply`.

Having a similar inspector pattern to Asp.net core filters/middleware would clean up a fair amount of code. Something such as:

```csharp
Task ExecuteAsync(Func<Task> next)
{
    // Do something before
    await next() // Calls the next inspector/client
    // Do something after
}
```

**Comment by r-pankevicius** [comment]
I wonder if such chaining is enough for **expired OAuth2 token scenario** where replay of service method call is needed after token is refreshed? Will help in this scenario?

I've done some work on my project after code review by @mconnew to pass "Authorization: Bearer token" header [via message inspector](https://github.com/dotnet/wcf/issues/3472#issuecomment-478127943). But I ran into issues with ugly over-wiring between the WCF client and message inspector due to the fact that IClientMessageInspector.BeforeSendRequest() method is synchronous.

Client method call + message inspector orchestration is done by [client method telling message inspector "make token ready" when it's needed here](https://github.com/r-pankevicius/WcfClientWithOMiauAuthentification/blob/Pass-token-via-message-inspector/src/LazyCatWcfService/LazyCatConsole/LazyCatServiceOMiauManualClient.cs).

I've put these experiments on a separate branch (too ugly) and returned back to setting headers via OperationContext OutgoingMessageProperties. Not perfect but somehow more fluent in async world.

**Comment by mconnew** [comment]
@EricStG, I have a little gift for you. I already had this as a prototype when you opened the issue but your opening this issue prompted me to polish it, added some tests, fixed the bugs the tests discovered, and push it to GitHub and publish to nuget.  
GitHub source: https://github.com/mconnew/Capri
nuget package: https://www.nuget.org/packages/Capri/

**Comment by EricStG** [comment]
@mconnew that looks very promising. I'll be taking a deeper look as soon as I get a chance. Thanks for this!

**Comment by StephenBonikowsky** [comment]
No further action needed on this.
