### ISSUE TITLE
Stack overflow exception

### ISSUE THREAD

**Issue by PhilPJL** [dotnet/wcf#3542]
![image](https://user-images.githubusercontent.com/271656/55502054-a1de2a80-5643-11e9-877e-b8f98a2783c8.png)

I've just updated to VS 2019.  Was interested to see if there was any progress on creating a WCF reference from a Xamarin forms app.

I pointed the tool at a WCF service.  Bang!  so, no progress.  

I just don't know how to express my disappointment.

**Comment by Lxiamail** [comment]
This issue is traced by https://github.com/dotnet/wcf/issues/2463. This work is still blacked by Xamarin/mono doesn't support task based async.

**Comment by dasetser** [comment]
@PhilPJL Thanks for reporting this issue. We've confirmed this is Stackoverflow exception is a bug in the tool and is not limited to Xamarin projects. We'll investigate a fix for this. The only workaround for now is to uncheck the "Reuse types in referenced assemblies" checkbox in the WCF Connected Service. 

For Xamarin forms apps, as far as I know this still won't work at runtime because of the reasons described in #2463.

**Comment by PhilPJL** [comment]
How can an issue like this (e.g. the stack overflow) not be planned to be fixed in the short term?  You've had 3 months.  What is going on?

**Comment by dasetser** [comment]
@PhilPJL Fixing this stack overflow exception is part of our plan for the next release of dotnet-svcutil (which will make it into VS shortly after). Sorry that the labels and milestone aren't clear. They're set up for the WCF Core release schedule, which is different from dotnet-svcutil/VS. We'll look into if we can make it more clear which tooling issues we're looking at.

**Comment by dasetser** [comment]
This is fixed in dotnet-svcutil 2.0.1.
