### ISSUE TITLE
Can't Add ASMX Web Reference

### ISSUE THREAD

**Issue by MrGadget1024** [dotnet/wcf#3649]
Visual Studio 2017 15.9.12

This fails with .Net Core 2.1 and works perfectly in Framework 4.8.

URL: https://webservices.solidcommerce.com/ws.asmx

With a .Net Framework 4.8 Class Library Project, add a Web Reference:

![image](https://user-images.githubusercontent.com/9826063/58120146-9edad180-7bd2-11e9-9282-0099c5462f81.png)

... which correctly gives me this:

![image](https://user-images.githubusercontent.com/9826063/58120246-cf227000-7bd2-11e9-8499-a3363c322355.png)

... and I use it with code like this:

```vb
Imports SC = WsdlTestNet48.com.solidcommerce.webservices

Public Class Class1

    Private ws As New SC.ws

    Const AppKey As String = "MyAppKey"
    Const SecurityKey As String = "MySecurityKey"

    Public Sub DoWork()
        ws.CookieContainer = New Net.CookieContainer
        ws.Proxy = Nothing

        Dim Filter As New SC.SearchOrderFilter With
            {.OrderStatus = SC.OrderStatusEnum.PAID}

        Dim Node As Xml.XmlNode = ws.SearchOrdersV6(AppKey, SecurityKey, Filter)

        ' Do something with the results
    End Sub

End Class
```

Trying to add the Web Reference in a .Net Core 2.1 Class Library project, I get this:

![image](https://user-images.githubusercontent.com/9826063/58120377-1f013700-7bd3-11e9-9b86-acfbcc6133b6.png)

Please note that AWS Lambda does not support .Net Framework...they only accept .Net Core 2.1 so I need an answer how to deal with this.

**Comment by MrGadget1024** [comment]
Apparently VB is the red-headed step-child **again**.

Switching to a C# project I can now see the WCF Web Service Reference Provider, but even that gives a flood of warnings and a LOT of the methods are missing as it seems I only have Async methods, so converting the code above to C# is unusable:

![image](https://user-images.githubusercontent.com/9826063/58126182-57f3d880-7be0-11e9-977c-c0d49b02b832.png)

**Comment by dasetser** [comment]
@MrGadget1024 The WCF Web Service Reference Provider is the correct tool to generate a WCF proxy for a .NET Core client. It does not have support for VB. This tool is similar to Add Service Reference, rather than Add Web Reference, but it should be able to generate a proxy for an asmx service as well. The tool does show warnings if there are parts of the wsdl it's unable to use (for example if something is defined that is not supported by WCF on .NET Core), but the file it generates should still be usable.

As far as only generating async methods, in the latest version of Visual Studio 2019 we added an option to also generate synchronous methods. I'd suggest trying the latest version of VS2019 and seeing if you can get a usable proxy class. Let us know if you run into further issues.

**Comment by MrGadget1024** [comment]
Here's the thing...that web service, and millions like it, are not WCF services.  I want Add Web Reference to work like it does in Framework.  With Service Contract, I lose my Cookie Container, my Proxy, PreAuthentication, and apparently VB is getting pissed on again.

**Comment by MrGadget1024** [comment]
Installed 2019 and added the connected service again through the WCF Web Service Reference Provider.

Broken code generated (duplicated the namespace:
![image](https://user-images.githubusercontent.com/9826063/58176864-3d1d7480-7c71-11e9-841a-8e141adcb5fa.png)

Same warnings as before
```
Cannot import wsdl:port
Detail: There was an error importing a wsdl:binding that the wsdl:port is dependent on.
XPath to wsdl:binding: //wsdl:definitions[@targetNamespace='http://webservices.liquidatedirect.com/']/wsdl:binding[@name='wsHttpPost']
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://webservices.liquidatedirect.com/']/wsdl:service[@name='ws']/wsdl:port[@name='wsHttpPost']
Cannot import wsdl:binding
Detail: The required WSDL extension element 'binding' from namespace 'http://schemas.xmlsoap.org/wsdl/http/' was not handled.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://webservices.liquidatedirect.com/']/wsdl:binding[@name='wsHttpPost']
Cannot import wsdl:port
Detail: There was an error importing a wsdl:binding that the wsdl:port is dependent on.
XPath to wsdl:binding: //wsdl:definitions[@targetNamespace='http://webservices.liquidatedirect.com/']/wsdl:binding[@name='wsHttpGet']
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://webservices.liquidatedirect.com/']/wsdl:service[@name='ws']/wsdl:port[@name='wsHttpGet']
Cannot import wsdl:binding
Detail: The required WSDL extension element 'binding' from namespace 'http://schemas.xmlsoap.org/wsdl/http/' was not handled.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://webservices.liquidatedirect.com/']/wsdl:binding[@name='wsHttpGet']


Importing web service metadata ...
Number of service endpoints found: 2
Scaffolding service reference code ...
Warning:Warning: Cannot import wsdl:binding
Detail: The required WSDL extension element 'binding' from namespace 'http://schemas.xmlsoap.org/wsdl/http/' was not handled.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://webservices.liquidatedirect.com/']/wsdl:binding[@name='wsHttpGet']
Warning:Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://webservices.liquidatedirect.com/']/wsdl:service[@name='ws']/wsdl:port[@name='wsHttpGet']
Warning:Warning: Cannot import wsdl:binding
Detail: The required WSDL extension element 'binding' from namespace 'http://schemas.xmlsoap.org/wsdl/http/' was not handled.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://webservices.liquidatedirect.com/']/wsdl:binding[@name='wsHttpPost']
Warning:Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://webservices.liquidatedirect.com/']/wsdl:service[@name='ws']/wsdl:port[@name='wsHttpPost']
Updating project ...
Done.
```

**Comment by dasetser** [comment]
@MrGadget1024 Thanks for letting us know you're also running into the duplicated namespace issue. This has been reported in issue #3158 and is in our backlog to investigate. I would suggest following that issue which we will respond to when we have updates about it, and if possible modifying the generated code to see if there are any other errors.

Unfortunately as far as Add Web Reference goes we do not have any plans to create a similar tool for .NET Core. The closest tool is the WCF Web Service Reference Provider (or the dotnet-svcutil command line tool), which will generate proxies for WCF. 

I'm closing this issue because there is already an issue tracking the double namespace bug, but let us know if you run into any other problems with this.
