### ISSUE TITLE
Enable Gzip in .Net Core WCF Client

### ISSUE THREAD

**Issue by maximdx** [dotnet/wcf#3665]
Hi,

I have generated a few client classes from schema files using dotnet-svcutil version 1.0.4, and put the references in a .net standard 2.0 project.
The clients are used to consume the web service by a .net core 2.2 project.
I use BasicHttpBinding for the endpoint binding and everything works fine until enabling gzip is required. I found this part is not well-documented and I cannot get much help from searching solutions on communities.
So I ask your helps for suggestions/documents how should I enable gzip in .net core clients of wcf?
Thanks in advance.

**Comment by StephenBonikowsky** [comment]
Hi @maximdx if I could make sure I understand what you are trying to do.

First, by gzip I assume you are wanting to use [GZipStream Class](https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.gzipstream?view=netcore-2.2), correct?

If so, are you trying to create an operation that sends/receives a GZipStream using the BasicHttpBinding?
Is this something new you are trying, have you had it working on the desktop .NET Framework?

It would help if you could send us an example of what you are trying to do.
@mconnew @HongGit

**Comment by mconnew** [comment]
We have an api [HttpTransportBindingElement.DecompressionEnabled](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.channels.httptransportbindingelement.decompressionenabled?view=netframework-4.8) not currently exposed in the contract to modify this behavior. The property is [there](https://github.com/dotnet/wcf/blob/f0b3b4935eb97807dbed7b73f25fbf160a523eac/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpTransportBindingElement.cs#L91) in the implementation but it doesn't do anything. Because it wasn't exposed, I just [hard coded](https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs#L292) HttpClientHandler to support compression as that's the default.  
@maximdx, as GZip compression/decompression is always enabled, this should just work. Are you having problems because of this?

**Comment by maximdx** [comment]
Hi @StephenBonikowsky  I am not sure but I think it is probably not. What I want to achieve is to add a http header "Accept-Encoding: gzip, deflate" into the request to let the service to response compressed content. I have done this in .Net Framework before.

Hi @mconnew  Later I have capture the request and response by fiddler and to my surprise the gzip header is already there. I should have checked this earlier so that I would provide this information. I believe the behavior I see is to do with the hard coded you mentioned. I am glad to know that there will be a property to control this in the future.

Thank you all for help me out.

**Comment by StephenBonikowsky** [comment]
Great! Glad we could help!
