### ISSUE TITLE
.Net Standard 2.0 System.ServiceModel.NetTcp throws exception in OpenSuse Linux

### ISSUE THREAD

**Issue by marzim** [dotnet/wcf#3666]
When running application with System.ServiceModel.NetTcp 4.4.4 in SUSE Linux Enterprise Server 12 SP2 throws a TypeLoadException.
`FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not resolve type with token 0100008b from typeref (expected class 'System.ServiceModel.NetTcpBinding' in assembly 'System.ServiceModel.NetTcp, Version=4.5.0.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')`

**Application compiled using** 

- .net standard 2.0
- Xamarin.Core.Forms.dll version 2.0.0.0
- Xamarin.Forms.Platform.GTK.dll version 2.0.0.0
- 

**Nuget package** 

- System.ServiceModel.NetTcp version 4.4.4
- System.ServiceModel.Http version 4.4.4
- System.ServiceModel.Primitives version 4.4.4
- System.ServiceModel.Security version 4.4.4

Code:

> public void StartServer()
>         {
>             string ip = "xxx.xxx.xxx.xxx; 
>             string address = "net.tcp://" + ip + ":9000/testautomation";
>             _serviceHost.Initialize(typeof(TestServer));
>             var binding = new NetTcpBinding()
>             {
>                 MaxBufferSize = int.MaxValue,
>                 MaxReceivedMessageSize = int.MaxValue,
>                 Security = new NetTcpSecurity()
>                 {
>                     Message = new MessageSecurityOverTcp()
>                     {
>                         ClientCredentialType = MessageCredentialType.None
>                     },
>                     Transport = new TcpTransportSecurity()
>                     {
>                         ClientCredentialType = TcpClientCredentialType.None
>                     },
>                     Mode = SecurityMode.None
>                 }
>             } ;
>             _serviceHost.AddServiceEndpoint(typeof(ITestContract), binding, address);
>             _serviceHost.Closed += _serviceHost_Closed;
>             _serviceHost.Faulted += _serviceHost_Faulted;
>             try
>             {                
>                 _serviceHost.Open();
>             }
>             catch (Exception exception)
>             {
>                 Logger.Instance.Error("Exception {0}", exception.Message);
>             }
>         }
> 
 

Also tried using the latest package of NetTcp and still it doesn't work

Any inputs are much appreciated.

Thanks,
-Marvin

**Comment by StephenBonikowsky** [comment]
Thanks for reporting the issue @marzim 
Xamarin uses its own implementation of WCF and there are numerous features that they have not implemented, particularly on Xamarin.Android and Xamarin.IOS.
Since both WCF Core (this repo) and Xamarin support netstandard2.0 you won't have any problem compiling but at runtime you will run into problems depending on what features you are using. Especially on unix based platforms.

Here are a couple other issues in our repo reporting similar problems, but at the end of the day it is the Xamarin implementation of WCF that needs to be updated.
#1688 and #2463 

@mconnew Is there anything you would like to add, did I misunderstand the reported scenario here?
