### ISSUE TITLE
Add Connected Service Error 0x80131500

### ISSUE THREAD

**Issue by romanv6** [dotnet/wcf#3673]
Hi,

While I am trying to add Connected Service using Microsoft WCF Web Service Reference Provider I am getting an 0x80131500 error.
![error](https://user-images.githubusercontent.com/11620386/59011978-8b687100-8836-11e9-87a2-4cd1749d7504.PNG)

So I have been comment out this entry in csproj file and it started work.
![csproj_commented](https://user-images.githubusercontent.com/11620386/59012054-c074c380-8836-11e9-82c4-d778726963b7.PNG)

Project is a class library and TargetFramework 4.6.2 

Microsoft Visual Studio Enterprise 2019
Version 16.1.2
VisualStudio.16.Release/16.1.2+29001.49
Microsoft .NET Framework
Version 4.7.03056

**Comment by StephenBonikowsky** [comment]
@dasetser Do you have any insight into this? I'm not familiar with "Microsoft WCF Web Service Reference Provider".

**Comment by dasetser** [comment]
@romanv6 Thanks for reporting this, and I'm glad you found a workaround to allow you to still use the tool.

This is the same issue reported in [feedback 526584](https://developercommunity.visualstudio.com/content/problem/526584/connected-services.html). It is fixed in Visual Studio 2019 16.2 (starting with preview 2).
