### ISSUE TITLE
Too much memory is used when CreateChannel

### ISSUE THREAD

**Issue by PccCodesix** [dotnet/wcf#3674]
When i use CreateChannel to  creat a object ,Memory increased by almost 100M.
My code is as follows
```
var binding = new BasicHttpBinding();

var endpoint = new EndpointAddress(_url);

 var factory = new ChannelFactory<xxx>(binding, endpoint);

callClient = factory.CreateChannel();
```
Is there any suggestion here? Or it's normal

**Comment by mconnew** [comment]
The amount of memory used is proportionate to the size of your contract. The more data types you have, and the more properties on your data types, and the more operations you have, the more memory that will be used. If you want to see how much memory is being used, add the following two lines to your code:
```c#
Console.ReadLine();
GC.KeepAlive(callClient);
```
Then when your process is stopped at the ReadLine call waiting for you to hit enter, run the tool [perfview](https://github.com/microsoft/perfview) and in the menu, choose Memory -> Take Heap Snapshot (or press alt+s) and take a heap snapshot of your process. You should be able to go into the memory usage view of the .gcdump created and see where the memory is being used.

**Comment by PccCodesix** [comment]
thanks for anwser ,I use the perfview tool take a heap snapshot .but But the result is this 
![image](https://user-images.githubusercontent.com/29922883/59184558-f43a4b00-8ba0-11e9-8e63-e61d8f3dd416.png)
 the static make up the majority.but i can't kown  what the specific type is. Maybe it's true , in fact my client is  static. But I can't confirm it
is there suggestions for the snapshot.is this cause by Symbol server? i'm a newer for the perfview tool

**Comment by mconnew** [comment]
It does look like it's not resolving symbols. This Just Works:tm: for me, but that might be because of the non-public symbol server I use inside Microsoft. It should all work when using the public Microsoft symbol server too. Could you zip up a dump file and provide a link? Make sure you don't have any real credentials configured, loaded into variables, or available in unused code as they can be extracted from a dump. If you're concerned about anything in your dump being publicly available, let me know and we can work out a non-public way to get it to me.

**Comment by mconnew** [comment]
It's been a week with no updates. Closing for now. Feel free to re-open if you need more help.
