### ISSUE TITLE
Cannot use reliable session in NetTcpBinging with SecurityMode.TransportWithMessageCredential

### ISSUE THREAD

**Issue by paulclarke-nec** [dotnet/wcf#3707]
Reliable sessions appears to have been implemented, based on https://github.com/dotnet/wcf/blob/d8724e17061fec86c9a6b17596fccd3f05cf758f/src/System.Private.ServiceModel/src/System/ServiceModel/NetTcpSecurity.cs#L79

However, the method is only ever invoked with isReliableSessionEnabled being false when using SecurityMode.TransportWithMessageCredential: https://github.com/dotnet/wcf/blob/c80f01c3376b832851ee5997844dd79d14eabf5b/src/System.Private.ServiceModel/src/System/ServiceModel/NetTcpBinding.cs#L161

I require a long living NetTcpBinding that will only receive a callback very infrequently, however anything beyond a minute of inactivity results in a and exception being thrown: `'System.TimeoutException' in System.Private.ServiceModel.dll`

**Comment by mconnew** [comment]
Reliable sessions hasn't been implemented. We try to keep the code the same as .NET Framework wherever possible for two reasons.  

1. Try to avoid introducing new bugs. 
2. When porting over a new feature, it reduces the risk of missing something that's needed as part of porting the feature.  

This means in the implementation code you will often see fragments or remnants of features which aren't supported. If some aspect of the feature has been exposed out of necessity, then one try to throw as soon as possible. For example, the enum `System.ServiceModel.SecurityMode` contains the value Message, but we don't support message security and removing a single value from an enum can cause all sorts of problems. So everywhere where we accept a SecurityMode enum value, we do validation and throw PlatformNotSupportedException immediately.  
Now to your actual problem. If you are getting a TimeoutException, it's because you are hitting one of the timeouts on your binding. In this case, you are probably hitting the ReceiveTimeout. The default receive timeout is 10 minutes. You can set this as high as you want and WCF won't close the connection that amount of time since it last received anything. There is a potential problems you can still run into though. If the connection ever goes away in a way that the client isn't notified (socket isn't cleanly closed by the server) you won't know that the connection has gone away until you either try to send something or the receive timeout it hit. This can happen if the server process crashes, or if you are behind a load balancer or firewall which silently closes idle connections without telling either side.  
If you need to detect when the connection dies, you need some keep alive mechanism. The simplest is to add a new operation on the server which does nothing. You can make it a OneWay operation and the client doesn't need to process a return message. Note, a OneWay operation is different than an operation with a void return type. A void return type still returns a full response message as it could respond with a Fault whereas a OneWay message returns a single ACK byte once the server has verified it can dispatch the request. So you still get a full round trip validation that the connection is still alive using a OneWay operation. Then you can kick off a background task similar to this:
```c#
Task.Run(async () =>
  {
    while(true)
    {
      await client.PingAsync();
      await Task.Delay(pingDelay); // e.g. 60 seconds
    }
  });
```

**Comment by StephenBonikowsky** [comment]
@paulclarke-nec Reliable sessions isn't available in WCF Core as @mconnew explained. Hopefully Matt helped with the issue you were having and provided some alternative ways of accomplishing what you need done.

Let us know if there is anything else we can assist with.
