### ISSUE TITLE
使用2017Net core 2.1/2.2添加webservice服务引用失败

### ISSUE THREAD

**Issue by xiongze666** [dotnet/wcf#3716]
正在导入 Web 服务元数据...
找到的服务终结点数: 1
正在搭建服务引用代码...
错误:δ�ҵ������dotnet-svcutil��ƥ��Ŀ�ִ���ļ�
完成。

![image](https://user-images.githubusercontent.com/47880804/60475170-9503be00-9ca8-11e9-8796-f53ba119628c.png)

安装都是相同的版本，同事的可以正常引用，我的就显示这个错误，是哪个补丁没安装还是其他问题？

**Comment by StephenBonikowsky** [comment]
@xiongze666 Thanks for reporting this issue. In order to best help us understand the problem could you get us the error and a full call-stack in a way that we can read it?

We are getting font formatting errors specifically with this...

> 错误:δ�ҵ������dotnet-svcutil��ƥ��Ŀ�ִ���ļ�

One possible solution is to switch your language to English long enough to re-run what you are doing, this would output the error in English which would be most useful.

Also, if you are running the dotnet-svcutil tool against a WSDL, providing us that WSDL is usually necessary to really understand what is happening.

Thank you.

**Comment by xiongze666** [comment]
> @ xiongze666感谢您报告此问题。为了最好地帮助我们理解问题，您是否可以通过我们可以阅读的方式获取错误和完整的调用堆栈？
> 
> 我们专门用这个来获取字体格式错误......
> 
> > 错误：δҵdotnet-svcutilƥĿִļ
> 
> 一种可能的解决方案是将您的语言切换到英语足够长的时间以重新运行您正在执行的操作，这将输出最有用的英语错误。
> 
> 此外，如果您正在针对WSDL运行的dotnet-SvcUtil工具工具，那么为我们提供WSDL通常是必要的，以便真正了解正在发生的事情。
> 
> 谢谢。

![image](https://user-images.githubusercontent.com/47880804/60474874-1f4b2280-9ca7-11e9-9d5e-3f68e0d4b4f4.png)

**Comment by StephenBonikowsky** [comment]
Thank you @xiongze666 
The dotnet-svcutil.exe tool is part of the SDK installed with Visual Studio, the error you are seeing is usually because your installation of VS has gotten messed-up.
You solve this by doing a repair of VS using "Visual Studio Installer".
![image](https://user-images.githubusercontent.com/12057732/60533892-7f48c580-9cb5-11e9-9237-e2f2f0d241a3.png)

**Comment by xiongze666** [comment]
> 谢谢@ xiongze666
> dotnet-svcutil.exe工具是随Visual Studio一起安装的SDK的一部分，你看到的错误通常是因为你的VS安装搞砸了。
> 您可以通过使用“Visual Studio Installer”修复VS来解决此问题。
> ![图片](https://user-images.githubusercontent.com/12057732/60533892-7f48c580-9cb5-11e9-9237-e2f2f0d241a3.png)

我按照您的方法，点击修复完成，重启电脑，重新创建项目后还是不能引用webservice服务，显示同样的错误，升级为2019版的还是不行，请问还有什么解决方案吗？

**Comment by StephenBonikowsky** [comment]
@imcarolwang Could you assist me with this issue? I can't read Chinese :)

**Comment by imcarolwang** [comment]
@xiongze666 ，你试试打开 %userprofile%\dotnet\tools, 查看是否存在 dotnet-svcutil.exe 文件? 
如果文件缺失可以通过以下命令安装：dotnet tool install --global dotnet-svcutil --version 2.0.0 （[参考链接](https://www.nuget.org/packages/dotnet-svcutil)）

**Comment by xiongze666** [comment]
> @ xiongze666，你试试打开％userprofile％\ dotnet \ tools，查看是否存在dotnet-svcutil.exe文件？
> 如果文件缺失可以通过以下命令安装：dotnet tool install --global dotnet-svcutil --version 2.0.0（[参考链接](https://www.nuget.org/packages/dotnet-svcutil)）
![image](https://user-images.githubusercontent.com/47880804/60641818-1c476200-9e60-11e9-8885-169a43ee9d41.png)
通过命令安装出现这个错误，还是不可以

**Comment by imcarolwang** [comment]
@xiongze666， 能再确认一下VS2019安装程序中的 .NET Core 2.2/2.1 development tools 也安装了吗？

@StephenBonikowsky  the error reported in issue looks due to installation problem of the dotnet-svcutil tool on specific machine, but as stated in issue, repair VS2017 even upgrade to VS2019 didn't fix it, it's said that before and after upgrade VS, it reported same error "**No executible found matching command 'dotnet-svcutil'**" when running the "**Microsoft WCF Web Service Reference Provider**" for wcf client code generation. 

I've suggested running command to add dotnet-svcutil globally as mentioned [here ](https://www.nuget.org/packages/dotnet-svcutil) , but it failed with file path not found error.  Do you think uninstall/reinstall .Net Core SDK could solve the issue?

**Comment by StephenBonikowsky** [comment]
@imcarolwang All we know for sure is that there is a problem with the environment. This isn't a common problem with VS or we would have seen other reports. Uninstalling and re-installing the SDK, even uninstalling VS entirely are all options to try and resolve this issue.

**Comment by imcarolwang** [comment]
@xiongze666 ，看起来这个是机器环境问题导致dotnet-svcutil没有正常restore，以下是一些建议：
1. 查看nuget source的配置是否正常， 在VS中查看： Tools->Nuget Package Manager-> Package Manager Settings, 找到 Package Sources， 我的本机包含了：https://api.nuget.org/v3/index.json
2. 卸载并重装.net core sdk, 或者卸载并重装VS
3. 在添加服务引用失败后，查找 %localappdata%\Temp\WCFConnectedService文件夹，压缩后上传到这里以供进一步调查

**Comment by StephenBonikowsky** [comment]
@xiongze666 I hope the additional assistance provided by @imcarolwang resolved your issue. As this is most likely a local environment issue there isn't anything else we can do.
