### ISSUE TITLE
dotnet-svcutil 2.0.0, incorrect reference generation

### ISSUE THREAD

**Issue by yahorsi** [dotnet/wcf#3717]
Hi Guys, 

dotnet-svcutil produces code that fails to compile
Please have a look to the attached WSDL.

[GETTICKETLISTService.zip](https://github.com/dotnet/wcf/files/3344881/GETTICKETLISTService.zip)

The tool invoked using the following command line:
dotnet-svcutil WSDL/GETTICKETLISTService.wsdl    --namespace *,EDW.Targenio.API.Contracts --outputDir Contracts --outputFile TicketListService.cs

Thanks!

**Comment by StephenBonikowsky** [comment]
@imcarolwang Could you have your team test this and provide additional info on what the compilation errors are.

Thanks.

**Comment by imcarolwang** [comment]
@StephenBonikowsky , below is what I found:

It failed to compile because the tool generate cs file containing enclosed DataContract type of the same name in class named TICKETLIST_OTType, the error: 

>'TICKETLIST_OTType': member names cannot be the same as their enclosing type.

Use the given wsdl file, the desktop version tool svcutil.exe generate proxy file with the same problem, so it's not issue specifically in .net core version of the tool dotnet-svcutil.

The corresponding wsdl content led to the problem lies in:
 ```
<xsd:complexType name="TICKETLIST_OTType">
        <xsd:sequence>
          <xsd:element name="TICKETLIST_OT">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="TICKETLIST"> ... </xsd:element>
                <xsd:element name="ERRORMESSAGE"> ... </xsd:element>
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element>
        </xsd:sequence>
  </xsd:complexType>
```

It seems the **TICKETLIST_OTType** and **TICKETLIST_OT** above generate two same DataContract class name "TICKETLIST_OTType" with one nested in the other. I tried to create similar type construction in service but fail to repro the problem as in my "repro" the nested DataContract name without "Type" suffix(compare with the container type) doesn't generate at all on client when running "Microsoft Web Service Reference Provider" on a .net Core app.

**Comment by mconnew** [comment]
@yahorsi, could you make the following change to the wsdl and see if it works? You should be free to change the name of any complex type definition as it's name should only be used for defining the schema type. The thing which gets expressed in XML is the element name.

Line 28 change:
`              <xsd:element name="TICKETLIST" type="tns:TICKETLIST_OTType"/>`
to
`              <xsd:element name="TICKETLIST" type="tns:TICKETLIST_OTComplexType"/>`

and line 32 change:
`      <xsd:complexType name="TICKETLIST_OTComplexType">`
to
`      <xsd:complexType name="TICKETLIST_OTComplexType">`

**Comment by mconnew** [comment]
For triage purposes, this issue reproduces on .NET Framework so isn't a regression.

**Comment by StephenBonikowsky** [comment]
@yahorsi Let us know if you need any additional help.
