### ISSUE TITLE
Bridge should be able to return raw data on a GET request for Resource

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#373]
Currently, the Bridge returns all data as a JSON string. In order to support certificate revocation lists being dynamically served by the Bridge, we need to be able to return the raw CRL to the caller, and (optionally) specify a content-type other than `application/json`.

**Comment by roncain** [comment]
WebAPI's forte is content negotiation.  If we need the byte[] as something other than json, we should revisit the Bridge controllers and make them invoke the WebAPI helpers that take MediaTypeFormatters based on requested content type.  We initially bypassed it due to uncertainty of a Json.Net dependency, but I think that can easily be revisited.

**Comment by iamjasonp** [comment]
We don't need to use JSON.NET at the moment based on this change... we will just return raw data. 

This change allows us to return the CRL from the location: http://<bridgemachine>:44283/resource/WcfService.CertificateResources.CertificateRevocationListResource 

#377 allowed addressable resources directly by URI.
