### ISSUE TITLE
System.ServiceModels.Primitives.dll has wrong public key token for uap10.0.15138

### ISSUE THREAD

**Issue by danielleiszen** [dotnet/wcf#3743]
Windows 10, 10.0.18362
VS 2019

An UWP project references a .NETStandard 2.0 project that has a dependency of nuget package System.ServiceModel.Primitives 4.5.3 Assembly Version=4.5.0.3, PublicKeyToken=**b03f5f7f11d50a3a**

When I define an instance from that package in the UWP project, for example:

private OperationContext cotnext;

and go to the definition of that class, I get to the following source:
System.ServiceModel.Primitives, Version=4.2.1.1, PublicKeyToken=**cc7b13ffcd2ddd51**
// C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.netcore.universalwindowsplatform\6.2.8\ref\uap10.0.15138\System.ServiceModel.Primitives.dll

The two public key tokens do not match, therefore binding redirects cannot be used to solve the problem. Since deployment of the UWP project  happens to check the dependencies neither I could resolve the assembly during runtime, could I?

Anyways I get a compilation error that requests the nuget package to be referenced, however that obviously does not solve the problem.

Please,  let me know how to fix this. Thx

**Comment by danielleiszen** [comment]
I've created a smal repo that reproduces the problem...
https://github.com/danielleiszen/servicemodeldiscrepancy

Is there any workaround? I am stuck with it.

**Comment by StephenBonikowsky** [comment]
@danielleiszen 
The correct token is "b03f5f7f11d50a3a", there was a point about a year ago where our packages got built using the incorrect token "cc7b13ffcd2ddd51". Those bad packages made it into a couple preview releases and were fixed. #2972 #2791 

I just confirmed that this issue with the UWP package was fixed in the Microsoft.NETCore.UniversalWindowsPlatform with version 6.2.0-preview1-26926-04 

However I just checked the latest release 6.2.8 and it pulls in assembly version 4.2.1.1 of S.SM.Primitives which is using the wrong token, I will follow-up on this and try to figure how it reverted back.

In the meantime can you try using the preview version?

**Comment by StephenBonikowsky** [comment]
This will be getting fixed in the 6.2.9 release of the UWP package.

**Comment by StephenBonikowsky** [comment]
Clarification...

6.2.8 has the correct WCF runtime assemblies. it's just the reference assemblies that are incorrect and which are getting fixed.

**Comment by StephenBonikowsky** [comment]
I will update this issue with the release info of the UWP package with the fix once it is known.

**Comment by StephenBonikowsky** [comment]
The fix will be part of Microsoft.NETCore.UniversalWindowsPlatform version 6.2.9, not sure when it will be released.

**Comment by StephenBonikowsky** [comment]
Still haven't seen the 6.2.9 package on NuGet, trying to find out when it will be released.

**Comment by MattWhilden** [comment]
6.2.9 is now available on Nuget. Certainly let us know how it goes.

Release notes: https://github.com/microsoft/dotnet/tree/master/releases/UWP/net-native2.2

**Comment by StephenBonikowsky** [comment]
Awesome, thank you!
https://www.nuget.org/packages/Microsoft.NETCore.UniversalWindowsPlatform/6.2.9
