### ISSUE TITLE
.net core Soap server Response

### ISSUE THREAD

**Issue by amira133** [dotnet/wcf#3757]
I used `.net core 2.2` to response a sample Soap request like this :

    <?xml version="1.0" encoding="utf-8"?>
    <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">      
      <soap:Header>
        <UserCredentials xmlns="http://tempuri.org/">
          <userName>string</userName>
          <password>string</password>
        </UserCredentials>
      </soap:Header>
      <soap:Body>
        <GetSub xmlns="http://tempuri.org/">
          <value>10</value>
        </GetSub>
      </soap:Body>
    </soap:Envelope>
but I don't know how to get `userName` , `password`.

I search a lot but not found a clearly solution ,So Can Some one help me?!

**Notice:** 
I can't edit my request model !!

**Comment by StephenBonikowsky** [comment]
@amira133 
Could you explain a little more clearly what you are trying to do, what is your scenario.
Please explain what you are trying to do on the client side versus the server side.
It's also helpful if you have some type of repro that we can look at with example code.

**Comment by amira133** [comment]
my client send this soap request. Now I want to get `userName` and `password` of his request in `soap:Header` to authenticate him, But I can't find any solution to get them in .net core.

`public class CalculatorService : ICalculatorService
    {
        public double GetSub(int x) => //do something;
    }

    [ServiceContract]
    public interface ICalculatorService
    {
        [OperationContract] double GetSub(int x);
        
    }`

**Comment by StephenBonikowsky** [comment]
So it looks like you are asking how to setup your WCF service. This repo is client side WCF only.

The WCF server side repo is here: https://github.com/CoreWCF/CoreWCF

Based on the class name in your example code it looks like you are using one of the Samples provided with the full framework which is good. I believe that to use the CoreWCF repo there will be namespace changes to your server code but should otherwise have the same functionality.
