### ISSUE TITLE
Question: NETCOREAPP3.0\SVCUTILBOOTSTRAPPER.EXE blocked by group policy

### ISSUE THREAD

**Issue by fepettersen** [dotnet/wcf#3819]
I have a few Connected Services in my project, one of which will not update because svcutilbootstrapper.exe is blocked by group policy. If I add "targetFramework": "netstandard2.0" to the "ExtendedData" portion of the ConnectedService.json, however, I am able to update the service. Is there a reason for this? 
The group policy allows .exe files signed by Microsoft, but I cannot find svcutilbootstrapper.exe anywhere, so I cant check the signature. Where is this file located?

**Comment by dasetser** [comment]
Thanks for reporting this. This is caused because of a difference in behavior working with .NET Core 3 projects compared to 2.0. Svcutilbootstrapper is a dynamically created project that dotnet-svcutil creates, builds, and runs in order to reuse types in referenced assemblies. 

In .NET Core 3.0 the way we create and build the project generates Svcutilbootstrapper.exe instead of the .NET Core 2.0 behavior that builds Svcutilbootstrapper.dll (which is run by calling `dotnet Svcutilbootstrapper.dll`). 

We'll look into investigating if we can fix this in a future release, and for now you can work around this by either disabling the "Reuse types in referenced assemblies" checkbox or using the workaround you already found of changing the target framework to 2.0.

**Comment by imcarolwang** [comment]
Can you please try out the latest Visual Studio preview release which could be downloaded from https://visualstudio.microsoft.com/vs/preview/ ? Let us know if you can still reproduce the issue on the upgraded build.

**Comment by HongGit** [comment]
closing since no response.

Feel free to reactivate if issue still persists after trying @imcarolwang suggestion above.
