### ISSUE TITLE
Support for WsHttpBinding

### ISSUE THREAD

**Issue by GRS-Leedo** [dotnet/wcf#3824]
Is there a plan to add support for WsHttpBinding?  I did see the old post from 2 years ago that simply stated that it was not supported, but I am curious to know if there are plans to add support in an upcoming release?

Thank you.

**Comment by StephenBonikowsky** [comment]
@GRS-Leedo Support for WsHttpBinding is being released with our 3.0 packages, you can already find preview releases on NuGet.
https://www.nuget.org/packages/System.ServiceModel.Security/4.6.0-preview8.final

Please note that the preview packages have this issue which will be fixed with preview9.
https://github.com/dotnet/wcf/pull/3830

Also, not all features are supported, try using it with your scenario and let us know if there is a specific area for which additional support is needed for your scenario.

**Comment by GRS-Leedo** [comment]
Awesome, thanks!

[cid:image005.png@01CCFDFB.153168C0]<http://www.leedo.com/>
Glen Swanson | Software Developer
10707 Corporate Drive, Suite 250 | Stafford, TX 77477
T 281.201.0900 ext:1005
Follow us on Twitter<https://twitter.com/LeedoCabinetry> | Like us on Facebook<https://www.facebook.com/LeedoCabinetry>

**Comment by Ettores88** [comment]
Sorry for the trivial question. Can we also use this library to implement WS-Security on SOAP request?
We need to implement the same transformation of the soap message as SoapUI, but we couldn't find anything on the web.
