### ISSUE TITLE
Adding dependicies using svcutil

### ISSUE THREAD

**Issue by Grandiada** [dotnet/wcf#3893]
I try to add dependicies with the help of svcutil
and i get file
![image](https://user-images.githubusercontent.com/20691820/64613101-02854680-d3de-11e9-8716-99e2fef255d1.png)
with next content:
![image](https://user-images.githubusercontent.com/20691820/64613431-ca323800-d3de-11e9-98b0-aa35711a28e1.png)

I want to configure this files for auto update of a lot of references
Where i can find any not default file configuration or configuration rules which form it?
Perfect way i type all references urls in some file and svcutil update them accordingly.
And i need to change services ports in configs files according to environment variables.
Hope for your help or some advices with my problems
thx

**Comment by dasetser** [comment]
@Grandiada The properties in this file are used by dotnet-svcutil for the update functionality, and generally correspond to a command line parameter that is passed to the tool to run the same command that was originally used to generate the proxy file. Since this is an implementation detail of the tool there is no documentation about the values that are stored in this file, and the format could change in the future.

If you want to update many references automatically I'd suggest creating a script that runs dotnet-svcutil with the command line parameters for your desired service.
