### ISSUE TITLE
Constructor issue in reference class generated from Microsoft WCF Web Service Reference Provider Tool

### ISSUE THREAD

**Issue by WilkoSki** [dotnet/wcf#3914]
I'm using the Microsoft WCF Web Service Reference Provider Tool bundled (2.0.1-preview-30514-0828) with VS2019 (16.2.5).  The project is a .NET472 project.

The Microsoft WCF Web Service Reference Provider Tool fails to generate constructors within the reference class which are compatible with previous versions of Visual Studio e.g. VS2015, VS2017 or provide overloads for all constructors supported by System.ServiceModel.ClientBase<TChannel>.

For example the following constructor aren't publicly exposed in the reference class:
protected ClientBase(string endpointConfigurationName);
protected ClientBase(string endpointConfigurationName, string remoteAddress);
protected ClientBase(string endpointConfigurationName, EndpointAddress remoteAddress);

The reference file previously generated via an earlier VS version, uses a binding definition within the app/web.config file, the name of the binding definition to use is passed into the constructor of the WS reference.

I cannot provide the WSDL file here as its provided under commercial agreement and subject to NDA.

However, where the WSDL includes the following:

```
<wsdl:service name="CompanyExternalService">
      <wsdl:port binding="impl:CompanyAPI" name="company">
         <wsdlsoap:address location="https://services.company.com/ws"/>
      </wsdl:port>
</wsdl:service>
```

Then the reference class generated by WCF Web Service Reference Provider Tool will contain a public constructor which takes an enum value for an EndpointConfiguration enum which it also generates (containing a single value).  

e.g.

```
public enum EndpointConfiguration
{
   company,
}

public CompanyAPIClient(EndpointConfiguration endpointConfiguration):
   base(CompanyAPIClient.GetBindingForEndpoint(endpointConfiguration),
   CompanyAPIClient.GetEndpointAddress(endpointConfiguration))
{
    this.Endpoint.Name = endpointConfiguration.ToString();
    ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
}
```

Its just all a bit messy.

Interestingly SVCUTIL.EXE ran against the same WSDL generates a reference that is compatible with previous versions of VS.

**Comment by WilkoSki** [comment]
Just an additional point, the tool generates a partial static method ConfigureEndpoint.  It seems the intention of this is to allow an overriding of the default configuration within code.

As its a static method it makes it awkward to cleanly utilise dependency injection to set alternative/custom configuration e.g. use a sandbox environment, set max received message size, custom header content etc.

Wouldn't the ConfigureEndpoint method be better as a virtual method?

A sandbox environment is one of our use cases, having the reference class bind straight to the endpoint as defined in the WSDL isn't desired.  Perhaps a set of advanced options in the tool should be considered to control the constructor generation and default endpoint and binding configuration.

**Comment by dasetser** [comment]
@WilkoSki This tool is designed for .NET Core client projects, which is why these differences exist. Since you are using this for a .NET Framework 4.7.2 project I would suggest you continue to use the Add Service Reference tool, which is still the preferred tool for full framework clients.

These differences in the generated class exist because .NET Core does not support config files. Instead of having the single config file that defines the configuration for your client it creates a ConfigureEndpoint method that includes what previous tools would normally put in the config files, and makes it partial to allow you to customize it without creating problems when you update the reference. 

However, since your client is a .NET Framework project I would suggest using Add Service Reference, as it will give you the client generation you're used to, and not limit your client to only things supported by WCF on .NET Core.

**Comment by WilkoSki** [comment]
@davster the differences due to .NET Core make sense, we recently migrated projects to target .NET standard 2.0 as opposed to 4.7.2 which explains why the Add Service Reference option is unavailable.

However in the generated code I personally feel that ConfigureEndpoint would be better as a virtual method as opposed to a static method.  The generated service class is already partial  which would still allow overriding of the default behaviour and preserve changes should the reference be regenerated.

Consider the use of DI to inject configuration etc.

**Comment by dasetser** [comment]
Thanks for the feedback. I can see why having this be a static method could make a DI scenario more awkward than if it was virtual, but I think with the class and method being partial it should still give you enough to hook into to let you configure what you need.

If we changed the way we generated this it would be a breaking change for anyone using the current approach who updates their proxy. We would rather avoid adding a setting to change this because we would like to keep one consistent way to configure the endpoint, so I'm going to mark this as closed. Let us know if your scenario that was working on .NET Framework is blocked by this approach though and we can look into what we can do to help.

**Comment by RealHabix** [comment]
I understand that removing static from ConfigureEndpoint would be a breaking change.. but can't we get a cli switch for this?
