### ISSUE TITLE
svcutil for dotnet core 3.0 generates ArrayOfXElement instead of the data contract

### ISSUE THREAD

**Issue by ibruynin** [dotnet/wcf#3932]
Please refer to https://developercommunity.visualstudio.com/content/problem/749409/svcutil-for-dotnet-core-30-generates-arrayofxeleme.html

FYI // I'm not entirely sure where to log the issue exactly.
If this one is not *the* place, feel free to close this issue immediately.

**Comment by StephenBonikowsky** [comment]
@dasetser could you take a look at this.
@mconnew thinks you may have already made this change?

**Comment by dasetser** [comment]
This is the same root cause as #3712, so I'm going to close this issue so we're only tracking it in one place. I added a new comment on that issue noting we had another report of it and adding my findings from the extra investigation I did based on your developer community report. Feel free to add any additional information you want in a comment on that issue.
