### ISSUE TITLE
Spaces in soapAction get HTML encoded and break WCF service client

### ISSUE THREAD

**Issue by bahaabeih** [dotnet/wcf#3966]
I have switched a web service client in net47 to a WCF client in netstandard and face the following problem:
Details here:
https://stackoverflow.com/questions/58358737/spaces-in-soapaction-get-html-encoded-and-break-wcf-service-client

**Comment by StephenBonikowsky** [comment]
@bahaabeih Thanks for reporting the issue, we are investigating.

**Comment by bahaabeih** [comment]
Any updates on this issue?
Services with such WSDL files are out of control of the consumer. Clients generated this way are simply unusable to hinder migration to netstandard.

**Comment by StephenBonikowsky** [comment]
@bahaabeih we've had a number of tooling issues come in recently and are working through them as quickly as we can.

@dasetser is there any update on this issue yet?

**Comment by dasetser** [comment]
@bahaabeih It looks like we're generating the same code as we do with svcutil for .NET Framework, so this does not look like something specific to .NET Core. It's just a difference between WCF and the Web Services client you were using previously. Unfortunately, it looks to me like WCF is doing the correct thing and it's likely that the service is specifying the wsdl incorrectly. My guess is that the Web Services client was ignoring the spaces, but WCF is including it. Since space characters are valid in urls (although they should be encoded) it's correct for us to handle them.

The soap action's url contains space characters as part of it. When we generate the client we generate it with the space characters, and at runtime WCF makes the call with the soapaction with the same number of (encoded) space characters, which is what the wsdl is saying it should do. 

I would suggest doing something similar to the workaround suggested in the StackOverflow thread. Download the wsdl file and fixup the soapactions to remove the whitespace, and then run in through the tool and see if it works as expected. If that works then it's a problem of the service not matching what the wsdl specifies.

If my guess is incorrect and we're not handling the space correctly and the Web Services client is, then let us know and we can reopen this issue and look into a fix. For now I'm marking this as closed since it looks like we're doing the correct thing.
