### ISSUE TITLE
WCF Web Service Reference Provider: Cannot generate from https://outlook.office365.com/EWS/Services.wsdl

### ISSUE THREAD

**Issue by MartinRobins** [dotnet/wcf#3971]
**Describe the bug**
I am unable to generate compilable code for accessing Office 365 EWS web services within any .NET Core project.

**To Reproduce**
1. Create a .NET Core project (I have tried Class Library and Function App)
2. Add a connected service
3. Select "Microsoft WCF Web Service Reference Provider"
4. Use the URI "https://outlook.office365.com/EWS/Services.wsdl", click "Go"
5. When prompted, enter a valid O365 username/password combination (this will be required 3 times)
6. Enter a namespace name (I chose "Exchange")
7. Click Finish
8. Click Close

**Expected behavior**
The service should be imported and the necessary code generated to allow the use of that service as would be the case when targeting the .NET full framework.

**Actual behaviour**
As you will see from the screen shots, the wizard completes with warnings. Code is generated but does not compile (System.IO.FileNotFoundException: System.Private.ServiceModel, Error generating functions metadata, netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets	41).

**Screenshots**
![ExchangeImport1](https://user-images.githubusercontent.com/2203265/67035383-77504c80-f111-11e9-8aec-2fe6380c38fb.png)
![ExchangeImport2](https://user-images.githubusercontent.com/2203265/67035793-3e64a780-f112-11e9-812e-ff86780d1cea.png)
![ExchangeImport3](https://user-images.githubusercontent.com/2203265/67035376-761f1f80-f111-11e9-9146-a7c6f0e59c22.png)
![ExchangeImport4](https://user-images.githubusercontent.com/2203265/67035378-76b7b600-f111-11e9-9fde-5e2ad0cfc5d9.png)
![ExchangeImport5](https://user-images.githubusercontent.com/2203265/67035380-76b7b600-f111-11e9-859b-2559b08c84cb.png)
![ExchangeImport6](https://user-images.githubusercontent.com/2203265/67035382-77504c80-f111-11e9-82c6-40ff3a02be74.png)
![ExchangeImport7](https://user-images.githubusercontent.com/2203265/67035532-c0080580-f111-11e9-8778-d4770b1837d9.png)
![ExchangeImport8](https://user-images.githubusercontent.com/2203265/67035626-ecbc1d00-f111-11e9-8fc4-8d2c1f901094.png)

** Additional **

- Visual Studio 16.3.5 on Windows 10 Professional.
- I do not want to use the nuget "Microsoft.Exchange.WebServices" as I specifically require push notifications (StreamNotifications are of no help).

**Comment by dasetser** [comment]
@MartinRobins What problem were you encountering when using the tool on a Class Library project? If I use a Class Library project I don't see any build errors afterwards.

For the build problems after using the tool on Azure Functions, try updating the System.ServiceModel.* packages to the latest (4.6) and rebuilding. That fixed the problem for me, and we have a change in an upcoming version of the tool that will add the correct version for you.

As far as the warning goes, I believe it is correct and shouldn't stop you from using the client it generates. It looks like the wsdl does not contain any <wsdl:service> or <wsdl:port> nodes, so it doesn't define any endpoints. You'll have to define the endpoint yourself in your client code because of this, but I believe the part of the proxy it does generate should be usable.

**Comment by dasetser** [comment]
If you're still running into problems with this let us know the answers to the above questions and we can reopen this issue.
