### ISSUE TITLE
Fix ServiceRestart_Throws_CommunicationException test

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#398]
The ServiceRestart_Throws_CommunicationException test is incorrect in several ways and should be corrected.  Main observable issues are:
1. It fails running multi-machine (either Windows or Linux)
2. It reports only the unexpected exception message and does not include the stack trace.

Problems to fix are:
1. It uses the HttpBaseAddress_Basic endpoint, which means it is talking to a ServiceHost used for other tests.  It should have a dedicated IResource endpoint on the Bridge that exists for no other purpose but this test.
2. It does some string replacement of the original URI thinking it contains "[HOST]" which is an incorrect assumption.  I'm not sure what the test is attempting to do but it should not need to alter the URL to the endpoint dedicated to a service restart
3. It uses the old style exception catching and reporting (rather than Assert.Throws()) and fails to capture the stack trace.

Note that this test should also technically inform the ResourceController it no longer has the resource for this endpoint before it closes the service host, otherwise the ResourceController will believe it still exists and continue to try to use a non-existent service host.

**Comment by zhenlan** [comment]
@StephenBonikowsky as a short term plan, please disable this test for now. For the long run, we will fix this test to work with bridge.

**Comment by StephenBonikowsky** [comment]
Test disabled by PR #428
I guess we keep this open until we actually fix it?

**Comment by iamjasonp** [comment]
I'm kind of curious about why we should keep this test. 

If the server restarts, shouldn't this be treated the same as a connection drop/abort?

**Comment by roncain** [comment]
IMHO, this test is not critical.  Too many variables for an edge case. I think proving only that we don't hang is enough.

**Comment by StephenBonikowsky** [comment]
Clarifying a few things as this was opened a long time ago...
1. It only uses HttpBaseAddress_Basic endpoint for the first part of the test to trigger the service to create a new ServiceHost and get it up and running. The operation will then return the endpoint address for this new ServiceHost.
2. The string replacement of [HOST] is valid, the ServiceHost that is created just uses 'localhost' as the host name, the client side will need the actual host name so 'localhost' is replaced with [HOST] in the string that is returned to the test case. The test case then uses HttpBaseAddress_Basic only for purposes of creating a UriBuilder from which it extracts the actual host name of the service and replaces [HOST] with it.
3. Yes, updating the test to use Asserts instead of a StringBuilder.

So yes this test is valid and it really just validates that if the Service dies (or restarts) for some reason in the middle of an operation the client won't hang but get a CommunicationException.

**Comment by StephenBonikowsky** [comment]
Regarding the issue where it fails on multi-machine runs, not sure why it should, but quite a bit has changes in the test infrastructure since this issue was first opened.
PR is coming soon and we will see what happens with CI.
