### ISSUE TITLE
Porting from .NET Framework, missing StreamUpgradeBindingElement, StreamUpgradeProvider?

### ISSUE THREAD

**Issue by mayerj** [dotnet/wcf#4079]
I am attempting to port our client side WCF code from full framework to .NET Standard 2.0.  We have some custom binding upgrades used to interact with the SSL stream, and the extension points for those appear to be missing.

As an example, the Framework Ssl StreamUpgradeAcceptor reads from the underlying stream without a timeout during the upgrade.  This was causing WCF to not respect our OpenTimeout during the initial connection attempt.  As a workaround we implemented a custom upgrade acceptor that set the stream timeout, then deferred to the SSL one.

Add references to:
System.ServiceModel.Duplex, System.ServiceModel.NetTcp, System.ServiceModel.Security, notice types missing.  (They appear to be in System.Private.ServiceModel, which I guess suggests they are no longer intended to be subclassed).

I'm not sure what to expect here.  My goal was to lower some code we had from .NET Framework to .NET Standard (such that I didn't need 2 copies of it).  That (currently) requires the code above.

**Comment by StephenBonikowsky** [comment]
@mayerj In the move to Core that API wasn't added to the public contract but there is no inherent reason why we can't do that. What kind of timeline are you looking at for your porting work?

Adding @mconnew

**Comment by brentafis** [comment]
I too would love some porting guidance here.  This may be better as a separate issue but I'm working on porting several client-side services to netcore.  All of these clients happen to use NetNamedPipeBinding which is currently in the future milestone.  That's unfortunate but I decided to implement it myself with the expectation I'd be able to just plug into the existing classes and derive/implement my own ClientFactory using both this repository and the netframework reference source as a guide.

The problem I keep running into is that there are several layers of classes/methods I'd love to be able to make use of that are marked as internal.  For example, ConnectionOrientedTransportChannelFactory, ConnectionPool, BufferedConnectionInitiator just to name a few. 

My question is essentially what is the recommendation here?  I understand the desire to both keep the implementation details private (which makes them easier to change/tweak) and keep the netcore version true to the netframework version (which maintains a very similar API surface) but on the flip side if I want to extend the framework and implement bindings that aren't currently/ever going to be part of the netcore version then ideally those classes would be available for my consumption.  I can likely accomplish my goal but if I want to ensure a proper and good communication with server side I'm going to likely be copying and pasting a whole lot of source from this repo to do so.

Thanks

**Comment by StephenBonikowsky** [comment]
@brentafis I am working on a doc specifically to answer the questions that you (and many others) have asked regarding the migration story for WCF from full framework to core. It is one of my higher priority tasks and I am actively working on it.

In the mean time here is some info I hope will help.

Of biggest impact is that WCF on the full framework is a mix of server and client side functionality. It was decided early on that WCF Core would not include any server side functionality. WCF was not originally designed to think of these as two separate things so there is a lot of shared and otherwise intermingled server/client code. So separating and moving only client side stuff to Core has been challenging. In general anything that is client side we would like to support in Core and that is an ongoing effort.

> there are several layers of classes/methods I'd love to be able to make use of that are marked as internal

We aren't constrained from adding to the API surface area but we do want to be careful in doing that. Although a lot of the implementation for various features made it to Core, the features they are part of were not initially part of the public surface area. Now as we look to light-up some of these features none of them "just work", too many things changed and additional work has to be done to get them to work end-to-end. So even if it looks like some of the classes/methods are there, other things they need deeper in the stack are missing or need to be fixed.

#### Regarding what features we can be expected to add support for.
We would like to support every WCF client side feature but a number of features depend on functionality below WCF in other areas of .NET Core. An example of that is Message security, we would like to support it but there are significant missing components in Core at this point.

#### Regarding the timing of adding support for new features.
As part of the doc we are working on we will have a list of features that for various reasons cannot be supported and a list of the features we plan to add support for and ideally some indication on timing and priority.

A really useful tool for determining where any given API is supported across all .NET platforms is https://apisof.net/

**Comment by StephenBonikowsky** [comment]
Also, `NetNamedPipeBinding `is something we want to get added sooner rather than later, we are just trying to find the time to squeeze it in.

**Comment by brentafis** [comment]
@StephenBonikowsky thank you for the detailed reply. It really does help to know things are coming and I'm sure the document you are working on will help even further.

> Also, NetNamedPipeBinding is something we want to get added sooner rather than later, we are just trying to find the time to squeeze it in.

Interestingly, I was able to get a version of this working using this repo as well as the netframework reference source as a guide. The result is still a bit rough in some places but I'd be happy to discuss options for integrating it back in.

**Comment by StephenBonikowsky** [comment]
@mconnew I believe you mentioned there was not a whole lot of work needed to get NamedPipes working in Core. I'd like to discuss having @brentafis submit a PR for enabling this feature in Core if he is willing.

**Comment by StephenBonikowsky** [comment]
@brentafis We discussed this today and because we have higher priority features and fixes it is not likely that we could add NetNamedPipeBinding in the near future.

However we are happy to work with the community to add content we want to see supported in WCF Core.

In order to add support for NetNamedPipeBinding in WCF Core we require that all P/Invoke code be removed and replaced with the correlating managed code. While this feature can only work on Windows we don't want to add complexity to our cross-platform building and packaging story.

The first step would be to make sure that every P/Invoke can be replaced. The [PipeSharedMemory ](http://index/?leftProject=System.ServiceModel&leftSymbol=c2rqmmy2mpfg&file=System%5CServiceModel%5CChannels%5CPipeConnection.cs&line=2607)P/Invoke is one of the first ones to check.

If you are interested in this please follow-up with us on our main NetNamedPipe issue tracking the addition of that feature. #2535

**Comment by StephenBonikowsky** [comment]
@mayerj If you still need `StreamUpgradeBindingElement `and `StreamUpgradeProvider` added to the public contract in WCF Core and you would like us to look into adding them please let us know what kind of time frame you are working with.
