### ISSUE TITLE
"System.ServiceModel.EndpointIdentity.CreateUpnIdentity" method for .net standard?

### ISSUE THREAD

**Issue by Adam-Tg** [dotnet/wcf#4089]
Hello, unfortunately the method "System.ServiceModel.EndpointIdentity.CreateUpnIdentity" does not exist for .net standard 2.0. I need this method for creating a EndpointAddress:

```csharp
EndpointAddress myEndpoint = new EndpointAddress(new Uri(wcfEndpoint.Endpoint), EndpointIdentity.CreateUpnIdentity(wcfEndpoint.Identity));
```

What can I do to make this also work on .net standard?

**Comment by mconnew** [comment]
Try this:
```c#
EndpointAddress myEndpoint = new EndpointAddress(new Uri(wcfEndpoint.Endpoint), new UpnEndpointIdentity(wcfEndpoint.Identity));
```

**Comment by Adam-Tg** [comment]
I also had the feeling that I could use this, but I was not sure.
So if I use this, will there be any side effects that I should know about?

**Comment by mconnew** [comment]
No side effects. You can see the code of the CreateUpnIdentity static method [here](https://github.com/microsoft/referencesource/blob/master/System.ServiceModel/System/ServiceModel/EndpointIdentity.cs#L106). I'll paste it here for convenience:
```c#
        public static EndpointIdentity CreateUpnIdentity(string upnName)
        {
            return new UpnEndpointIdentity(upnName);
        }
```
So instead of calling a static method which just constructs an object for you and returns it, you can directly construct the object and you get identical results.

**Comment by mconnew** [comment]
As an aside, part of some of the pain and difficulty people have with using WCF is there's about 20 ways to do the exact same thing. I'm trying to minimize that with the .NET Core implementation as much as is reasonable which sometimes means small but compatible code changes need to be done.

**Comment by DasOhmoff** [comment]
Ah, I see, ok thank you :)

**Comment by StephenBonikowsky** [comment]
Let us know if you have any other questions.
