### ISSUE TITLE
WCF Web Service Reference Provider Tool - Naming of Methods

### ISSUE THREAD

**Issue by RealDotNetDave** [dotnet/wcf#4096]
It seems the proxy code that this tool generates dose not use proper .NET naming standards. For example, these methods:

```
getUserInfo()
login()
```

Should really be:
```
GetUserInfo()
Login()
```

A few of the methods do follow these well-established naming standards, but the majority do not. Also, these methods should have proper XML comments that include what exceptions the methods throw (very important).

**Comment by StephenBonikowsky** [comment]
@RealDotNetDave  The tool doesn't own the casing it just gets it from the WSDL.
Adding XML comments for exceptions would be nice, it is a feature request though which we can consider for a future release.

**Comment by RealDotNetDave** [comment]
Got it. Thanks. Xml comments are important since I don't know what exception types will be thrown when I'm coding.

**Comment by Davilink** [comment]
@StephenBonikowsky Could it a be a feature request ?

**Comment by StephenBonikowsky** [comment]
Adding @HongGit and @mconnew since they own this.

**Comment by mconnew** [comment]
@RealDotNetDave, the only exception types that can be thrown by an operation that's driven by the response from the service is either [FaultException](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.faultexception?view=dotnet-plat-ext-3.1) or [FaultException\<TDetail\>](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.faultexception-1?view=dotnet-plat-ext-3.1) where the TDetail type is attributed on the interface using FaultContractAttribute. If the service throws an unrecognized exception (not attributed using FaultContractAttribute), then you get the non-generic exception FaultException. So there's no need to add Xml comments as the operation already has an attribute on it. Here's an example:
```c#
  [ServiceContract]
  public interface ISampleService
  {
      [OperationContract]
      [FaultContractAttribute(typeof(GreetingFault))]
      string SampleMethod(string msg);
  }
```
In this case calling SampleMethod can throw FaultException\<GreetingFault\> or if the service throws an unexpected exception, you would get a FaultException. All other exceptions are internal to WCF related to problems with making the call, e.g. TimeoutException, ProtocolException, EndpointNotFoundException etc. Other than TimeoutException, all the WCF internal exceptions derive from CommunicationException.

**Comment by Davilink** [comment]
@mconnew I was more talking about the naming convention (for Object, Properties, Method). Maybe i should open a separate issue for that.

**Comment by mconnew** [comment]
@Davilink, my prior comment was aimed at someone else's comment about wanting Xml documentation generated listing the exceptions that could be thrown. As for the naming convention, Stephen was correct in saying we just pull it from the WSDL. Any attempt to do something different from what's in the WSDL will be wrong in some set of cases. For example if the WSDL has an operation called `myoperation` then capitalizing it to `Myoperation` would by wrong.

**Comment by Davilink** [comment]
I thought that the XML attribute allowed to specified the name of the properties, the Object Name and Method for the  serialiser/deserializer like we can do we JsonProperty attribute.

**Comment by mconnew** [comment]
@Davilink, it does. After the code has been generated, you can modify the code to have the casing that you want as long as you add the attribute property to specify the original name. The problem with modifying the name by default to confirm to some standard such as enforce the first letter to be uppercase is that sometimes that would be the wrong thing to do. So it's better to leave it as "wrong" (which is subjective from person to person) and not modify it as it's wrong because that's what the input had. It's worse to be wrong because you automatically changed something than it is to be wrong because you left it the same as the source schema. In one case, the .NET tooling is wrong, in the other, the source schema is wrong.  
BTW, if you modify the generated code, your modifications will get reverted if you ever update your generated client based on an updated WSDL.

**Comment by Davilink** [comment]
yeah, what i was suggesting is to have an option to change the casing, because like you said, if i change the setting in the generated and i want to update (new method or change in the properties, etc...) at least the use of the same option will automatically generated the code with the same convention.

something like :
--ObjectNamePascalConvention
--PropertiesNamePascalConvention
--MethodNamePascalConvention

or the meta flag
--PascalNameConvention (will be the equivalent of setting the 3 flag at the same time)

dotnet svcutil https://www.example.com?wsdl  --PascalNameConvention [other option or parameters]
