### ISSUE TITLE
Attempting to generate a svc client fails if the project references a nuget package with a name ending in .dll

### ISSUE THREAD

**Issue by ctolkien** [dotnet/wcf#4126]
**Describe the bug**
Attempting to generate a SOAP client via `svcutil` fails if the project references a nuget package with a name ending in `.dll`

**To Reproduce**

Install a package like `DocuSign.eSign.dll` and then attempt to generate a client for this project. You will receive the following error:

`Error: The specified parameter value 'DocuSign.eSign.dll' is not valid. Parameter name: 'packageName'.`

**Expected behavior**

Generate a svc client.

**Screenshots**

![image](https://user-images.githubusercontent.com/515955/72564257-780ca080-3903-11ea-82f2-af05cde3029e.png)

**Comment by StephenBonikowsky** [comment]
@dasetser Could you take a look?

**Comment by dasetser** [comment]
It looks like the tool is assuming it's referencing a dll instead of a package name and throwing an error. We'll look into how we can make this scenario work. For now I would suggest removing that reference temporarily, running the tool, then adding it back. This should impact the generated file unless you need to reuse types from that reference.

**Comment by ctolkien** [comment]
>For now I would suggest removing that reference temporarily

Issue with that is the rest of the project won't build - which is required to run `svcutil`. What we've had to do is split it up into separate projects, and then port/copy files across as needed.
