### ISSUE TITLE
System.PlatformNotSupportedException: Compiling JScript/CSharp scripts is not supported 

### ISSUE THREAD

**Issue by RealDotNetDave** [dotnet/wcf#4128]
This issue was first brought up in 2017: https://github.com/dotnet/wcf/issues/2219. I am still seeing the issue in .NET Core 3.1 going against a huge WSDL file generated in Salesforce. We have tried some of the solutions in the original issue, but so far we have not been able to get around it.

Any ideas? This is causing a work stoppage since we can't log into Salesforce.

**Comment by StephenBonikowsky** [comment]
Based on #2219 and #1274 the conclusion was that it was a legitimate issue but because there was a known workaround and the issue also exists on the full framework we weren't going to fix it in Core.

@RealDotNetDave You said the workaround did not work for you? Could you tell us how your scenario is different from the other's that hit this problem for whom the workaround does work?

Adding @dasetser and @mconnew

**Comment by mstancombe** [comment]
@RealDotNetDave have you tried the workaround from https://github.com/dotnet/wcf/issues/2219#issuecomment-531368768 ?
I also ran into this today, and this workaround resolved it.

**Comment by StephenBonikowsky** [comment]
Feel free to re-open this issue if you have more info for us.
