### ISSUE TITLE
Adding a connected service when there are multiple services in the solution adds the wrong one

### ISSUE THREAD

**Issue by LaughingJohn** [dotnet/wcf#4191]
Hi,

I have a solution with 4 web service in it. When trying to add a service reference in another project in the solution to one of the services, having chosen it from the GUI it adds a reference to a different service to the one I have chosen. I suspect this issue may be in the UI.

To get around this I have to remove 3 of the 4 service projects from the solution, then create my reference and then add them back in again.

It's not the end of the world but it takes a while to figure out what's going on.

Thanks.
LJ

**Comment by HongGit** [comment]
@imcarolwang can you please try to to see if you could repro this issue!

**Comment by imcarolwang** [comment]
@HongGit , this issue could be reproduced on my side.

The repro app: [Issue4191.zip](https://github.com/dotnet/wcf/files/4335976/Issue4191.zip)
The solution contains 4 wcf service projects (Service1,2,3,4) and a console core project as test client. On the client project, run WCF Connected Service Provider tool and choose different discovered service, it always generates proxy for Service4 which is expected behavior.

**Comment by dasetser** [comment]
Interestingly the ConnectedService.json file is saved with the correct service address, but the actual generated file is for the wrong service. So the UI is picking up the selection correctly, but passing the wrong address to dotnet-svcutil when doing the actual generation. We'll look into fixing this in a future release.

For now an easier workaround than removing the other services temporarily is to just update the Service Reference after you generate it. Since the right address is in the ConnectedService.json the update functionality generated the proxy for the correct service.

**Comment by LaughingJohn** [comment]
Updating the reference never works for me for some reason. Firstly I get "No connection could be made because the target machine actively refused it 127.0.0.1:2424".
I have got around this by running up the service in a different instance of VS. However when it regenerated it seemed to ignore the "use types from referenced assemblies" and made up types of it's own. Bit of a pain!

Thanks for looking into the original issue though!

**Comment by imcarolwang** [comment]
The problem described in issue no longer reproduce in the recent release of Visual Studio 2019 - 16.11 Preview3, it could be downloaded from https://visualstudio.microsoft.com/vs/preview/.

**Comment by LaughingJohn** [comment]
Thanks @imcarolwang !
