### ISSUE TITLE
No connection could be made because the target machine actively refused it 127.0.0.1:2424

### ISSUE THREAD

**Issue by LaughingJohn** [dotnet/wcf#4224]
When refreshing my service reference I get "No connection could be made because the target machine actively refused it 127.0.0.1:2424".

The scenario is that I have added a .net standard project (our own implementation of a proxy) to an existing .net solution that contains the service itself and other projects which also reference the service, one is .net 4.5.2 and the other is PCL.

If I attempt to update the .Net Standard service reference first I get the above error. If I do one of the others first and then do the .Net Standard one then it works. I guess doing one of the others "fires up" the service successfully and it's still running, whereas the standard one can't seem to start it for some reason..

**Comment by LaughingJohn** [comment]
P.S VS2019 Preview.

**Comment by dasetser** [comment]
@LaughingJohn Thanks for reporting this. You're getting this message because the service is not running and is expected. As you guessed, if you update a .NET Framework service reference first it detects that the service is in the same solution and hosts it for you automatically before updating. This is due to some integration features that Add Service Reference has that the WCF Connected Service does not have, which makes this a feature request. 

These integration features are missing because WCF on .NET Core is targeting the scenario where you have an existing service you want to reference with a WCF client, where Add Service Reference was created with developing WCF clients and services simultaneously. Because of the target scenarios for the .NET Core tool this kind of integration feature (which can be worked around by manually starting the service before updating) became very low priority, and we're not able to prioritize this over other requests that we're getting.

**Comment by LaughingJohn** [comment]
Thank you! Just out of interest is there an existing feature request I can go add my support to?
