### ISSUE TITLE
WebSockets streaming request/reply scenario failing in System.Net.WebSockets layer

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#424]
The call...
"Task task = _webSocket.SendAsync(new ArraySegment<byte>(Array.Empty<byte>(), 0, 0), _outgoingMessageType, true, timeoutHelper.CancellationToken);"

Located...
"C:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\WebSocketTransportDuplexSessionChannel.cs"

Fails with...
"System.Net.Http.WinHttpException occurred
  HResult=-2147024809
  Message=The parameter is incorrect
  NativeErrorCode=87
  Source=System.Net.WebSockets.Client
  StackTrace:
       at System.Net.WebSockets.WinHttpWebSocket.SendAsync(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)"

The values passed in to "_webSocket.SendAsync" are...
   - new empty ArraySegment of type byte
   - _outgoingMessageType is binary
   - "true"
   - CancellationToken is null

**Comment by mconnew** [comment]
I think this is a bug in the WebSocketClient code. As we're streaming our request, we don't know that we're done until after we have sent all the data. The problem is we've sent every frame with the EOM flag set to false (in other words, not the end of the WebSocket message). We now need to send a zero payload length websocket frame marking the end of the WebSocket message. Apparently WinHTTP doesn't like this.

**Comment by roncain** [comment]
@mconnew does this mean you are actively working on a fix in WebSocketClient code?  Do we need to open a separate issue in CoreFx to track it?

**Comment by mconnew** [comment]
I'll discuss with the NCL team and see what their timeline would be for fixing this. I've checked the WinHTTP api docs and it claims this is a supported scenario, I think the issue is the buffer being passed to WinHTTP should be null instead of a zero length array.
