### ISSUE TITLE
Data Contract object pooling

### ISSUE THREAD

**Issue by epignosisx** [dotnet/wcf#4240]
Hi folks. I've been profiling a .NET Core 3.1 app and it is a consumer of a WCF service that sends large number responses and the profiler is showing many data contract objects allocated to handle the big payload. I was thinking about introducing pooling for these data contract objects, but I was not able to find any information online. This is a HttpBasicBinding client using the XmlSerializer.

I would appreciate if you could tell me if this is possible or provide any other ideas to reduce object allocation for large responses.

**Comment by HongGit** [comment]
@epignosisx thanks for reporting the issue with us!

WCF already pool them, except some cases where custom headers are being used.  If that is the case, could you please give us an example on how it is being used?

**Comment by epignosisx** [comment]
I think we are talking about different object pooling. I’m referring to the DTO classes WCF generates from a WSDL. I doubt those are pooled by WCF since they are returned to the application code (in case of the response) and WCF will not have a way to know when they are no longer referenced in order to reuse them.

My challenge is the service response has very long lists of items with even more nested lists. I’m trying to see if there is some extensibility in the XmlSerializer that would allow me to provide the objects instead of it creating new instances on each service call.

**Comment by HongGit** [comment]
@mconnew can you please comment?

**Comment by mconnew** [comment]
@epignosisx, there is no extensibility for XmlSerializer to call a factory method to create an instance instead of newing one up. If you were using DataContractSerializer, there's a half solution you could do. If you use a surrogate provider, an instance would still be created when deserializing, but then it would get passed to the surrogate provider which can then provide the "real" instance. That first instance would be in gen0 so would be collected really quickly with minimal cost and your instance provided by the surrogate could be a long lived instance that would end up in gen2. It wouldn't stop allocation, but it would prevent objects moving to gen1 and then being expensive to collect.
If you are willing to be more hands on in handling the objects, you could implement an IClientOperationFormatter. In the DeserializeReply method, it hands you a Message object which you can get an XmlReader for the body from. If you are willing to write the code to deserialize the body yourself, you can use your own pooling. This would mean you wouldn't be using XmlSerializer at all and would be handling the deserialization yourself. You could still use an XmlSerializer on inner objects if you wanted. So if you expect a List\<Foo\> and Foo has a property of type Bar, you could deserialize the Bar object using an XmlSerializer while still using your own logic to instantiating the Foo objects.
I'm sorry there's nothing out of the box. With the current implementation of the serializers, adding something like this would be a crazy amount of work as they are implemented by emitting IL code at runtime. So it's not just the case of writing the code, it's writing the code via emitting IL statements equivalent to the code you would write.
I'm going to close this issue as there's nothing we can do in the product and I think I've given you all the possibilities of how you can achieve object pooling.
