### ISSUE TITLE
.Net Core 3.1 ChannelFactory creating proxy service call method exceptions

### ISSUE THREAD

**Issue by 630383257** [dotnet/wcf#4304]
Using wcf in .net core, using ChannelFactory to create proxies.
[example link](https://thecodebuzz.com/consume-wcf-web-services-in-net-core-using-channelfactory/)
the code is similar
```
1. new ChannelFactory<IProxyService>(new BasicHttpBinding(), new EndpointAddress(new Uri("http://address")).CreateChannel();
2. var service= sp.GetService<IProxyService >();
     service.Add(1);
```
When I refer to the .Net Framework package, it runs normally. When I copy the proxy interface code to .Net standard, it can run normally Step 1, when I run to step 2, an exception is thrown: Object reference not set to an instance of an object.

![image](https://user-images.githubusercontent.com/34563003/86106149-cc42c000-baf2-11ea-9445-49965b98eea6.png)

The nuget package references
```
  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Annotations" Version="4.7.0" />
    <PackageReference Include="System.Private.ServiceModel" Version="4.7.0" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="4.7.0" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.7.0" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.7.0" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.7.0" />
    <PackageReference Include="System.ServiceModel.Duplex" Version="4.7.0" />
    <PackageReference Include="Portable.BouncyCastle" Version="1.8.6.7" />
    <PackageReference Include="System.Xml.XmlSerializer" Version="4.3.0" />
  </ItemGroup>
```
How to fix this error?

**Comment by mconnew** [comment]
In the call stack, it's calling ThrowIfFaultUnderstood, which means the server returned a Fault message. If it was a problem with the SOAP parts of the message (action, soap version etc), then you would have had a more specific exception thrown with some helpful text. It looks like a generic fault message was returned by the service. The most likely cause is the service threw an unhandled exception. As this works with a .NET Framework client but not with a .NET Core client, I suspect there's some serialization problem in .NET Core which is causing the service side to get a null where it's not expected and is throwing a NullReferenceException.  
You can verify this is the case by enabling the service side debug behavior to have it send the full exception and callstack details to the client. The default behavior is to return a generic fault as exposing the exception details can help a potential attacker in some cases so don't leave it on in a publicly facing service. Here's an [article](https://docs.microsoft.com/dotnet/api/system.servicemodel.description.servicedebugbehavior?view=netframework-4.8) describing it, but the piece you need to be concerned about in your service config is this:
```xml
    <behaviors>
      <serviceBehaviors>
        <behavior name="metadataAndDebug">
          <serviceDebug includeExceptionDetailInFaults="true" />
        </behavior>
      </serviceBehaviors>
    </behaviors>
```
Make sure your service definition has a matching behavior name (behaviorConfiguration attribute on your service config element).  
Hopefully this will help track down where the problem is. You might need to use [fiddler ](https://www.telerik.com/fiddler) to capture the request for .NET Framework and .NET Core to see the difference between how the same request is serialized. .NET Core removed the ability to serialize some types such as MemoryStream so if you are using one of those types in your contract, you will need to do a workaround. If needed I can help you with the workaround once it's been identified what the problem is.

**Comment by HongGit** [comment]
Feel free to re-open if this is still an issue.

**Comment by 630383257** [comment]
Thanks for the help.
I found the error was caused by the namespace change of the Interface, when I changed the namespace to the same as under .Net Framework, it worked fine!
