### ISSUE TITLE
WCF client is showing fault state after creation in .NET core 3.1 application

### ISSUE THREAD

**Issue by devblaster** [dotnet/wcf#4363]
**Describe the bug**
WCF client is showing "fault" state in project. 

Upon debugging more I found there is one exception in TypeLoader 
**Name={IXXXWebService}, Namespace="http://tempuri.org/", ContractType=error CS0103: The name '_contractType' does not exist in the current context**

In ServiceClient.EndPoint property I am seeing  **error CS0103: The name '_address' does not exist in the current context****

Any idea why this might be happening ?
I am referencing following nuget packages 

![image](https://user-images.githubusercontent.com/8345685/93004736-ca3bab00-f4fe-11ea-8da5-3b0ca5a7a65f.png)

**Comment by HongGit** [comment]
@devblaster could you please share repro project so we could investigate?

**Comment by gmihaescu** [comment]
@devblaster - are you sure that you're not inspecting the WCF client in the debugger?
![image](https://user-images.githubusercontent.com/62328498/100374133-154c6100-300c-11eb-829c-4135316ed868.png)

When doing so the debugger needs to evaluates the properties, some throw and put the channel in Faulted state. 
Quantum mechanics stuff: by looking at the object you alter its state.

**Comment by safayatzisan** [comment]
Any update on this regard? I am facing this as well.

**Comment by skaryshev** [comment]
Same here: Channel is created in faulty state targeting .net5.0. It happens only with WSHttpBinding. BasicHttpBinding works fine.

**Comment by simo-92** [comment]
Any update on this problem? I am facing this as well.

**Comment by mibo32** [comment]
Any updates on this one ? or any  workarounds  ?

**Comment by mconnew** [comment]
WSHttpBinding with Message security isn't supported (which is what's used with the default constructor). We do support TransportWithMessageCredentials, but we don't yet support that with Windows credentials. The issue with "The name '_address' does not exist in the current context" is because of a debugger attribute on the class which wasn't updated when the private field _address used to back the Address property was removed in preference of using an auto property. This issue has been fixed in the upcoming 4.9 release, but has nothing to do with the lack of support for Message security.  

I'm going to close this issue now as the only actionable item has already been fixed.
