### ISSUE TITLE
How can I inject a fake xml server response for unit testing?

### ISSUE THREAD

**Issue by timabell** [dotnet/wcf#4370]
Hi, I hate to raise an issue but I've spent hours trawling the internet to no avail and really hope you can help.

I've [inherited an existing WCF client](https://github.com/SkillsFundingAgency/dfc-coursedirectory/blob/b7f6600f5ccb3313210faec77797dfe9a74e764b/src/Dfc.CourseDirectory.Core/Connected%20Services/UkrlpService/Reference.cs) which I now need to modify, and as such [want to get it under test](https://timwise.co.uk/2020/07/09/approaches-to-refactoring-and-technical-debt/) to avoid regressions.

To get this under test I want to inject a known response from the server (in the form of an xml response) instead of having the service under test connect to the production endpoint. Once I have that I can then validate that the correct values are returned from the generated wcf client.

Is there a hook somewhere I can use with the wcf client to provide the fake xml response?

Thanks.
([also asked on stackoverflow](https://stackoverflow.com/q/63999109/10245))

**Comment by mconnew** [comment]
As long as you aren't running on .NET Framework, you can use the solution I documented [here](https://github.com/dotnet/wcf/issues/3230#issuecomment-431921166). Someone created a blog post explaining things a bit more [here](https://medium.com/trueengineering/realization-of-the-connections-pool-with-wcf-for-net-core-with-usage-of-httpclientfactory-c2cb2676423e). Basically you can replace the HttpMessageHandler with your own dummy one. Or if you follow the link in my comment to the test for this feature, you can see how the request can be optionally intercepted. If you return an HttpResponseMessage, it will skip making the real call and provide your HttpResponseMessage to WCF. If you return null, it will send the HttpRequestMessage which you are might have optionally modified using the real HttpClientHandler.
I'm going to close this issue because that should be everything you need. If you have any follow up questions, re-open the issue so that it gets visibility.
