### ISSUE TITLE
.NET Core 3.1 X509 signature

### ISSUE THREAD

**Issue by gaui** [dotnet/wcf#4380]
I'm having a problem with signing WCF calls with a X509 certificate signature.

The following code works with .NET Framework but it doesn't with .NET Core because `X509SecurityToken` doesn't exist and I can't access the `RequestSoapContext`.

```
SvcService.Service ws = new SvcService.Service();
X509Certificate2 cert = new X509Certificate2("cert.pfx", 
"privatekeypassword");
X509SecurityToken token = new X509SecurityToken(cert);
 ws.RequestSoapContext.Security.Tokens.Add(token);
 ws.RequestSoapContext.Security.Elements.Add(new MessageSignature(token));
 
 DataSet ds = ws.GetItem(2081234);
```

What would be the method to achieve the same in .NET Core? The proxy classes are generated with dotnet-svcutil.

**Comment by gaui** [comment]
Here's a similar issue: https://stackoverflow.com/q/59737636/1053611

If anyone can direct me towards an alternative way to do this, it would be greatly appreciated.

**Comment by mconnew** [comment]
You are using Web Services Enhancements (WSE) which was an add-on library to support more SOAP features for Web Services for .NET 2.0 and was the precursor to WCF. Can you provide the WSDL for the service you are trying to communicate with? I suspect either BasicHttpsBinding or WSHttpBinding with security mode of TransportWithMessageCredential is what you need. Unfortunately neither of those is supported yet with dotnet-svcutil, but the WCF libraries themselves support those features. With the WSDL I should be able to tell you definitely if your scenario is supported and if it is, what code you will need.

**Comment by gaui** [comment]
Hey @mconnew , thank you for that. Here's the WSDL: http://ws-test.skra.is/SvcFasteignaskra_0402/Fasteignaskra.asmx?wsdl

**Comment by mconnew** [comment]
Unfortunately your WSDL is incomplete. This means you are likely doing the signature verification manually on the server side similar to how you are signing it manually on the client side. I'm not sufficiently familiar with WSE to be able to map the code directly to WCF. I did a bit of digging around on the internet and what you are doing is bordering on MessageSecurity and not TransportWithMessageSecurity so I'm not sure if it's doable as I think MessageSignature might use a SignedXml transform which isn't available to us.  
Can you provide an example request and response message with any security details redacted. You need to leave the XML document structure the same so leave the XML elements and attributes, but replace any binary blobs (base64 encoded strings) and any other identifiers with something showing they've been replaced (like `REDACTED`) because sometimes an empty element is legitimate. I might be able to work out the equivalent in WCF by working backwards from the SOAP message.

**Comment by gaui** [comment]
@mconnew Thank you very much. Here's an example SOAP message with the token redacted: https://gist.github.com/gaui/83ab22b9fd2e4cb6a544e649a319c8cc

**Comment by mconnew** [comment]
I've got a bit of bad news. Your scenario would cause a PlatformNotSupportedException to be thrown as it requires going down the same code path as full MessageSecurity does. But looking at how your message is signed, I believe we should have all the security primitives needed to support your scenario. Normally for your type of scenario a type of XML transform called STR-Transform is used which is why this code path has been disabled but as you aren't using that transform, it should be doable.  
Unfortunately this means I don't have a solution for you in the short term but this is a scenario I'd like to get working. Especially as it looks like there isn't a lot of implementation to port, it's mostly just re-enabling a couple of code paths.  
For the benefit of future me, here's the main place where changes need to be made:  
https://github.com/dotnet/wcf/blob/d71557a6ba42bd6d4c5223e978cdafd5b535b970/src/System.Private.ServiceModel/src/System/ServiceModel/Security/SendSecurityHeader.cs#L409
It looks like I've already correctly ported the actual signing and reference adding code here:
https://github.com/dotnet/wcf/blob/d71557a6ba42bd6d4c5223e978cdafd5b535b970/src/System.Private.ServiceModel/src/System/ServiceModel/Security/WSSecurityOneDotZeroSendSecurityHeader.cs#L329

**Comment by gaui** [comment]
@mconnew Thank you for this. I managed to create and sign the SOAP message by implementing `IClientMessageInspector` and the `BeforeSendRequest` function. Everything works perfectly when I copy the SOAP message into Postman and send it there, but it fails through .NET Core. The error message is the following:

```
ProtocolException: The content type application/soap+xml; charset=utf-8 of the response message does not match the content type of the binding (text/xml; charset=utf-8). If using a custom encoder, be sure that the IsContentTypeSupported method is implemented properly.
```

Is it possible somehow to override the `Content-Type` HTTP header to `text/xml` instead of `application/soap+xml` ? I thought MessageVersion.Soap11 uses `text/xml` but it seems to be `application/soap+xml` :confused:

**Comment by mconnew** [comment]
The content type `application/soap+xml` is for SOAP 1.2 and `text/xml` is for SOAP 1.1. So your service is returning a SOAP 1.2 response. You can either modify your binding or create a new binding and setting the appropriate message version on the TextMessageEncodingBindingElement. I suspect the following binding should work for you:
```
var mebe = new TextMessageEncodingBindingElement();
mebe.MessageVersion = MessageVersion.Soap12;
var transportbe = new HttpTransportBindingElement();
var binding = new CustomBinding(mebe, transportbe);
```
If not, then use:
```
var customBinding = new CustomBinding(existingBinding);
var mebe = customBinding.Elements.Find<TextMessageEncodingBindingElement>();
mebe.MessageVersion = MessageVersion.Soap12;
```
And use the `customBinding` when creating your channel factory.

**Comment by HongGit** [comment]
@gaui  it seems that your issue is resolved.  Feel free to reopen if that is not the case.

**Comment by domagojmedo** [comment]
@mconnew is there any plan to enable this signing on .NET Core? I see that you commented that you would like to include it, but issue has since been closed

**Comment by pacoweb** [comment]
Hi, @gaui

I'm trying to do something similar to what you mentioned here. Could you give me an example of how you achieved this using IClientMessageInspector? Thanks in advance.v
