### ISSUE TITLE
With net48 you can read from the ProtocolException.InnerException the response stream. This is not possible in netcoreapp3.1

### ISSUE THREAD

**Issue by JSCProjects** [dotnet/wcf#4454]
We have services (not in my control, written in Java for example) where we connect with wcf and when these services return a HttpStatus Code 400 with a soapfault. Your where able to catch te ProtocolException and read the soapfault via the inner exception:

```
catch (ProtocolException protocolException)
            {
                if (!(protocolException?.InnerException is WebException webEx))
                {
                    // netcoreapp3.1 doesn't have an InnerException
                    throw;
                }

                using var stream = webEx.Response.GetResponseStream();
                using var xmr = XmlReader.Create(stream);
                var message = Message.CreateMessage(xmr, (int) stream.Length, MessageVersion.Soap11);
                var mf = MessageFault.CreateFault(message, (int) stream.Length);
                message.Close();
                throw new FaultException(mf, requestFunction.Method.Name);
            }
```

**To Reproduce**
1. Run a SOAP Service which returns SOAP-Faults and status code 400
2. Build soap client with net48 and try to call the SOAPService -> Result FaultException is thrown (wanted)
3. Build soap client with netcoreapp3.1 and try to call the SOAPService -> Result ProtocolException is thrown (NOT-wanted)

**Expected behavior**
I would like to receive FaultException even if it's not following the standard. Or let me get the response via another way and throw a FaultException.

**Comment by mconnew** [comment]
The reason why there isn't an inner exception is because HttpClientHandler doesn't throw an exception for non-200 responses. It simply replies with an HttpResponseMessage with the appropriate response code.  This is the more correct way to do things because receiving a non-200 response isn't an exception from an HTTP Protocol point of view. It's only an error at the application level that's interpreting it.  

I presume you're having to do this because the Java service isn't using a 500 HTTP Status Code when returning a Fault response? If so, there might be an easier option for you. In .NET Core, I added the ability to replace the HttpClientHandler with a custom HttpMessageHandler implementation. You could create a handler which derives from [DelegatingHandler](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.delegatinghandler?view=net-5.0) to wrap the default HttpClientHandler and modify the response status code before it's returned to WCF. Then you let WCF's normal Fault handling code handle the Fault response and convert it into a FaultException for you. You can find the basis of an example implementation [here](https://github.com/dotnet/wcf/blob/1bf5b13fe172738a75d2c5b016d96970c35fe2a7/src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/HttpBindingTestHelpers.cs#L12). You can see how it's added to the ChannelFactory [here](https://github.com/dotnet/wcf/blob/1bf5b13fe172738a75d2c5b016d96970c35fe2a7/src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/BasicHttpBindingTests.4.0.0.cs#L100-L107). Although you could use that implementation using delegates, you can just put the logic inline in the implementation. You can check the status code of the HttpResponseMessage and if it's the value used for faults by the Java service, set it to 500 instead.

**Comment by mconnew** [comment]
I'm going to close this issue. If my suggested solution doesn't work for you, feel free to reopen.
