### ISSUE TITLE
NetTcpBinding throws PlatformNotSupportedException .Net Core 3.1

### ISSUE THREAD

**Issue by Dimigergo** [dotnet/wcf#4482]
Hello!

Windows: Win10 x64 Pro 20H2

I have a .NET Standard 2.0.3 project called MLR.Components.WCF.Client with System.ServiceModel 4.8.0 dlls.
![wcf_1](https://user-images.githubusercontent.com/11498949/103771217-95141500-5027-11eb-853b-8a9470fdbe47.png)

When I run from a .NET Framework 4.7.2 project, everything is works fine, but when I start a .NET Core 3.0/3.1 project including this library, the following exception is thrown with Message security:
![wcf_2](https://user-images.githubusercontent.com/11498949/103770804-e1128a00-5026-11eb-97f1-fad52d572a5c.png)

When I switched to `SecurityMode.None` it works fine, but I need the message security, because all of my other .NET Framework with this library projects uses message security flawless. We need NetTcpBinding and Message Security, because we released our projects to cross-domain platforms, over the internet, and uses large amount of data to transmit with sensitive information.

Our conception is use the same WCF channel library, because all of the data is the same for the web and the existing desktop clients:
![wcf_3](https://user-images.githubusercontent.com/11498949/103772378-b8d85a80-5029-11eb-8ca8-3dc470b5dbfd.png)

So in one word, everything is works fine, except when we start to use .NET Core.

Thanks in advance!

**Comment by Dimigergo** [comment]
I have a workaround for this.

When I change the security mode from Message to TransportWithMessageCredential everything works fine with .NET Core 3.1.
```
binding.Security.Mode = SecurityMode.TransportWithMessageCredential;
binding.Security.Transport.ClientCredentialType = TcpClientCredentialType.Certificate;
binding.Security.Message.ClientCredentialType = MessageCredentialType.Certificate;
```

But the main problem still alive:
MessageSecurity is not supported.

Thanks!

**Comment by Jetski5822** [comment]
throws in .net5.0+ too

**Comment by Jetski5822** [comment]
Simple Repo 

```
// See https://aka.ms/new-console-template for more information
var x = new System.ServiceModel.NetTcpBinding("LargeTcpBinding");

Console.WriteLine("Hello, World!");
```

**Comment by mconnew** [comment]
I'm sorry I missed this. This got pulled to me attention when somebody else commented (and looks like they deleted their comment as it was unrelated). We don't have support for Message security due to missing dependencies. This issue is tracked in #4. The difference between TransportWithMessageCredential and Message is two fold. Firstly, TransportWithMessageCredential uses SSL/TLS to make the communication secure and to detect message tampering whereas Message encrypts and signs the message itself. Secondly, TransportWithMessageCredential validates the server's identity via the server TLS certificate. The mechanism of authenticating the client is the same in both cases. For your scenario, it is providing the client certificate as a security token in the initial session establishment handshake. WCF enables you to have multiple bindings used on the server listening on different endpoints (in this case, different paths). If you don't need security in rest (messages saved to disk or a database for example and still being encrypted), and you aren't doing multiple hop message routing using WCF Routing Services, then you get equivalent security with TransportWithMessageCredential. You can add a second endpoint on your service using TransportWithMessageCredential and all existing clients will be unaffected. A .NET Core client would connect to the new endpoint on the exact same service instance.  

As a side note, NetTcp really doesn't perform well over the internet, specifically with high latency connections. The reason is that there is a single byte ACK that the server replies once a request has been successfully decoded. The client is unable to use the same socket to send any more requests until it receives that ACK byte. If the client is taking advantage of the ability to send multiple outstanding requests to the service and have the replies come back in any order, then the round trip latency reduces performance. This also affects one-way operations as there's still an ACK byte response with a one-way operation. If you are adding a second endpoint to accommodate .NET Core, I would recommend evaluating using an HTTP based binding for internet communication.

Closing this issue as it's a duplicate of #4.
