### ISSUE TITLE
Back out PR to work around dnu upgrade

### ISSUE THREAD

**Issue by mconnew** [dotnet/wcf#452]
The most recent dnu upgrade doesn't traverse folders the same way it used to and we were missing doing a package restore on older reference assembly/façade versions. Once the dnu issue is resolved, my work around from PR #451 needs to be backed out.

**Comment by iamjasonp** [comment]
There was a follow-up checkin after yours, @mconnew. This probably will mean that both https://github.com/dotnet/wcf/commit/df2f33ccd90edb41ae89b4621430d496171ca4aa and https://github.com/dotnet/wcf/commit/7749b8522b7fe348c907ff7438c327db4e45a83d will need to be re-evaluated once we figure out what to do. 

(for reference - the root cause of this was https://github.com/aspnet/dnx/pull/2910)

**Comment by ellismg** [comment]
FWIW, You can close this issue now.  The newer versions of dotnet cli don't have this bug.

**Comment by zhenlan** [comment]
@mconnew do we still need to do any revert or can this issue be closed now?

**Comment by mconnew** [comment]
No longer applicable
