### ISSUE TITLE
WCF Web Service Reference Provider Tool Failure

### ISSUE THREAD

**Issue by isadrastea** [dotnet/wcf#4554]
My local web service is running well but i can't create a connected service reference in WPF (Net Core 3.1) Project on visual studio 2019 version 16.8.6. Only .Net Framework project is possible.

// Service web page
![image](https://user-images.githubusercontent.com/26916642/109841030-fead4a00-7c8b-11eb-9a42-96840e009520.png)

// Connected Service reference failure
![image](https://user-images.githubusercontent.com/26916642/109841282-387e5080-7c8c-11eb-9570-989367769b72.png)

**Comment by isadrastea** [comment]
My WPF project was generated by windows template studio with Prism MVVM pattern.

![image](https://user-images.githubusercontent.com/26916642/109843354-5056d400-7c8e-11eb-840c-3e8a2fa90ba7.png)

**Comment by imcarolwang** [comment]
@isadrastea Regarding the Connected Service reference failure, I guess it's caused by the extra slash at the end of the URI name, try without the end slash, i.e. http://localhost:8585/RtTower.WebService

For the generating error, WCF Connected Service tool currently doesn't support target framework net5.0-windows. As a workaround, would it work for you to use netcoreapp3.1 to generate the wcf proxy and change back to your targeting framework afterwards?

**Comment by isadrastea** [comment]
My development environment is VS 2019 .netcore 3.1 with WPF. And i already tested it without last backslash. Unfortunately it was not help to solve issue.
So, i tried trick test with .net framework application to generate wsdl file. Then imported the wsdl file in my wpf project. The trick help to create connected service reference, But it create asynchronous methods of reference. That is so fuuny. I think the connected servive reference generate did it for httpclient by default.
