### ISSUE TITLE
In BridgeClientCertificateManager: when foundUserCertificate is true, isLocalKeyName does not set correctly in some cases

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#465]
When foundUserCertificate is true, isLocalKeyName should be set in the case certificate is already installed. It isn't set currently for some reason.

**Comment by iamjasonp** [comment]
This is by design. See https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Common/Infrastructure/src/BridgeClientCertificateManager.cs#L132 

"isLocal" is something returned from the Bridge upon PUT to tell the BridgeClient if it requested creation of a cert for a machine that is local to the bridge. It DOES NOT indicate whether or not this was installed already. 

Say you have a computer `mytest-box.example.com`

isLocal is true if the PUT request is for: 
FQDN - `mytest-box.example.com`
Hostname - `mytest-box`
localhost - `localhost`

In these cases where the BridgeClient is requesting these certs (as it's running on the same box), the BridgeClient will know that it's a cert it doesn't need to be installed. This detection was needed to prevent the process running BridgeClient from needing elevation when running on the same machine as the Bridge itself.

**Comment by hongdai** [comment]
If it's running on the same box, do you expect below If statement is true(i.e IsLocalKeyName is set)  and isLoal is true? Currently it does not go into the if statement as TryGetValue return false.


136                     if (response.TryGetValue(IsLocalKeyName, out isLocalString)) 
137                     { 
138                         bool isLocal = false; 
139                         if (bool.TryParse(isLocalString, out isLocal) && isLocal) 
140                         { 
141                             return; 
142                         }

**Comment by iamjasonp** [comment]
I think the wrong question is being asked. 

It doesn't matter if the BridgeClient and Bridge are on the same box. Remember that the Bridge is agnostic of where the BridgeClient is running, and vice versa. 

What matters is the incoming PUT request's certificate subject name. 

So if you are running on `test.foobar.com` and your incoming PUT to MachineCertificateResource is for a certificate for `test` or `test.foobar.com`, `isLocal` returns true. This is true regardless of what machine the request is originating from.  

If you request a UserCertificateResource, isLocal is not passed back at all. There is no way to determine whether or not the cert generated is for a  local machine or not. 

I have been looking to remove this check entirely in favour of a better method, but I have not yet figured out what "better" is.

**Comment by hongdai** [comment]
Closing this issue as it does not causing a test failure.
