### ISSUE TITLE
Connected services tab doesn't include WCF Web Services

### ISSUE THREAD

**Issue by Joebeazelman** [dotnet/wcf#4715]
Created a new project from VS2019 WCF template.  WCF Services is not one of the option listed under the Connected Services tab, but you can add it using the "Add Service Reference" by right-clicking on the project. The menu option is nondescript and the title says nothing about WCF, making it difficult to find in the huge list of menu options.

Come on Microsoft!  Why are you guys so inept!  Do you guys even use the software you write?

**Comment by imcarolwang** [comment]
The "Add Service Reference" menu is to trigger running tool to generate WCF Client code against WCF Service in a .NetFramework targeting project.

This repository tracks issues relate to WCF Client codes/tools base on .NETCore runtime, since the problem here looks relate to UI behavior of "Add Service Reference" used by a .NetFramework project template, could you please file ticket in https://developercommunity.visualstudio.com/home with the repro details you have? Thank you.

**Comment by HongGit** [comment]
Close this issue since no new response.  Feel free to re-open or log a new issue if the problem persists.
