### ISSUE TITLE
E2E scenarios for Linux

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#476]

**Comment by roncain** [comment]
It would be useful to provide a description of what this issue is asking.  It will let us discuss the requirements before building it.  In my mind, the goals are:
1. Provide a simple console app that can run on *any* platform to verify basic WCF functionality.
2. Make it easy for one of us to convert this console app into a test case repro we can send to other teams if we want to show them a specific failure.

I believe you will need to copy some of the BridgeClient code so that it talks to WCF Services via the Bridge, because of course the Bridge may need to run on another machine when this app runs on Linux.  I recommend reuse of the Bridge endpoints for these reasons:
1. We don't want another set of WCF services and interfaces to maintain
2. We don't want to invent yet another multi-machine setup
3. If we find a failure and want to provide this app to another team as a repro, it needs to be ready to repro *any* of our scenarios.

The default console app doesn't need to exercise all our functional tests, but it should be written so it is easy for one of us to modify it to exercise a single specific functional test.

**Comment by hongdai** [comment]
Adding the requirements of the linux E2E scenarios I have in mind in addition to Ron's comments above:
1) Verify E2E customer experience on Linux.
I'll need to get E2E customer experience from Linux owner.
2)  Find out the gap between e2e customer experience and lab runs and fill the gap.
The current list is:
a. Product set up is different. So we need to verify the product has been setup correctly.
b. No runtime difference. So we don't need to repeat all scenario tests in the lab  run. Pick one from each product Nuget package should be sufficient.

For the implementation, Agree to reuse lab run tests.

**Comment by zhenlan** [comment]
@hongdai, agree with what you said. Regarding b, we may like to pick up more than one scenarios per our package if they touch different major dependent packages (eg. http, sockets etc.).

**Comment by hongdai** [comment]
This is done. We haven't found any new issue in the Linux E2E testing for RC1.
