### ISSUE TITLE
Question: Is the auto-generated code from WsdlImporter .NET 6 compatible?

### ISSUE THREAD

**Issue by andliang** [dotnet/wcf#4805]
I apologize if this is the wrong place to ask this question but I dont know where else to turn.

From what I understand WsdlImporter only runs on .NET Frameowork (that I know at the very least). WsdlImporter can be used to auto-generate C# code (see [here](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.description.wsdlimporter?view=netframework-4.8) for an example). Is the auto-generated code produce by WsdlImporter .NET 6 compatible?

Thanks

**Comment by HongGit** [comment]
Not 100%, but you can make it work with some small changes. The issue is the binding config and endpoint config on .NET Framework using app.config and .NET needs it in code. But the contracts and generated client will work if you use the constructor overload which takes a binding and endpoint address.
