### ISSUE TITLE
IChannelListener interface not available

### ISSUE THREAD

**Issue by bstordrup** [dotnet/wcf#4812]
**Describe the bug**
The IChannelListener interface is not available when using the System.ServiceModel.Primitives package

**To Reproduce**
See the project in this project: https://github.com/bstordrup/WcfMissingInterface

The project will not compile as the IChannelListener is not visible in the System.ServiceModel.Channels namespace although the interface is marked public in the code base.

**Expected behavior**
IChannelListener interface should be visible.

**Additional context**
I think that the problem is caused by the IChannelListener interface not being part of the System.ServiceModel.Primitives.cs in the System.ServiceModel.Primitives.Ref project. However, I'm not able to test this as I'm not able to build the solution, but that's another story.

**Comment by mconnew** [comment]
The IChannelListener interface is a service side only api and isn't applicable to client side usage of WCF. This project and the produced packages are only for supporting the client usage of WCF. The interface only exists in the implementation as a holdover from when we were first porting the code and the client and server side of the implementation were very tightly bound together. It enabled us to more quickly port an implementation. You will see in the code base that there are zero implementations of these interfaces and zero reachable code calling any of the methods on the interfaces.  
We won't be adding these interfaces to the reference assembly. If you need them to be able to compile your own code, the best option I can suggest is to add the interfaces to your own code base using conditional compilation so that they only get included when you target netstandard2.0/netcoreapp3.1+/net5.0+. I'm going to close this issue and the PR as there isn't anything actionable from the WCF side.

**Comment by bstordrup** [comment]
@mconnew, thank you for the answer. Would it make sense to add them to CoreWCF instead if they are server side?

**Comment by mconnew** [comment]
The call pattern is different in CoreWCF. It's based off the asp.net core middleware model and not the polling model (accept/begin accept with callback). Also the namespace is different in CoreWCF so even if it was the same programming model, it still wouldn't help.
