### ISSUE TITLE
no dash "-" in dotnet svcutil execution command, parameter short "-d" for "--OutputDir" does not work

### ISSUE THREAD

**Issue by SnailGirl-Joanna** [dotnet/wcf#4914]
Description
The parameter short for --outputDir does not work on dotnet svcutil (No dash "-" between dotnet and svcutil)

Simple Reproduce

> create and build console project
> Execute the dotnet svcutil command to add servicereference as below
>       dotnet svcutil /SayHello.svc -d C:\FolderName

If use  dotnet-svcutil /SayHello.svc -d C:\FolderName or dotnet svcutil /SayHello.svc --outputDir C:\FolderName, reference code generate normally

Expected behavior
The service reference code generated normally

**Comment by imcarolwang** [comment]
Starting with dotnet-svcutil 2.x, the recommend way to use this global tool is running dotnet-svcutil.exe by itself (dotnet-svcutil) instead of invoking dotnet. See the [dotnet-svcutil ](https://learn.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil2x) guide for more usage reference. Closing issue.
