### ISSUE TITLE
Add a ScenarioTestHelpers.DisposeAll() that takes a list of IDisposable objects.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#492]
This method would also check for null first and then call Dispose.
Apply to Extensibility/WebSockets/WebSocketTests.cs tests that use the ClientReceiver type.

**Comment by roncain** [comment]
Part of this issue is deciding the right pattern for scenario tests that use multiple IDisposable objects.  This could include use of 'using' statements which would eliminate the need for this test helper class.  I mentioned the possibility of this helper primarily to ensure we had a consistent cleanup model for each test that did not leave IDisposable instances undisposed.

**Comment by roncain** [comment]
Closing because this helper was added many months ago and is use throughout our tests.
