### ISSUE TITLE
Console App cannot connect to SSRS server

### ISSUE THREAD

**Issue by sal-420** [dotnet/wcf#4936]
**WCF code fails  after returning from  ` public System.Threading.Tasks.Task<SsrsServiceReference1.LoadReportResponse> LoadReportAsync(SsrsServiceReference1.TrustedUserHeader TrustedUserHeader, string Report, string HistoryID)`** 

if `rsBinding.Security.Mode = BasicHttpSecurityMode.Transport;` the program stops with no error.

if `rsBinding.Security.Mode = BasicHttpSecurityMode.TransportCredentialOnly;` error thrown is: `The provided URI scheme 'https' is invalid; expected 'http'. (Parameter 'via')` 

**To Reproduce**
C# console app
.net 5.0
VS2019
local IIS
SSRS server
https://mySsrsServer/reportserver/ReportExecution2005.asmx

```c#
using ServiceReference1;
using System;
using System.Collections.Generic;
using System.IO;
using System.ServiceModel;
using System.Threading.Tasks;

namespace SSRSSimple
{
    class Program
    {
        const string ReportExecution2005EndPointUrl = "https://YourServer.com/ReportServer/ReportExecution2005.asmx";
        const string SsrsServiceAccountActiveDirectoryUserName = "someActiveDirectoryNameWithoutDomain";
        const string SsrsServiceAccountActiveDirectoryPassword = "somePassword";
        const string SsrsServiceAccountActiveDirectoryDomain = "someDomain";
        const string ReportPath = "/ProjectName/Reports/Report_Overview_Basic_Without_Rdl_Extension";
        const string ReportWidth = "8.5in";
        const string ReportHeight = "11in";
        const string ReportFormat = "PDF";  // Other options include WORDOPENXML and EXCELOPENXML
        const string HistoryId = null;

        static void Main(string[] args)
        {

            RunReport().Wait();

            Console.WriteLine("DONE !");
        }

        private static async Task RunReport()
        {
            ReportExecutionServiceSoapClient rs = CreateClient();
            var trustedHeader = new TrustedUserHeader();

            LoadReportResponse loadReponse = await LoadReport(rs, trustedHeader);

            await AddParametersToTheReport(rs, loadReponse.ExecutionHeader, trustedHeader);

            RenderResponse response = await RenderReportByteArrayAsync(loadReponse.ExecutionHeader, trustedHeader, rs, ReportFormat, ReportWidth, ReportHeight);

            SaveResultToFile(response.Result, "SomeFileName.pdf");
        }

        private static async Task<LoadReportResponse> LoadReport(ReportExecutionServiceSoapClient rs, TrustedUserHeader trustedHeader)
        {
            // Get the report and set the execution header.
            // Failure to set the execution header will result in this error: "The session identifier is missing. A session identifier is required for this operation."
            // See https://social.msdn.microsoft.com/Forums/sqlserver/en-US/17199edb-5c63-4815-8f86-917f09809504/executionheadervalue-missing-from-reportexecutionservicesoapclient
            LoadReportResponse loadReponse = await rs.LoadReportAsync(trustedHeader, ReportPath, HistoryId);  // <<<------- this is the errant line

            return loadReponse;
        }

        private static async Task<SetExecutionParametersResponse> AddParametersToTheReport(ReportExecutionServiceSoapClient rs, ExecutionHeader executionHeader, TrustedUserHeader trustedHeader)
        {
            // Add parameters to the report
            var reportParameters = new List<ParameterValue>();
            reportParameters.Add(new ParameterValue() { Name = "ProjectID", Value = "1434" });
            reportParameters.Add(new ParameterValue() { Name = "GeographyID", Value = "6071" });
            reportParameters.Add(new ParameterValue() { Name = "Radius", Value = "20" });
            reportParameters.Add(new ParameterValue() { Name = "PreparedBy", Value = "Dave" });
            reportParameters.Add(new ParameterValue() { Name = "PreparedFor", Value = "Someone special" });
            reportParameters.Add(new ParameterValue() { Name = "CurrencyId", Value = "142" });
            
            SetExecutionParametersResponse setParamsResponse = await rs.SetExecutionParametersAsync(executionHeader, trustedHeader, reportParameters.ToArray(), "en-US");

            return setParamsResponse;
        }

        private static async Task<RenderResponse> RenderReportByteArrayAsync(ExecutionHeader execHeader, TrustedUserHeader trustedHeader,
           ReportExecutionServiceSoapClient rs, string format, string width, string height)
        {
            string deviceInfo = String.Format("<DeviceInfo><PageHeight>{0}</PageHeight><PageWidth>{1}</PageWidth><PrintDpiX>300</PrintDpiX><PrintDpiY>300</PrintDpiY></DeviceInfo>", height, width);

            var renderRequest = new RenderRequest(execHeader, trustedHeader, format, deviceInfo);

            //get report bytes
            RenderResponse response = await rs.RenderAsync(renderRequest);
            return response;
        }


        private static ReportExecutionServiceSoapClient CreateClient()
        {
            var rsBinding = new BasicHttpBinding();
            rsBinding.Security.Mode = BasicHttpSecurityMode.Transport;  // << -- for an error message change to `BasicHttpSecurityMode.TransportCredentialOnly`
            rsBinding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Windows;
            
            var rsEndpointAddress = new EndpointAddress(ReportExecution2005EndPointUrl);
            var rsClient = new ReportExecutionServiceSoapClient(rsBinding, rsEndpointAddress);

            // Set user name and password
            rsClient.ClientCredentials.Windows.AllowedImpersonationLevel = System.Security.Principal.TokenImpersonationLevel.Impersonation;
            rsClient.ClientCredentials.Windows.ClientCredential = new System.Net.NetworkCredential(
                SsrsServiceAccountActiveDirectoryUserName, 
                SsrsServiceAccountActiveDirectoryPassword, 
                SsrsServiceAccountActiveDirectoryDomain);


            return rsClient;
        }

        private static void SaveResultToFile(byte[] result, string fileName)
        {
            using (var fs = File.OpenWrite($"c:\\temp\\{fileName}"))
            using (var sw = new StreamWriter(fs))
            {
                fs.Write(result);
            }
        }
    }
}
```

**Comment by mconnew** [comment]
As per the [documentation here](https://learn.microsoft.com/en-us/dotnet/api/system.servicemodel.basichttpsecuritymode?view=dotnet-plat-ext-7.0#fields) `TransportCredentialOnly` is for HTTP and not HTTPS. `TransportCredentialOnly` means you are only using the credential part of the transport security, meaning HTTP authentication, and you aren't using any security capability such as using SSL/TLS. As HTTPS uses SSL/TLS and you are providing an HTTPS URL, you are saying "I only want to use the credentials aspect of HTTP security and not SSL/TLS, and I want to do so with a server which requires SS:/TLS".  
WCF can't use SSL/TLS and not use it at the same time. The error message is by design, as per the thrown error message "The provided URI scheme 'https' is invalid; expected 'http'."

**Comment by sal-420** [comment]
@HongGit.

Hi Hong 
I mentioned above  using `Transport` option  results in the program stopping  and no error is thrown. Try/catch fails to catch any error. The errant line is in the WCF service ` return ((SsrsServiceReference1.ReportExecutionServiceSoap)(this)).LoadReportAsync(inValue); `  


Using ` BasicHttpSecurityMode.None;` results in error "The provided URI scheme 'https' is invalid; expected 'http'. (Parameter 'via')" the inverse of `TransportCredentialOnly`

Keep in mind this is a dot net 5 console app using windows authentication requesting SSRS reports

**Comment by mconnew** [comment]
From the same documentation, the value `None` means:

> The SOAP message is not secured during transfer. This is the default behavior.

HTTPS uses SSL/TLS to secure the connection. So when you say you want no security, this isn't compatible with using an HTTPS url. You are saying "I want no security using this URL which provides security". If you are using an HTTPS url, you need to use security mode `Transport`. 

It sounds like your issue is that your application is hanging and not about whether an exception is being thrown? The default SendTimeout on the binding is 1 minute. It doesn't look like you are setting a different timeout, so have you waited 1 minute to see if the call times out? You can modify the timeout by setting `BasicHttpBinding.SendTimeout` to the relevant TimeSpan, eg `TimeSpan.FromSeconds(10)` so you don't have to wait so long.  

Have you tried using [Fiddler](https://www.telerik.com/fiddler/fiddler-classic) to see if your request is being sent and the response received? You will need to configure Fiddler to decrypt HTTPS connections, documentation [for that is here](https://docs.telerik.com/fiddler/configure-fiddler/tasks/decrypthttps).

As this is an asmx service, I presume your previous client on .NET Framework wasn't WCF but a Web Services Soap Client. It might be worth capturing a request with Fiddler from your existing .NET Framework client and comparing with what .NET 5 is producing so see if there's any obvious differences.

**Comment by HongGit** [comment]
closing as there is no response since last Oct.   Feel free to re-activate if this is still an issue.
