### ISSUE TITLE
FaultException<TDetail> overrides ToString() but fails to include client-side stacktrace, thereby breaking all generic exception logging

### ISSUE THREAD

**Issue by oskarb** [dotnet/wcf#4945]
It is a common pattern to have generic catch-all statements in e.g. thread main or other generic error handlers that catch Exception and log it using `ToString()`.

Unlike more or less any other exception class known to man-kind, FaultException<TDetail> overrides `ToString()` *and* doesn't include the stack trace in the returned string:
https://github.com/dotnet/wcf/blob/4e2a97e639417fd14158c9e7f0bb36de342a667d/src/System.Private.ServiceModel/src/System/ServiceModel/FaultException.cs#L417-L420

This breaks generic exception loggers using ToString() because specifically for FaultException we now get no information about where in the client it happened. (Ironically, in troubleshooting scenarios we may get part of the server's stack trace if it has been included in the Detail object. But not the client's.)

The base `Exception.ToString()` is documented (https://learn.microsoft.com/en-us/dotnet/api/system.exception.tostring?view=net-6.0) as:
> [ToString](https://learn.microsoft.com/en-us/dotnet/api/system.exception.tostring?view=net-6.0) returns a representation of the current exception that is intended to be understood by humans. Where the exception contains culture-sensitive data, the string representation returned by ToString is required to take into account the current system culture. Although there are no exact requirements for the format of the returned string, it should attempt to reflect the value of the object as perceived by the user.

> The default implementation of [ToString](https://learn.microsoft.com/en-us/dotnet/api/system.exception.tostring?view=net-6.0) obtains the name of the class that threw the current exception, the message, the result of calling [ToString](https://learn.microsoft.com/en-us/dotnet/api/system.exception.tostring?view=net-6.0) on the inner exception, and the result of calling [Environment.StackTrace](https://learn.microsoft.com/en-us/dotnet/api/system.environment.stacktrace?view=net-6.0). If any of these members is null, its value is not included in the returned string.

So perhaps there is no formal contract that ToString() *must* include the stack trace, but base class documentation and precedence sure strongly implies it. The lack of this basically leads to having to special case FaultException everywhere you write a generic exception logging routine which is annoying and in practice impossible.

**Comment by mconnew** [comment]
A FaultException specifically communicates that the service returned a Fault response to a request. WCF converts the returned Fault message into a FaultException and throws it. Nothing on the client side went wrong and everything functioned as intended. It's the service which has communicated that something went wrong on the service side. This means the call stack on the client side is irrelevant as it will simply be a call stack to the code which converts a Fault message into a FaultException.  
As you quoted from the documentation:
>Although there are no exact requirements for the format of the returned string, it should attempt to reflect the value of the object as perceived by the user.

To provide the call stack of where FaultException was thrown wouldn't be an accurate reflection of what happened and would actually be misleading. We fulfill the requirement of the ToString() method by providing all the information we have from the service about what went wrong. Depending on how the service was configured, that might include the stack trace on the service side,  
 
The key thing from the documentation is:
>[ToString](https://learn.microsoft.com/en-us/dotnet/api/system.exception.tostring?view=net-6.0) returns a representation of the current exception that is intended to be **understood by humans**.

If you have code which is interpreting the output of Exception.ToString() in any way, it's doing the wrong thing. The only reason for logging the output from ToString() is to write it out to the log so that a human can read that log to get an idea of what happened. Having the call stack of the code which converts a Fault message to an exception doesn't help you at all and is wasting space in your logs.  

If you do have code which is interpreting the stack trace from ToString(), you should either log the value of `Exception.StackTrace` (presuming the code that's interpreting it is reading the logs), or directly interpret Exception.StackTrace, but as I said, this is a waste of time for FaultException. If there's a problem which occurred locally in the WCF client, you will have a valid stack trace in the output of ToString() indicating where the problem happened.

FaultException isn't the only exception which does things a little differently. Take a look at the [list of exception types here](https://source.dot.net/#q=Exception.ToString) which have overridden the ToString() method. Many of them produce the same output, but not all of them. For example, Win32Exception can output the NativeErrorCode and HResult to the output.

If you want to know the stack trace of an Exception, the correct place to retrieve it is the StackTrace property. If you want to know the message that came with it, use the Message property. If you need the log output to be consistent, you should build your own exception log string code to create a consistent output based on the information you want to be included.
