### ISSUE TITLE
dotnet-svcutil : request serialization bug

### ISSUE THREAD

**Issue by rfedericoni** [dotnet/wcf#5028]
**Describe the bug**
Environment: dot net core 6
OS: MacOS

Using the wsdl in attachment when I call the method renewAccountSpidProfessionalFromIdUserByDateAsync in the logged request xml **idUser** and other params (autoRenew, dateTo) are missing even if correctly set. All methods that have explicit params (not a single request param) works instead of this one that as only one param as object request. I think there is some bug for this particular case and for some reason the XML request serialization skips some renewAccountSpidProByDateRequest properties.

**Logged xml request**
`<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><Action s:mustUnderstand="1" xmlns="http://schemas.microsoft.com/ws/2005/05/addressing/none"></Action></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><renewAccountSpidProfessionalFromIdUserByDate xmlns="http://service.ws.nam/"><request xmlns=""><idLicenseManager /><idLra>20</idLra></request></renewAccountSpidProfessionalFromIdUserByDate></s:Body></s:Envelope>**`

**To Reproduce**
        var request = new renewAccountSpidProByDateRequest
        {
            idLra = "20",
            autoRenew = true,
            idLicenseManager = "",
            idUser = 123456,
            dateTo = DateTime.Now
        };
        Service.renewAccountSpidProfessionalFromIdUserByDateAsync(request);

**Additional context**
[spid.wsdl.zip](https://github.com/dotnet/wcf/files/10863689/spid.wsdl.zip)

**Comment by imcarolwang** [comment]
It seems that the fileds are missing because XmlSerializer applyies PropertyNameSpecified pattern to conditionally serialize the property. PropertyNameSpecified pattern involves adding a boolean property to your class that indicates whether the property should be serialized. The name of this boolean property is constructed by appending "Specified" to the name of the property you want to conditionally serialize. You can refer to [this doc](https://learn.microsoft.com/en-us/dotnet/api/system.xml.serialization.xmlserializer?redirectedfrom=MSDN&view=net-7.0#:~:text=Another%20option%20is%20to%20use%20a%20special%20pattern) for more details.



To address this issue, you can set the [missingPropertyName]Specified to true as showed below and retry the scenario.
```
var request = new renewAccountSpidProByDateRequest
{
    idLra = "20",
    autoRenewSpecified = true,
    autoRenew = true, // missing
    idLicenseManager = "",
    idUserSpecified = true,
    idUser = 123456, // missing
    dateToSpecified = true,
    dateTo = DateTime.Now // missing
};
```

**Comment by HongGit** [comment]
@rfedericoni closing this as workaround was provided.  Feel free to reactivate if the issues persist.
