### ISSUE TITLE
Breaking change going from System.ServiceModel.* 4.10.0 to 4.10.1

### ISSUE THREAD

**Issue by KeithHenry** [dotnet/wcf#5053]
**Describe the bug**
Code that compiled on `System.ServiceModel.Primitives` `4.10.0` does not compile on `4.10.1`

```c#
// This line compiled previously:
await this.wcfGenerateClient.CloseAsync();
```

> {our generated WCF service} does not contain a definition for 'CloseAsync' and no accessible extension method 'CloseAsync' accepting a first argument of type ...

Our code has not changed.

In `4.10.0` `System.ServiceModel.ClientBase` had `CloseAsync`
Today, in `4.10.1` it does not.

**Expected behavior**
No breaking changes in a minor update - this should be a major version number change to `5.*` or above.

**Workaround**
This can be worked around by forcing all dependencies that use the service model primitives to a specific version:

Replace in the `.csproj`:

```xml
    <PackageReference Include="System.ServiceModel.Http" Version="4.10.*" />
```

With
```xml
    <PackageReference Include="System.ServiceModel.Http" Version="4.10.0" />
```

**Comment by trejjam** [comment]
`ClientBase`[https://github.com/dotnet/wcf/blob/main/src/System.ServiceModel.Primitives/src/System/ServiceModel/ClientBase.cs#L356] in this repository still contains `CloseAsync`, and it did not change since 9/2022. My guess is that someone who published 4.10.1 packed some really old version :/

**Comment by KeithHenry** [comment]
@trejjam these are the core definitions for WCF in .NET - is the deployment process that fragile?

Everyone who uses `4.10.*` and `CloseAsync()` (instead of the sync-blocking `Close()`) will have compile errors today that they did not yesterday. When can we expect a `4.10.2` with this fixed?

**Comment by trejjam** [comment]
I do not know. I am not maintainer. I just decompiled 4.10.0 and 4.10.1 and compared them with this repository. I found the issue because of broken dependabot PR build in my repository.

**Comment by mconnew** [comment]
I'm looking into this. The package metadata states it's built from commit b508e0e947d4986f76557756e16c4f7fa2a305c1 which does have the ClientBase\<TChannel\>.CloseAsync() method as can be seen [here](https://github.com/dotnet/wcf/blob/b508e0e947d4986f76557756e16c4f7fa2a305c1/src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.Netcoreapp.cs#L17). I'll update when I know more.

**Comment by mconnew** [comment]
I found the problem. In 4.10.0 the System.ServiceModel.Primitives package has reference assemblies for netstandard2.0 and net6.0. The CloseAsync method isn't there for netstandard2.0 as that only has api's common to .NET Framework and .NET. When you target net6.0, you get a few more async based api's including ClientBase\<TChannel\>.CloseAsync() which don't exist on .NET Framework. In preparing for this release, we had some build issues because older .NET versions are no longer in support so some tfm's were updated. This accidentally added a new reference tfm of net7.0 which looks like the netstandard2.0 version of the api's instead of net6.0.  
We'll release a 4.10.2 in the next couple of days with either a fixed net7.0 reference assembly, or without the net7.0 folder (so you'll pick up the net6.0 version instead).

**Comment by mconnew** [comment]
We've unlisted the 4.10.1 package from nuget. What unlisting means is if you have explicitly set 4.10.1 as your version, it can still be fetched from nuget and used, but when the nuget package manager is querying for versions (ie you have specified 4.10.*), it won't be found and you will get the 4.10.0 version returned as the latest.  
We'll publish a fixed version as soon as we can. The only difference between 4.10.0 and 4.10.1 (other than this unintentional break) was to update the version of System.Security.Cryptography.Xml to help with dependency scanning tools flagging a vulnerable version. The security bug fixed in the crypto library is in a feature which the WCF client doesn't use so it was purely a "quiet the tooling" release.

**Comment by HongGit** [comment]
[WCF Client 4.10.2](https://github.com/dotnet/wcf/releases/tag/v3.4.1-rtm) was released today.
