### ISSUE TITLE
Support NetHttpsBinding with TransportWithMessageCredential

### ISSUE THREAD

**Issue by Shuyu-Zhao** [dotnet/wcf#5379]
**Issue:** When creating a new NetHttpsBinding(BasicHttpsSecurityMode.TransportWithMessageCredential) using System.ServiceModel.Http(version 4.10.0), the problems exists. 

**Error:** The value 'TransportWithMessageCredential' is not supported in this context for the binding security property 'securityMode'.

A sample:
![b9f32688-97b6-4f6a-af07-0ea9489cb67f](https://github.com/dotnet/wcf/assets/144762638/324d2616-501b-455f-8e71-d79601e9d39b)

**Comment by mconnew** [comment]
Just use NetHttpBinding. The only difference between NetHttpBinding and NetHttpsBinding is the default security mode (None vs Transport) and the class names for some of the properties are different but have all the same property names. This is why we didn't add NetHttpsBinding, because it's just semantic sugar around using NetHttpBinding but with security mode of Transport by default.
