### ISSUE TITLE
Got the "An HTTP Content-Type header is required for SOAP messaging and none was found" error when the content-type header has multiple values

### ISSUE THREAD

**Issue by lucassantosTI** [dotnet/wcf#5425]
**Describe the bug**
I got the "An HTTP Content-Type header is required for SOAP messaging and none was found" exception when I sent a third-party webservice request.

This errors occurs because the server send me a reply with a Content-Type header with multiple values.

**My request is like this:**
```
POST http://url/service.asmx HTTP/1.1
Content-Type: text/xml;charset=utf-8
SOAPAction: "http://url/serviceAction"
Host: url
Content-Length: 424
Expect: 100-continue
Accept-Encoding: gzip, deflate
Connection: Keep-Alive

<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><serviceAction xmlns="http://url"><ID_SATTRANS>9852365</ID_SATTRANS><mensagemLivre>Teste desenvolvimento</mensagemLivre></serviceAction></s:Body></s:Envelope>
```

**And I got this response from the server:**
```
HTTP/1.1 500 Internal Server Error
Cache-Control: private
Content-Type: text/xml; charset=utf-8,text/xml;charset=ISO-8859-1
Server: Microsoft-IIS/10.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Thu, 15 Feb 2024 18:55:46 GMT
Connection: close
Content-Length: 422

<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><soap:Fault><faultcode>soap:Server</faultcode><faultstring>Server was unable to process request. ---&gt; The validation business rule violated.</faultstring><detail /></soap:Fault></soap:Body></soap:Envelope>
```
In this response we have this on content-type header: `Content-Type: text/xml; charset=utf-8,text/xml;charset=ISO-8859-1` and it's results in an empty `ContentType` value on the `HttpResponseMessage`. 
I try to treat that issue creating a custom `MessaceEncoder` (https://learn.microsoft.com/en-us/dotnet/framework/wcf/samples/custom-message-encoder-custom-text-encoder) and custom `EndpointBehavior` (https://learn.microsoft.com/en-us/dotnet/api/system.servicemodel.description.iendpointbehavior?view=dotnet-plat-ext-8.0) but both with unsuccess, watching the code of the `System.ServiceModel.Http` , I found the line of code that threw the validation in the `ContentType`:
https://github.com/dotnet/wcf/blob/07f0d0c43119763b505be80d3219a86c8b70e547/src/System.ServiceModel.Http/src/System/ServiceModel/Channels/HttpResponseMessageHelper.cs#L135C3-L137C11

To solve that I change the code from:

```csharp
var mediaValueContentType = content.Headers.ContentType;
_contentType = mediaValueContentType == null ? string.Empty : mediaValueContentType.ToString();
```

to:

```chsarp
var mediaValueContentType = content.Headers.ContentType;
if (
    mediaValueContentType == null
    && content.Headers.TryGetValues("Content-Type", out var values)
    && values?.Count() > 0)
{
    values = values.First().Split(",", StringSplitOptions.RemoveEmptyEntries);
    if (values?.Count() > 0)
    {
        mediaValueContentType = MediaTypeHeaderValue.Parse(values.First());
    }
}
```

When, if the `mediaValueContentType` is null, tries to get the value for the Content-Type using `TryGetValues` approach.

Finally I using the complied DLL's with this changes in my project, but I like to submit this change to the repo if more devs having this issue.

**Comment by mconnew** [comment]
The spec for Content-Type header is [listed here](https://www.rfc-editor.org/rfc/rfc7231#section-3.1.1.5). It states the format is:
```
   Content-Type = media-type
```
It provides a link to the spec for media-type which [can be found here](https://www.rfc-editor.org/rfc/rfc7231#section-3.1.1.1). It's a little too involved to try and describe here concisely, but the important thing is it's not a multi-value header. Some headers are single value, others accept a comma delimited list of values, and Content-Type is a single value header. This means the header the server is providing is invalid. When you think about it, that should make sense as you can't have text simultaneously encoded two different ways.

HttpResponseMessage is returning null in the Content-Type header because the parser used is a single value parser and it can't parse the provided value as it's invalid. I'm not going to accept a change to enable WCF to accept HTTP responses which are invalid and explicitly against the HTTP specs. Specs are important and are there for a reason.

You should be able to solve this with a custom MessageEncoder which expects the content type to be the empty string.

**Comment by lucassantosTI** [comment]
@mconnew I know, I sent this RFC to my partner before, but he told me he couldn't change the code, and emphasized that if the same service is consumed by others, using JAVA or .NET Framework.

Because this I want to fork the repo and adds the implementation contained in the PR.

**Comment by mconnew** [comment]
You should be able to do this with a custom MessageEncoder that wraps the existing one and just replaces the expected ContentType. If there's a problem with that, I'm happy to ship any changes needed to fix that scenario so you just need a wrapping MessageEncoder implementation.

**Comment by mconnew** [comment]
I just remembered another option you can do which is less intrusive. You can actually wrap the underlying HttpClientHandler with a custom HttpMessageHandler. You can find a really good blog post [describing this approach here](https://justsimplycode.com/2019/11/02/disable-header-100-continue-in-net-core-wcf-client/). The code you need is almost identical to what's provided in the blog. The only difference is that instead of modifying the outgoing ExpectContinue header before calling base.SendAsync, you would modify the incoming ContentType header after calling base.SendAsync so that the HttpResponseMessage that WCF is returned has a valid ContentType header.

**Comment by 0xced** [comment]
I just open sourced [Wcf.HttpClientFactory](https://github.com/0xced/Wcf.HttpClientFactory) which could help you achieve what Matt described in just two lines of code:

```csharp
var services = new ServiceCollection();
services.AddSingleton<InterceptingHttpMessageHandler>()
services.AddContract<MyService, MyServiceConfiguration>().AddHttpMessageHandler(sp => sp.GetRequiredService<InterceptingHttpMessageHandler>());
```

Then `MyService` can be injected wherever you need it.

The documentation in the README is still lacking but the xmldoc and the [HelloServiceTest code](https://github.com/0xced/Wcf.HttpClientFactory/blob/6254a6df13fddcd3143c0ece726ccd5778ff15c9/tests/HelloServiceTest.cs#L46) should help you getting started.

I have not yet published a NuGet package but if you recompiled WCF from source then using `Wcf.HttpClientFactory` from source should not be an issue for you. 😉

Please don't hesitate to ask me if something is unclear or doesn't work.

**Comment by 0xced** [comment]
@lucassantosTI Have you been able to use `Wcf.HttpClientFactory` to solve your problem? I'm interested to know how it worked for you and if the documentation was clear enough.

**Comment by lucassantosTI** [comment]
> @lucassantosTI Have you been able to use `Wcf.HttpClientFactory` to solve your problem? I'm interested to know how it worked for you and if the documentation was clear enough.

Hy @0xced doesn't work exactly how I needed it, We are using the change included in PR on this issue, and trying some help with the third-party to fix his webservice header.

**Comment by mconnew** [comment]
@lucassantosTI, take a look at the blog post, you should be able to do what you need by providing your own content type before returning the response to WCF. We've closed the PR as it's not a change we'll accept, and using the custom message handler capability mentioned in that blog post is sufficient to solve your problem. I'm going to close this issue as I don't see anything else that needs to be done or answered.
