### ISSUE TITLE
All calls to WCF service in .NET 8 extremely slow compared to .NET framework 4.8.1

### ISSUE THREAD

**Issue by OpenSourceIsEvil** [dotnet/wcf#5498]
I am attempting to convert a class library from .NET Framework 4.8.1 to .NET 8 that connects to an instrument that you communicate with via WCF. All calls to the server are much slower (not just the first call).

The performance test takes around 3 seconds in .NET Framework 4.8.1 (most of which is constructing the client proxy) but it takes 35 seconds in the project converted to .NET 8. The server and client are running locally on the same machine.

Attached is a stripped down very simple complete example with the same client code code in .NET framework 4.8.1 and in NET 8 and a performance test

The output from the performance test in the attached file on .NET Framework 4.8 is:

Start: 0
After constructor: 3310
Before loop: 3321
After loop: 3347

The output on .NET 8 is:

Start: 0
After constructor: 8508
Before loop: 12609
After loop: 35268

Added measurement for each method in the new code:
Start: 0
After constructor: 6567
Gaia Lock took: 2045
Gaia SetParameter took: 2043
Before loop: 10659
Gaia GetParameter took: 2030
Gaia GetParameter took: 2024
Gaia GetParameter took: 2047
Gaia GetParameter took: 2025
Gaia GetParameter took: 2030
Gaia GetParameter took: 2043
Gaia GetParameter took: 2052
Gaia GetParameter took: 2063
Gaia GetParameter took: 2042
Gaia GetParameter took: 2047
Gaia Unlock took: 2043 
After loop: 33112

It seems like there is a 2 second overhead on each call to the server

The proxy code was generated with: "svcutil /d:"$(ProjectDir)\service" %WSDLFILE% /language:C# /async /internal /namespace:*,Unisensor.Gaia.Webservices /noconfig"

Changed to: dotnet-svcutil -d "$(ProjectDir)\service" %WSDLFILE% --outputFile GaiaService.cs --sync --internal --namespace "*,Unisensor.Gaia.Webservices"

I have inspected the XML sent to the service with Fiddler and it seems to be identical. The server is written in C++ and can't be changed. I am running a freshly installed Windows 11.

I have updated the example with correct packages and the workaround
[WCFPerformanceProblem.zip](https://github.com/dotnet/wcf/files/15008764/WCFPerformanceProblem.zip)

**Comment by OpenSourceIsEvil** [comment]
The bug seems to be releated to DNS - if you pass an ip address instead of machine name there is no performance penalty

**Comment by peterkiss1** [comment]
Not sure what is happening but you are not even using the latest versions:
```
  <ItemGroup>
    <PackageReference Include="System.ServiceModel.Duplex" Version="4.10.*" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.10.*" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.10.*" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.10.*" />
    <PackageReference Include="System.ServiceModel.Federation" Version="4.10.*" />
  </ItemGroup>
```
The packages should be updated or removed as not all required or even exists for .NET 8.

**Comment by OpenSourceIsEvil** [comment]
@peterkiss1 Yeah sorry about that, my full solution had the correct package versions. I have updated the solution with the newest packages and the performance problem is even bigger. I have include the workaround in the newest version. In the performance test (GaiaNetworkInstrumentTests) line 61/62 you can uncomment to get the client proxy created with hostname or ip.

**Comment by mconnew** [comment]
@OpenSourceIsEvil, for the .NET 8 version of the test, I'm getting a fault exception come back saying "Failed setting parameter value (client does not hold lock)". The return value from the Lock() call passes. The server provides the client with a ClientId which is passed to the Lock() call. How does the server associate that lock with subsequent client calls as it's not passed as a parameter to SetParameter(). Is it expecting all calls to happen on the same socket?

**Comment by OpenSourceIsEvil** [comment]
@mconnew That sounds strange the performance tests spawns the webserver.exe you might have one running in background where you stopped the test before unlock was called. The server expects lock to be called - it verifies that all calls have the same IP as was used to call lock

**Comment by mconnew** [comment]
Does it keep a persistent state on disk? I did check for any left over processes and there weren't any.

**Comment by mconnew** [comment]
I worked out why the it was complaining about the lock, and why it likely wasn't on your machine. You pass -t 5000 to WebServer.exe which sets a 5 second timeout on the lock. The performance issue you're seeing is even worse on my device which meant the lock was expiring before the call happened. This is an issue in the .net runtime HttpClientHandler implementation. I understand why they made the change in behavior between HttpWebRequest on .NET Framework and HttpClientHandler on .NET as it's addressing a specific problem people had for years on .NET Framework, unfortunately the way they implemented the change was a naive approach which causes problems in a very specific scenario that you have.  

Here's what's happening. HttpClientHandler does a dns lookup to get the list of ip addresses and tries each one in turn. It tries the IPv6 addresses first, then tries the IPv4 addresses. As WebServer.exe only listens on an IPv4 address, each IPv6 attempt has to time out. Because I have wsl2 installed, along with a Wifi adapter and an ethernet adapter, Hyper-V with VM's, and a company VPN connection, I have a total of 6 IPv6 addresses that the Dns call will return. It takes 2 seconds for each connect attempt as it tries 5 times (getting a RST response each time), and waits half a second between each attemp (so 4 pauses), so each unique IPv6 address adds 2 seconds to the connection time. As I have 6 IPv6 addresses, it wastes 12 seconds before it successfully connects.  

Here's where the behavior of WebService.exe doesn't play well with the behavior of HttpClientHandler. In the response from WebService.exe, it sends the `Connection: close` response header, meaning the socket will be closed after the response is sent. This means the next request needs a new connection. Here's where the different between HttpWebRequest and HttpClientHandler comes in. HttpWebRequest reuses the last successful IP address, which in this case was an IPv4 address. The connection for the next request using HttpWebRequest on .NET Framework will succeed immediately. HttpClientHandler on the other hand goes back to its list of IP addresses and tries them all again, including the IPv6 addresses first. This means on my machine, each request has a 12 second delay before it can be sent.  

The reason why HttpClientHandler did this is because there were problems with how HttpWebRequest did things. It didn't honor DNS TTL times, so if you had a service which scaled up/down or simply replaced the hosts when deploying new versions, and did the transition by updating DNS records using a short TTL (1 - 2 mins DNS TTL isn't unusual for a cloud deployed service), HttpWebRequest would keep trying to use the same IP addresses, and would now no longer be able to communicate to the server. To solve this, instead of HttpClientHandler doing the Dns resolution and creating a socket using that IP address, if creates a new Socket using a DnsEndpoint with the hostname, and lets the Socket do a Dns lookup each time and connect. This means HttpClientHandler no longer has about which IP addresses didn't work, and there's no mechanism to pass that on to the Socket class. Basically HttpClientHandler has amnesia about which IP addresses didn't work.  

I'll be opening an issue in dotnet/runtime to report this problem. There is a simple solution for you though. There's a setting to disable IPv6 on a per process basis. You can either set the environment variable `DOTNET_SYSTEM_NET_DISABLEIPV6` to `true` before you launch the process, or you can call `AppContext.SetSwitch("System.Net.DisableIPv6", isEnabled: true)` at the start of your program. I couldn't get the tests working well with the second option as the test running infrastructure opens a socket to VS to report progress and once an AppContext value has been read, it's cached and you can't change it. In your actual app this might be an option though. To validate this for the unit tests, I added a file called `disableIPv6.runsettings` to the solution, and in the VS test explorer, configured this runsettings file to be used. In VS2022, you click the drop down arrow next to the settings cog in the test explorer -> Configure Run Settings -> Select Solution Wide runsettings file. Here's the contents of the .runsettings file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <RunConfiguration>
    <EnvironmentVariables>
      <DOTNET_SYSTEM_NET_DISABLEIPV6>true</DOTNET_SYSTEM_NET_DISABLEIPV6>
    </EnvironmentVariables>
  </RunConfiguration>
</RunSettings>
```

With this enabled, this was the output:
```
Start: 0
After constructor: 257
Before loop: 265
After loop: 280
```

**Comment by mconnew** [comment]
I just looked to see if there was something equivalent for .NET Framework and there is. Add a file to your test project called `testhost.dll.config` and set Copy to Output Directory to `Copy if newer`. Set the contents to this:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <system.net>
    <settings>
      <ipv6 enabled="false" />
    </settings>
  </system.net>
</configuration>
```

Then when you run the .NET Framework tests, the timings will again be better:
```
Start: 0
After constructor: 13215
Before loop: 13225
After loop: 13250
```

Between After Constructor and BeforLoop, you make 2 calls, one to Lock, and an initial SetParameter call. You can see that those two calls now are taking 10ms to complete where before you had a 4 second delay on .NET Framework to make that first connection.

**Comment by OpenSourceIsEvil** [comment]
@mconnew Thx for the detailed answers - I will try you suggestions.

**Comment by HongGit** [comment]
Close this issue as it's over a month.  Feel free to re-open if there are more questions.
