### ISSUE TITLE
Unencrypted data sent with secure profile activated for WCF NETTCP binding

### ISSUE THREAD

**Issue by lebronws** [dotnet/wcf#5587]
**Describe the bug**
1. Create a secure WCF service  and host it in a console application
2. Create a WCF client to invoke the WCF service
3. Use Wireshark to capture the packets and found the [PSH,ACK] packet between TCP handshake and TLS handshake

**To Reproduce**
4. The [WCFNettcpTLSServiceTest.zip] is one console application to test. you can use it to test in Visual studio.
5. you can replace the certificate by yours. 

[WCFNettcpTLSServiceTest.zip](https://github.com/user-attachments/files/15911187/WCFNettcpTLSServiceTest.zip)

**Expected behavior**
Use Wireshark to capture the packets and there should not be the [PSH,ACK] packet between TCP handshake and TLS handshake

**Screenshots**
See the red highlight content in the Wireshark screenshot for your reference.
![wireshark screenshot for WCF](https://github.com/dotnet/wcf/assets/156871110/20a1906c-c78a-45a5-bcbf-91e35da0ad8a)

**Additional context**

**Comment by lebronws** [comment]
[WCFNettcpTLSServiceTest.zip](https://github.com/user-attachments/files/15911120/WCFNettcpTLSServiceTest.zip)
![wireshark screenshot for WCF](https://github.com/dotnet/wcf/assets/156871110/7c903e04-564f-4916-884d-b6ab7d7f0162)
I created a new project to test it. you can follow this to reproduce it.

**Comment by mconnew** [comment]
This is correct and expected for the framing protocol used by NetTcp. It's not the same as HTTP, there's an initial handshake before security is established. In the initial handshake, the client sends an initial preamble which includes the framing protocol version and the mode of the connection (basically corresponds to streamed vs buffered). Then it sends the endpoint url that it wishes to connect to. If there's security configured, it then sends the mime type of the security it wishes to negotiate. In practical terms this means SSL or NegotiateStream (for Windows auth), but it could be something custom if you wrote a custom security upgrade provider. On the service side, once it has read the endpoint url, the connection gets routed to the relevant endpoint which then negotiates security. That endpoint then checks the security upgrade mime type and rejects the connection if it doesn't match. Once the mime type has been verified to match, it then hands over to SslStream/NegotiateStream to secure the connection. This is all documented in the MC-NMF protocol specification as [can be read here](https://learn.microsoft.com/en-us/openspecs/windows_protocols/mc-nmf/).  

The reason why this was done is because a single listening port can have multiple endpoints available on it, some will have security, other won't. Different endpoints can have different security, e.g. use different service certificates if using SSL. There's no way to know what security to use unless you know the endpoint before you negotiate the security.

**Comment by lebronws** [comment]
hi @mconnew,

ok, thanks for your clarification.
