### ISSUE TITLE
EndpointDispatcher entity contains no properties (System.ServiceModel.Primitives)

### ISSUE THREAD

**Issue by RuslanDziadik** [dotnet/wcf#5630]
**Describe the bug**
I am trying to migrate an existing project from .net48 to .net8. During migration an existing implementation of IEndpointBehavior I get stucked. Because the compiler does not found the properties DispatchRuntime/ChannelDispatcher, but if I look into the implementation the property is already there
(see 1st screenshot)

Also System.ServiceModel.Primitives does not provide access to public interface IErrorHandler
(see 2nd screenshot)

Targetframework: .net8.0-windows
Packages:
System.ServiceModel.Primitives (8.0.0)

**To Reproduce**
1. Fiddle https://dotnetfiddle.net/ZzYmcG

**Expected behavior**
That the property can be access and provide the same behavior as before (net48), or another way how to access them

**Screenshots**
![image](https://github.com/user-attachments/assets/8037f12b-f3ba-4c01-bc0a-4feee1b15ae0)
![image](https://github.com/user-attachments/assets/50570c7b-b36c-4c24-9d54-7ff7d11e11d2)

**Comment by mconnew** [comment]
For setting an `IDispatchMessageInspector`, you can do it via a different API.
```c#
    public void ApplyClientBehavior(ServiceEndpoint endpoint, ClientRuntime clientRuntime)
    {
        clientRuntime.CallbackDispatchRuntime.MessageInspectors.Add(_myDispatchMessageInspector);
    }
```
For IErrorHandler, we haven't exposed this so an alternative solution will need to be found if your development timeline is shorter than the time it would take to add and release that api.  

Can you provide a little more info about what you do in your error handler implementation? For example, if you are logging exceptions, one possibility might be to set IncludeExceptionDetailInFaults to true, then in an IDispatchMessageInspector, check if the reply message is a fault message, and if it is, extract the exception callstack from the message body to log it. You would then optionally replace the reply message with one which doesn't have the callstack if revealing the exception callstack to the server is a problem (this is normally only cared about with the server sending it to the client). I believe there might be scenarios where this wouldn't be sufficient as there might be exceptions thrown which result in not being able to send a message to the server because the channel faulted. It really depends what your usage scenario is. If you can share, I might be able to suggest some alternatives.

**Comment by mconnew** [comment]
@RuslanDziadikm is my suggestion about logging based on the Message being a fault message sufficient or do you need a different solution?

**Comment by RuslanDziadik** [comment]
@mconnew yes, thank you! System.ServiceModel.Primitives for net8 is still missing some objects, like ServiceHostBase, that was there in framework48. fortunately that objects are mostly used on server side - so it forced us to split our libraries on client/server parts and upgrade client libs to net8
