### ISSUE TITLE
BasicHttpSecurity fails with 8.1

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/wcf#5690]
This worked with 8.0.0:

```csharp
 var binding = new BasicHttpsBinding()
 {
     MaxReceivedMessageSize = int.MaxValue,
     ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max,
     Security = new BasicHttpsSecurity()
     {
         Mode = BasicHttpsSecurityMode.Transport,
     },
 };
```

No longer works with 8.1.0 in .NET 8 library

`
'BasicHttpsSecurity' does not contain a constructor that takes 0 arguments
`

**Comment by mconnew** [comment]
I see that. We've adopted some new tooling which should auto generate the reference assembly source from the implementation. The constructor is public in the implementation, but for some reason the tooling generated it as internal. As you aren't setting anything else other than the mode on BasicHttpsSecurity, there's a simple workaround you can use while waiting for a fix.
```c#
var binding = new BasicHttpsBinding(BasicHttpSecurityMode.Transport)
{
    MaxReceivedMessageSize = int.MaxValue,
    ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max
};
```
If this was just sample code to illustrate the problem and you are modifying settings on BasicHttpsSecurity too, you will need to switch to setting properties after you have instantiated the class instead of using an object initializer block.
