### ISSUE TITLE
Description nuget package is missing ref assembly in 8.1

### ISSUE THREAD

**Issue by bbowyersmyth** [dotnet/wcf#5692]
**Describe the bug**
System.Web.Services.Description nuget package now has a ref folder in 8.1. But its empty so essentially has no api surface area.

**To Reproduce**
1. Add the System.Web.Services.Description nuget package to a new project
2. The namespaces System.Web.Services.Description and System.Web.Services.Configuration can not be found

**Expected behavior**
Same as 8.0. Namespaces and classes are public

**Comment by mconnew** [comment]
There were no code changes between 8.0 and 8.1, and this doesn't depend on any System.ServiceModel packages so you're safe to use 8.0 until we ship a fix. This happened because in some of our other packages, we're trying to suppress accidental usage on earlier dotnet versions as we now support targeting netstandard2.0, but don't have a runtime implementation which works on earlier dotnet versions. This package doesn't have a ref assembly as it doesn't need it. The build rule to emit the suppressing ref folder needed to be a little more constrained.
