### ISSUE TITLE
The ServiceCertRevoked test fails in ToF for CoreCLR

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#624]
It may be sporadic, but I just saw it fail running ToF against CoreCLR 
 --------------------------------
  Running Test: ExpectedExceptionTests.TCP_ServiceCertRevoked_Throw_MessageSecurityException
  Assert.True:Expected: SecurityNegotiationException, Actual: no exception
  Xunit.AssertTestException: Assert.True: Expected: SecurityNegotiationException, Actual: no exception
     at Xunit.Assert.HandleFail(String assertionName, String message) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 592
     at Xunit.Assert.True(Boolean condition, String message) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Assertion.cs:line 147
     at ExpectedExceptionTests.TCP_ServiceCertRevoked_Throw_MessageSecurityException() in e:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\tests\Scenarios\Client\ExpectedExceptions\ExpectedExceptionTests.cs:line 532
     at EntryPointMain.b__d() in e:\ProjectK\src\QA\ToF\PK\x86\rel\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Client\ExpectedExceptions\Client.ExpectedExceptions.Tests\Client.ExpectedExceptions.Tests.main.cs:line 26
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod(TestInfo t) in e:\ProjectK\src\QA\ToF\tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
  ---- Test FAILED ---------------

**Comment by hongdai** [comment]
It passed on my enlistment machine with the latest bit. @roncain , do you have more data such as how frequently you see it fails? So far it only repros on your machine.

**Comment by roncain** [comment]
It fails 100% of the time so far.  Verified again today 1/4/2016.  Could this be a timing issue with the CRL test logic?

**Comment by roncain** [comment]
It also fails with a different exception running in ToF against NET Native:
  Running Test: ExpectedExceptionTests.TCP_ServiceCertRevoked_Throw_MessageSecurityException
  Caught Unexpected exception:System.AggregateException: AggregateException_ctor_DefaultMessage ---> System.IO.IOException: An existing connection was forcibly closed by the remote host.
  
  An existing connection was forcibly closed by the remote host.
   ---> System.Exception: An existing connection was forcibly closed by the remote host.
  
  An existing connection was forcibly closed by the remote host.

**Comment by hongdai** [comment]
Sounds like a timing issue. We could change the test to work around it by retry for 3 times, wait for a few ms each time.

**Comment by roncain** [comment]
More info -- it always fails for me the first time I start the Bridge and run the tests. It passes if I leave the Bridge running and re-run the tests.  However if I exit the Bridge (which cleans up certs), restart it and rerun the tests, it fails again.  So unless we understand why there is a timing issue here, then maybe a few retries would be reasonable, providing it doesn't take too long before detecting a real failure.

**Comment by iamjasonp** [comment]
Wanted to open a bug on this, and yes, I confirm I see this too. 

This is still related to the certificate revocation information being cached. It's not apparent to me why this is happening only when running under ToF and not happening when running using just OSS.

We currently solve the certificate revocation issue in OSS by generating a certificates with a unique CRL URI (e.g., http://localhost:44283/resource/WcfService.CertificateResources.CertificateRevocationListResource?serialNum=**383a9eca9d1c5237**) where `383a9eca9d1c5237` is the serial number of the cert. This way, when each certificate is checked for revocation, there is a difference in query string, and so the OS should make a new request to the Bridge for the CRL. 

https://technet.microsoft.com/en-us/library/ee619723(v=ws.10).aspx describes the algorithm; I've been trying various methods to deterministically solve this for ToF no avail for now :frowning:

"A few retries"... we currently set any CRL to expire in five minutes ("next update" time), so that's how long we have to wait. We could potentially reduce the "next update" - but the danger in setting the "next update" field to a time that's too short is skew between machines in x-machine tests will cause CRLs to expire too soon, causing chain validation issues.

**Comment by iamjasonp** [comment]
You know - something we could do to help with the time skew is to run `net time \\servername /set /yes` prior to running tests. Maybe this might allow us to lower the CRL validity time on the Bridge to 1 min...
