### ISSUE TITLE
Create supported-feature matrix and release notes for RC2

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#665]
I recommend we clone the RC1 supported-feature matrix for RC2 and use it to help sign off RC2.  We should also update the individual per-package release notes in https://github.com/dotnet/wcf/tree/master/release-notes

**Comment by zhenlan** [comment]
@hongdai please add the table in PR #898 as an appendix to the supported feature table for RC2.

cc: @iamjasonp

**Comment by StephenBonikowsky** [comment]
Still needs to be done...

- [ ]  Updated with the correct version number and link to each of our packages.

- [ ] Review the content under the new section “Partially Working Features”, in particular Https/WebSockets/TransferMode_Streamed. I was starting to get confused as we have multiple Issues opened that all might be related to WebSockets and NetTcp and Streaming but because of the different platforms involved it is not clear to me if these are all different issues or related.
o	https://github.com/dotnet/wcf/issues/420
o	https://github.com/dotnet/wcf/issues/470
o	https://github.com/dotnet/wcf/issues/463

- [ ] Write a blurb about Message Security in the Not Supported Features section.

- [ ] In the Platforms section other than for UWP I didn’t have any other info than what version we are currently supporting, do we need to add anything else there?

- [ ] Some other new feature I can’t think of?

**Comment by StephenBonikowsky** [comment]
Done
