### ISSUE TITLE
ContractDescription.GetContract static methods are not available

### ISSUE THREAD

**Issue by zhech2** [dotnet/wcf#668]
I see that the GetContract method is implemented in System.ServiceModel.Primitives.  Is it possible to get access to ContractDescription.GetContract?

**Comment by roncain** [comment]
Hi @zhech2 .  ContractDescription.GetContract is not part of the public contract in WCF for .NET Core because we are trying to maintain parity with the existing Windows Phone and Windows Store contracts initially.  And then we can expand our contracts where needed to support API's like this one if there is sufficient need.

In the meantime, there is a technique we use that uses only public API's to accomplish the same thing.  You can see examples at https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Common/Unit/TestHelpers.cs#L78 which looks like this:
```
            CustomBinding binding = new CustomBinding();
            binding.Elements.Add(new TextMessageEncodingBindingElement());
            binding.Elements.Add(new HttpTransportBindingElement());
            EndpointAddress address = new EndpointAddress(FakeAddress.HttpAddress);

            ChannelFactory<T> factory = new ChannelFactory<T>(binding, address);
            ContractDescription contract = factory.Endpoint.Contract;
```

In this case, the "T" generic type is the Type of the WCF service type, like what you would have passed to ContractDescription.GetContract().  The code above does not actually require a running WCF service and will not try to access the network. You can see it is using a fake URL that looks like this (though any fake but legal-looking URL will work):

```
public static class FakeAddress
{
    public static string HttpAddress = "http://" + IPAddress.None + ":0";
    public static string TcpAddress = "net.tcp://" + IPAddress.None + ":0";
}
``` 

Under the covers, it calls non-public API's that do the equivalent of ContractDescription.GetContract.

Would this work for you?

**Comment by zhech2** [comment]
Yes, that will work.  Thanks for your assistance on this.

**Comment by roncain** [comment]
Thanks @zhech2 .   I'm closing this issue since that works for you but feel free to open new issues if you run into problems or find other API's you need.  After we release our first set of stable packages, we'll consider what new (or existing in full framework) API's to add back to the NET Core contracts.
