### ISSUE TITLE
Investigate if it's possible to enable basic authentication test without a domain

### ISSUE THREAD

**Issue by hongdai** [dotnet/wcf#69]
Basic authentication test is currently disabled as the test needs to be run on a domain with domain user. We need to investigate if it's possible to run it without a domain.

**Comment by iamjasonp** [comment]
Note that: 
* Account doesn't need to be on a domain, but right now support on Windows seems to be for users defined in Windows only (local users are fine). 
* This issue is going to rear its head in Digest authentication as well. 
* It might be possible to have basic work with a custom username and password validator in WCF, if selfhosted.

**Comment by roncain** [comment]
Reopened because test Https\ClientCredentialTypeTests.cs still has [ActiveIssue] for it.  We need to update the test with an ActiveIssue that is open

**Comment by mconnew** [comment]
This bug is for basic auth. Issue #653 is for Digest auth.

**Comment by hongdai** [comment]
To clarify, this bug has been fixed by https://github.com/dotnet/wcf/pull/85 a while ago. It is reopened by Ron as the Digest auth test marked with this issue number by accident. https://github.com/dotnet/wcf/pull/653 fixed the issue number for Digest auth test. Hence reclose this bug.
