### ISSUE TITLE
Aync APIs genereated by ASR do not work for NetTcpBinding endpoint

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#78]
In a UWP app, use "Add Service Reference" to generate a service client. All the operation APIs will be async. They work fine for http endpoint, but hangs for NetTcpBinding endpoint. This repros for both debug and release mode, so I suspect this is not specific to .NET Native.

**Comment by zhenlan** [comment]
Update:
This appears only to be a problem if the operation call is made like "GetDataAsync(...).Result". This worked fine if the call is make like "await GetDataAsync(...)" and the caller function is changed to be async. I still do not understand why this is only a problem for tcp binding. I am using VS2015 RC build.

**Comment by hongdai** [comment]
Update: Async Apis using NetTcpBinding endpoint does not appear work for coreclr either.

**Comment by mconnew** [comment]
This was caused by async continuations on the Open code path being posted to the synchronization context instead of the thread pool. This wasn't an issue with the HTTP transport as there is no async work being done on the Open code path whereas NetTcp needs to open a socket which runs asynchronously.
