### ISSUE TITLE
Define requirements for automating OuterLoop tests cross-machine

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#791]
OuterLoop tests require the Bridge to be running on a Windows machine.  Xplat test therefore need to involve 2 machines, one with the OS to run the test, and one with Windows to run the Bridge.

As a first step, we need to name the scenarios we want to support, including:
  1. Should it support being used to test PR's automatically via GitHub?
  2. Should we assume the Bridge machine can always be spun-up and created for each unique test run?
  3. Should we create a long-running Bridge machine tests know about and can use without starting it?
  4. Should the Bridge be capable of servicing multiple clients at a time, each with different test resource versions?
  5. Which test frameworks need this?  Helix?  ToF?  Developer's machine running Linux?

**Comment by roncain** [comment]
This issue is intended to serve as the discussion area for which scenarios we need to support.  Feel free to add comments to this issue.

/cc @zhenlan @hongdai @stebon @iamjasonp @mconnew

**Comment by hongdai** [comment]
Scenario 6: How to update server when there are new tests require server changes.
Scenario 7: Should we keep Server backwards compat? i.e. previous milestone tests can run against the latest one.

As for scenarios priority:
1) Official Lab runs
2) Dev machine, including test PR's.

**Comment by roncain** [comment]
Regarding scenarios 6 and 7 -- I think it's important to distinguish between updating the Bridge code and the resource code that the Bridge uses to start WCF services.  I personally believe keeping the WCF Services themselves backward compatible is not achievable.  But I believe creating a Bridge that adapts to changing resources (WCF Services) is critically important if we try to maintain a long-running Bridge machine.  Issue #779 is intended to go more deeply into this scenario after we have decided whether a long-running Bridge is a requirement.

**Comment by hongdai** [comment]
Making the WCF service backward compatible has the advantage that all lab runs + E2E verification can simply use it. Adapts to changing resources approach require extra manual step to get the matched version resource code.

As long as we don't change existing service interfaces, this should be achievable.

**Comment by roncain** [comment]
I think our experience already tells us that we regularly change service interfaces for every new test scenario.  And WCF Services are not the only resources maintained by the Bridge.  I guess the key point here is that Scenario 7 is a proposed solution to the issue of maintaining a long-running Bridge instance.  It would not be an issue if a Bridge machine is spun-up for every unique test run.

So the fundamental questions we need to answer are:
 * What are the advantages and disadvantages of creating a new Windows VM to host the Bridge for each unique test run?
 * What are the advantages and disadvantages of maintaining one or more long-running Bridges that can be uses for unique test runs?

Long-running Bridge machines may be easier to adapt to lab automation scenarios, but that has its own costs.

**Comment by hongdai** [comment]
Changing service interfaces by adding new methods are backwards compatible - we typically add new methods for new tests. I agree WCF Services are not the only resources maintained by the Bridge could be a blocker here.

As for the fundamental questions we need to answer:
I see more advantages of maintaining a long running bridges:
1) test run are faster as it does not wait for service to start.
2) More reliable result because there will be no service start up intermittent issues.
3) Does not need to think about set up server on Dev box, or hand repro to external team.
4) automate Creating a new winodws VM to host the Bridge for each unique test run is costly, in terms of both machine resources and automation efforts.

**Comment by iamjasonp** [comment]
> Should it support being used to test PR's automatically via GitHub?

Yes, I think we should consider supporting allowing PRs to be tested via GitHub; as we've seen lately, it's nice to have a sane environment to run tests in and offloading some verification work to the CI system is desirable.

For CI Linux tests though, I was thinking of a little bit of a novel solution; we could create a Jenkins build flow that will build in Linux, fire up a Bridge in the `windows-elevated` pool, run tests, and then upon completion of the Linux x-machine tests, shut down the Bridge. This should be doable, but more investigation would be needed. 

> Should we assume the Bridge machine can always be spun-up and created for each unique test run?

It'd be kind of cool to have some kind of isolation per client ("Should the Bridge be capable of servicing multiple clients at a time, each with different test resource versions?"), but I don't know that we should keep different test resource versions. Seems like a headache. 

> Should the Bridge be capable of servicing multiple clients at a time, each with different test resource versions?

Yes, Bridge should be capable of servicing multiple clients. No, they should not have different test resource versions - possibly except for when we do a release. 

My personal thinking is that, for the most part, test resources are going to be additive to whatever already exists; I think it's reasonable for us to assume that testers wanting to use a shared CI machine should be asked to move to the latest test resource versions.

Perhaps it'd be interesting to incorporate a version number that passes between the BridgeClient and Bridge - but just used as a sanity check rather than used to maintain more than one version. 

> Should we create a long-running Bridge machine tests know about and can use without starting it?

I tend to want this, but more for tests not launched via Jenkins. For CI, we might be able to use the solution above. 

> Which test frameworks need this? Helix? ToF? Developer's machine running Linux?

All of the above, I think. As for a developer machine running Linux, this is all well and good as long as they are not introducing new Bridge resources; I think that any new resources will still need to be tested on a dev's Windows box... that is, do not allow devs to push code to a common Bridge machine to host. The code running on a proposed shared Bridge machine must have been vetted. If we add/modify tests resulting in changes to resources, we can ask devs to rebase. 

> How to update server when there are new tests require server changes.

Perhaps we could have Jenkins do this work automatically (i.e., when we notice a commit in the Bridge/ subdirectory, then it causes a bunch of actions to happen). Maybe use [ifttt](https://ifttt.com/) or something :) More research needed.

> Should we keep Server backwards compat? i.e. previous milestone tests can run against the latest one.

See above - though I see your point about keeping servers around for milestones and releases. 

> Wcf server can be access everywhere.

Security considerations... to discuss :) 

--- 

> What are the advantages and disadvantages of creating a new Windows VM to host the Bridge for each unique test run?

We used to do this for WCF desktop. Except it meant that we lengthened each test run by a long time while we spun stuff up. 

That said, as long as we're diligent about cleaning up in all circumstances and don't dirty the machine, we shouldn't need a new VM each time, just a clean Bridge launch. 

> What are the advantages and disadvantages of maintaining one or more long-running Bridges that can be uses for unique test runs?

I think @hongdai mostly captured what I was thinking for this already.

**Comment by zhenlan** [comment]
Based on discussions so far, these will be the scenarios that I think we will need to cover by the design of our outerloop testing infrastructure:

1. Automated nightly lab runs
  1. Test Net Native from ProjectN branch
  2. Test Net Native from ProjectK branch
  3. Test CoreCLR from ProjectK branch (including all applicable platforms, eg. Windows, Linux, Mac etc.)
  4. Test NETCOREFORCORECLR from ProjectK branch
2. PR’s tested on CI machines
  1. Platforms may include Windows, Mac, Linux, NetNative, …
3. Dev experience (on all platforms)
  1. I am working on a fix/feature and I want to test it locally before sending a PR
  2. I want to buddy build/test a PR/shelvset from a peer
  3. I have a shelveset/private build and I want to test it in the lab

I agree the WCF test services need to be updated promptly to match the payload of client tests, which means services should be updated nightly for scenario 1 and per PR for scenario 2. Devs should maintain her/his own services just like we are doing today, but we should make it easy for devs to spin up her/his own services either self hosted or IIS hosted.

Ideally, we can separate the server logic (ie., setup, activation, cleanup and state) from client tests so that our tests can run from any infrastructure (eg., Helix or ToF).

**Comment by roncain** [comment]
@hongdai has addressed the automated nightly build portion of this.  Leaving this issue open as the discussion issue for getting basic CI automation working multi-machine.

**Comment by roncain** [comment]
Closing now because we have moved to the new test infrastructure and added support to CI to use the new PR service, based on these discussions.
