### ISSUE TITLE
TestCase is not validating anything?

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#835]
ExpectedExceptionTests.TCP_ServiceCertFailedCustomValidate_Throw_Exception

Does not appear to be validating anything, based on the title it expects an exception but the catch doesn't validate anything.

So the test will pass whether an exception is thrown or not, and if it throws an exception it doesn't do an Assert on anything, there is no validation being done.

If the test were validating the Exception I would currently expect it to be failing for Issue #833 which is what the other two TCP related expected exception tests are failing for.

**Comment by StephenBonikowsky** [comment]
Once this test is fixed and confirmed to then fail on NetNative it should be added to the list of failing tests in Issue #833

**Comment by iamjasonp** [comment]
@StephenBonikowsky I'm looking at the following file: 

https://github.com/dotnet/wcf/blob/25ecad2fa533c88f5eee10f706140a3c0fae56fa/src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.cs#L450

* Line 465 - checks to ensure that the call *must not* succeed (i.e., an exception must be thrown) 
* Line 472 - validates the exception type 
* Line 475 - validates the exception message
* If an exception is thrown but not a CommunicationException, then the harness should catch that. 

Am I missing something?

**Comment by roncain** [comment]
Should we just make the test use Assert.Throws?  It would be clearer what it is doing, and we can still check the exception contents.

**Comment by iamjasonp** [comment]
> Should we just make the test use Assert.Throws? It would be clearer what it is doing, and we can still check the exception contents.

I think that's a good way to approach verification here, assuming there are no caveats to why we avoided using that before.

**Comment by StephenBonikowsky** [comment]
Sorry guys, I copied the wrong test case name into the title. The test I meant was...
TCP_ServiceCertFailedCustomValidate_Throw_Exception

I'll update the title.

**Comment by iamjasonp** [comment]
I see what's happening here. We set [here](https://github.com/dotnet/wcf/blob/25ecad2fa533c88f5eee10f706140a3c0fae56fa/src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.cs#L496)

```csharp
   factory.Credentials.ServiceCertificate.Authentication.CustomCertificateValidator = new MyCertificateValidator();
```

MyCertificateValidator in turn is: 


```csharp 
     public override void Validate(X509Certificate2 certificate) 
     { 
         if (certificate.IssuerName.Name != "RandomOne") 
         { 
             throw new Exception(exceptionMsg); 
         } 
     } 
```

So the actual validation is happening inside the Validate method (i.e., the certs we use are actually issued by "DO_NOT_TRUST_WcfBridgeRootCA", but we are expecting "RandomOne" in this validator). This is a little confusing, I agree. 

I think a more clear way of doing this is to make the validator check for the `certificate.IssuerName.Name == "RandomOne"`, and we throw here. We then catch the exception that is thrown in the text by using an Assert.Throws. That would feel more like what you'd see in real life - i.e., "something is not what I expected, throw an exception" rather than "something is not what I expected, continue and let the method (and therefore test) succeed"
