### ISSUE TITLE
Investigate and resolve use of cookies in UWP apps

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#908]
The current approach to set the CookieContainer in WCF is predicted to have issues in UWP apps because the underlying cookie container cannot be set.  We need to confirm this, and if necessary explicitly copy cookies over to the underlying cookie container.  @mconnew has more details of the issues involved.

**Comment by mconnew** [comment]
I verified, the issue is you can't set it if ServiceModelHttpMessageHandler.UseCookies is set to false. The change made by @roncain in HttpChannelFactory in #905 avoids the issue. As we will be removing ServiceModelHttpMessageHandler at some point in the future (we have a copied and modified version) when HttpClientHandler supports client certificates, this change should remain so that we continue to work with the behavior in HttpClientHandler. In other words, the fix should remain as is and cookies should work in UWP apps.
