### ISSUE TITLE
Response delay while streaming via NetTcp on service shutdown

### ISSUE THREAD

**Issue by orgaksm** [dotnet/wcf#977]
Related to [this post](http://stackoverflow.com/questions/17400589/wcf-response-to-client-delayed-when-transferring-file-to-server-with-transfermo) on stackoverflow.

The problem is that when the service will be closed, the client is waiting until time out, which is defined by receiveTimeout and sendTimeout of client and server, to throw an exception that the socket connection is not available. Both values must be high, because if they are low, slow connections cannot download or upload files, because the timeout interrupts the process.

When I download a file, it gets stuck in the CopyTo/Read-method of the download stream.
I did a work around but it isn't a good approach:

```
const int bufferSize = 81920;
var buffer = new byte[bufferSize];

do
{
    fileService.IsAlive();
    var bytesRead = downloadStream.Read(buffer, 0, bufferSize); 
    if (bytesRead == 0)  
        break;
    stream.Write(buffer, 0, bytesRead); 
} while (true);
```

This procedure should be done by the connection protocol (netTcp/transferMode=streamed)

**Comment by mconnew** [comment]
The behavior you are seeing is due to the semantics of streamed mode compared with buffered. When using a buffered connection, underneath it's actually a duplex connection, even when using request/reply. A pending receive is always posted to accept incoming requests or replies to any outstanding requests. This is why you can have multiple outstanding requests sent on a single NetTcp connection from multiple threads with a single channel. With streamed mode, when a request is being made, the instance of the call owns the channel until the call has completed. The request stream is sent, and only after it has been sent do we issue a receive/read on the connection. This is because you can't have a reply to a request message if the request message hasn't actually been fully sent, even when the response message is a Fault message.  
You have a few options on how to deal with this depending on your requirements, most of which will require a change only in your service code. On the service side, if you have an exception thrown, you need to catch the exception, drain the incoming stream and then re-throw the exception which will cause the Fault message to be returned. As the response stream was completely read, the client has completed all it's sending and is now waiting for the response. This does require the entire request stream to be sent, and in the case of a large request failing early, this may be undesirable. If it's the case that it is undesirable to spend the time/bandwidth to receive the rest of the message, then you could fault the channel (using Abort()) on the service side. This will cause the socket to be disconnected and you will get a CommunicationException on the client side. This has the disadvantage of not receiving information about what went wrong, but will be pretty immediate.  
Another option which requires changes on the client and server side is to use two channels and use the second channel to receive OOB info about the status of the request on the first channel.

**Comment by orgaksm** [comment]
The problem is that I can't handle any exception on the server side, if the server crashes (eg. unplanned shutdown on remote server), but I need to know it immediately on client side.
For the moment I switched to http/transferMode=streamed, because the files will never be larger than 2gb.
